use mtdb
GO

DROP TABLE OBJ_INDEX_DATE
GO

CREATE TABLE OBJ_INDEX_DATE
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL DATE
)
GO

CREATE INDEX OBJ_INDEX_DATE_INDEX1 ON OBJ_INDEX_DATE (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DATE_INDEX2 ON OBJ_INDEX_DATE (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
