apply from: 'libs.gradle'
dependencies {
	implementation project(':iplass-core')
	implementation project(':iplass-web')
	implementation project(':iplass-gem')
	implementation project(':iplass-tools')
}

apply plugin: 'eclipse'

processResources {
	// 静的リソースをコピーする際に、org/iplass配下のファイルは除外する
	// GWT コンパイル結果と同じディレクトリに配置する
	// TODO META-INF/resources/admin/mtpadmin 配下に配置するように変更するか、iplass-admin-client-gwt プロジェクトに移動すべき
	exclude 'org/iplass/**'

	// 重複ファイル設定（コピーされたファイルを正とする）
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

def adminClientGwtCompileResult = project(':iplass-admin-client-gwt').layout.buildDirectory.dir('gwt/out/mtpadmin')
jar {
	dependsOn ':iplass-admin-client-gwt:compileGwt'
	includeEmptyDirs = false;

	// META-INF配下にgwtコンパイル結果をコピー
	into('META-INF/resources/admin/mtpadmin') { 
		from(adminClientGwtCompileResult)
		// TODO 現時点では processResources で除外した org/iplass/adminconsole/public 配下のファイルをコピーする必要がある
		from('src/main/resources/org/iplass/adminconsole/public')
		// TODO 現時点では processResources で除外した org/iplass/gwt/ace/public 配下のファイルをコピーする必要がある
		from('src/main/resources/org/iplass/gwt/ace/public')
	}
}

task copyStaticResources(type: Sync) {
	dependsOn('processResources')

	//静的リソースをコピー
	from layout.buildDirectory.dir('resources/main')
	//jar内のwebjarsフォルダ配下をコピー
	from (configurations.wjRuntime.collect {it.isDirectory() ? it : zipTree(it)}) {
		exclude 'META-INF/maven/'
		exclude 'META-INF/MANIFEST.MF'
	}
	into layout.buildDirectory.dir('tmp/staticresources')
	includeEmptyDirs = false
}

task archiveStaticResources(type: Zip) {
	dependsOn('copyStaticResources')

	archiveAppendix = 'staticresources'

	//META-INF/resourcesをZIP圧縮
	from (layout.buildDirectory.dir('tmp/staticresources/META-INF/resources')) {
		exclude 'jsp'
	}
}
