configurations {
	wjRuntime

	compileOnly.extendsFrom(jeecoreapis)
	compileOnly.extendsFrom(jeewebapis)
	runtimeOnly.extendsFrom(wjRuntime)

	gwtCompileOnly {
		extendsFrom(jeecoreapis)
		extendsFrom(jeewebapis)
	}
}

dependencies {
	//supercsv
	implementation sharedLib('net.sf.supercsv:super-csv')

	// commons-lang
	implementation sharedLib('org.apache.commons:commons-lang3')

	// commons-io
	implementation sharedLib('commons-io:commons-io')
	
	// commons-fileupload
	implementation sharedLib('org.apache.commons:commons-fileupload2-jakarta-servlet6')
	
	//jackson
	implementation 'com.fasterxml.jackson.core:jackson-databind'

	// gwt-servlet-jakarta
	implementation sharedLib('org.gwtproject:gwt-servlet-jakarta')

	wjRuntime sharedLib('org.webjars.npm:ace-builds')

	//smart gwt has no public maven repository
	compileOnly fileTree(rootProject.ext.localLibDir) {
		include 'smartgwt/**/*.jar'
	}
	compileOnly sharedLib('org.gwtproject:gwt-user')

 	// GWTコンパイル用依存関係
	// gwt
	gwtCompileOnly(sharedLib('org.gwtproject:gwt-dev')) {
		// java.xml パッケージを含む xml-apis ライブラリを推移依存するため除外
		exclude group: 'net.sourceforge.htmlunit', module: 'htmlunit'
		// NOTE: apache-jsp 関連のライブラリを推移依存する。害が無いので除外しないが不要ではある。
		//exclude group: 'org.eclipse.jetty'
	}
	gwtCompileOnly(sharedLib('org.gwtproject:gwt-codeserver')) {
		// java.xml パッケージを含む xml-apis ライブラリを推移依存するため除外
		exclude group: 'net.sourceforge.htmlunit', module: 'htmlunit'
		// NOTE: apache-jsp 関連のライブラリを推移依存する。害が無いので除外しないが不要ではある。
		//exclude group: 'org.eclipse.jetty'
	}
	gwtCompileOnly sharedLib('org.gwtproject:gwt-user')
	gwtCompileOnly sharedLib('org.gwtproject:gwt-servlet-jakarta')
	// jackson
	gwtCompileOnly platform(sharedLib('com.fasterxml.jackson:jackson-bom'))
	gwtCompileOnly 'com.fasterxml.jackson.core:jackson-databind'
	//smart gwt has no public maven repository
	gwtCompileOnly fileTree(rootProject.ext.localLibDir) {
		include 'smartgwt/**/*.jar'
	}
}
