ext {
	// TODO gwt plugin jakarta-servlet 版に対応していないので、バージョンを指定し依存関係を設定しない
	//gwtVersion = "2.10.0"
}

configurations {
	wjRuntime

	compileOnly.extendsFrom(jeecoreapis)
	compileOnly.extendsFrom(jeewebapis)
	runtimeOnly.extendsFrom(wjRuntime)
}

dependencies {
	// gwt
	implementation sharedLib('org.gwtproject:gwt-servlet-jakarta')
	
	//supercsv
	implementation sharedLib('net.sf.supercsv:super-csv')

	// commons-lang
	implementation sharedLib('org.apache.commons:commons-lang3')

	// commons-io
	implementation sharedLib('commons-io:commons-io')
	
	// commons-fileupload
	implementation sharedLib('org.apache.commons:commons-fileupload2-jakarta-servlet6')
	
	//jackson
	implementation 'com.fasterxml.jackson.core:jackson-databind'

	wjRuntime sharedLib('org.webjars.npm:ace-builds')
}
