use mtdb
GO

DROP TABLE LOB_STORE
GO

CREATE TABLE LOB_STORE
(
    TENANT_ID NUMERIC(7,0),
    LOB_DATA_ID NUMERIC(16,0),
    CRE_DATE DATETIME2(3),
    REF_COUNT NUMERIC(10,0),
    B_DATA VARBINARY(MAX),
    LOB_SIZE NUMERIC(16,0),
    CONSTRAINT LOB_STORE_PK PRIMARY KEY (TENANT_ID, LOB_DATA_ID)
)
GO
