use mtdb
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR
GO

CREATE TABLE OBJ_UNIQUE_STR
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR_INDEX1 ON OBJ_UNIQUE_STR (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR_INDEX2 ON OBJ_UNIQUE_STR (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__1
GO

CREATE TABLE OBJ_UNIQUE_STR__1
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__1_INDEX1 ON OBJ_UNIQUE_STR__1 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__1_INDEX2 ON OBJ_UNIQUE_STR__1 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__2
GO

CREATE TABLE OBJ_UNIQUE_STR__2
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__2_INDEX1 ON OBJ_UNIQUE_STR__2 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__2_INDEX2 ON OBJ_UNIQUE_STR__2 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__3
GO

CREATE TABLE OBJ_UNIQUE_STR__3
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__3_INDEX1 ON OBJ_UNIQUE_STR__3 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__3_INDEX2 ON OBJ_UNIQUE_STR__3 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__4
GO

CREATE TABLE OBJ_UNIQUE_STR__4
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__4_INDEX1 ON OBJ_UNIQUE_STR__4 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__4_INDEX2 ON OBJ_UNIQUE_STR__4 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__5
GO

CREATE TABLE OBJ_UNIQUE_STR__5
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__5_INDEX1 ON OBJ_UNIQUE_STR__5 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__5_INDEX2 ON OBJ_UNIQUE_STR__5 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__6
GO

CREATE TABLE OBJ_UNIQUE_STR__6
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__6_INDEX1 ON OBJ_UNIQUE_STR__6 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__6_INDEX2 ON OBJ_UNIQUE_STR__6 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__7
GO

CREATE TABLE OBJ_UNIQUE_STR__7
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__7_INDEX1 ON OBJ_UNIQUE_STR__7 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__7_INDEX2 ON OBJ_UNIQUE_STR__7 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__8
GO

CREATE TABLE OBJ_UNIQUE_STR__8
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__8_INDEX1 ON OBJ_UNIQUE_STR__8 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__8_INDEX2 ON OBJ_UNIQUE_STR__8 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__9
GO

CREATE TABLE OBJ_UNIQUE_STR__9
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__9_INDEX1 ON OBJ_UNIQUE_STR__9 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__9_INDEX2 ON OBJ_UNIQUE_STR__9 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__10
GO

CREATE TABLE OBJ_UNIQUE_STR__10
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__10_INDEX1 ON OBJ_UNIQUE_STR__10 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__10_INDEX2 ON OBJ_UNIQUE_STR__10 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__11
GO

CREATE TABLE OBJ_UNIQUE_STR__11
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__11_INDEX1 ON OBJ_UNIQUE_STR__11 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__11_INDEX2 ON OBJ_UNIQUE_STR__11 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__12
GO

CREATE TABLE OBJ_UNIQUE_STR__12
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__12_INDEX1 ON OBJ_UNIQUE_STR__12 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__12_INDEX2 ON OBJ_UNIQUE_STR__12 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__13
GO

CREATE TABLE OBJ_UNIQUE_STR__13
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__13_INDEX1 ON OBJ_UNIQUE_STR__13 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__13_INDEX2 ON OBJ_UNIQUE_STR__13 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__14
GO

CREATE TABLE OBJ_UNIQUE_STR__14
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__14_INDEX1 ON OBJ_UNIQUE_STR__14 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__14_INDEX2 ON OBJ_UNIQUE_STR__14 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__15
GO

CREATE TABLE OBJ_UNIQUE_STR__15
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__15_INDEX1 ON OBJ_UNIQUE_STR__15 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__15_INDEX2 ON OBJ_UNIQUE_STR__15 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__16
GO

CREATE TABLE OBJ_UNIQUE_STR__16
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__16_INDEX1 ON OBJ_UNIQUE_STR__16 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__16_INDEX2 ON OBJ_UNIQUE_STR__16 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__17
GO

CREATE TABLE OBJ_UNIQUE_STR__17
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__17_INDEX1 ON OBJ_UNIQUE_STR__17 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__17_INDEX2 ON OBJ_UNIQUE_STR__17 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__18
GO

CREATE TABLE OBJ_UNIQUE_STR__18
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__18_INDEX1 ON OBJ_UNIQUE_STR__18 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__18_INDEX2 ON OBJ_UNIQUE_STR__18 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__19
GO

CREATE TABLE OBJ_UNIQUE_STR__19
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__19_INDEX1 ON OBJ_UNIQUE_STR__19 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__19_INDEX2 ON OBJ_UNIQUE_STR__19 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__20
GO

CREATE TABLE OBJ_UNIQUE_STR__20
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__20_INDEX1 ON OBJ_UNIQUE_STR__20 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__20_INDEX2 ON OBJ_UNIQUE_STR__20 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__21
GO

CREATE TABLE OBJ_UNIQUE_STR__21
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__21_INDEX1 ON OBJ_UNIQUE_STR__21 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__21_INDEX2 ON OBJ_UNIQUE_STR__21 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__22
GO

CREATE TABLE OBJ_UNIQUE_STR__22
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__22_INDEX1 ON OBJ_UNIQUE_STR__22 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__22_INDEX2 ON OBJ_UNIQUE_STR__22 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__23
GO

CREATE TABLE OBJ_UNIQUE_STR__23
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__23_INDEX1 ON OBJ_UNIQUE_STR__23 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__23_INDEX2 ON OBJ_UNIQUE_STR__23 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__24
GO

CREATE TABLE OBJ_UNIQUE_STR__24
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__24_INDEX1 ON OBJ_UNIQUE_STR__24 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__24_INDEX2 ON OBJ_UNIQUE_STR__24 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__25
GO

CREATE TABLE OBJ_UNIQUE_STR__25
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__25_INDEX1 ON OBJ_UNIQUE_STR__25 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__25_INDEX2 ON OBJ_UNIQUE_STR__25 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__26
GO

CREATE TABLE OBJ_UNIQUE_STR__26
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__26_INDEX1 ON OBJ_UNIQUE_STR__26 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__26_INDEX2 ON OBJ_UNIQUE_STR__26 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__27
GO

CREATE TABLE OBJ_UNIQUE_STR__27
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__27_INDEX1 ON OBJ_UNIQUE_STR__27 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__27_INDEX2 ON OBJ_UNIQUE_STR__27 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__28
GO

CREATE TABLE OBJ_UNIQUE_STR__28
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__28_INDEX1 ON OBJ_UNIQUE_STR__28 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__28_INDEX2 ON OBJ_UNIQUE_STR__28 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__29
GO

CREATE TABLE OBJ_UNIQUE_STR__29
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__29_INDEX1 ON OBJ_UNIQUE_STR__29 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__29_INDEX2 ON OBJ_UNIQUE_STR__29 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__30
GO

CREATE TABLE OBJ_UNIQUE_STR__30
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__30_INDEX1 ON OBJ_UNIQUE_STR__30 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__30_INDEX2 ON OBJ_UNIQUE_STR__30 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__31
GO

CREATE TABLE OBJ_UNIQUE_STR__31
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__31_INDEX1 ON OBJ_UNIQUE_STR__31 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__31_INDEX2 ON OBJ_UNIQUE_STR__31 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
