use mtdb
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM
GO

CREATE TABLE OBJ_UNIQUE_NUM
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM_INDEX1 ON OBJ_UNIQUE_NUM (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM_INDEX2 ON OBJ_UNIQUE_NUM (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__1
GO

CREATE TABLE OBJ_UNIQUE_NUM__1
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__1_INDEX1 ON OBJ_UNIQUE_NUM__1 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__1_INDEX2 ON OBJ_UNIQUE_NUM__1 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__2
GO

CREATE TABLE OBJ_UNIQUE_NUM__2
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__2_INDEX1 ON OBJ_UNIQUE_NUM__2 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__2_INDEX2 ON OBJ_UNIQUE_NUM__2 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__3
GO

CREATE TABLE OBJ_UNIQUE_NUM__3
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__3_INDEX1 ON OBJ_UNIQUE_NUM__3 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__3_INDEX2 ON OBJ_UNIQUE_NUM__3 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__4
GO

CREATE TABLE OBJ_UNIQUE_NUM__4
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__4_INDEX1 ON OBJ_UNIQUE_NUM__4 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__4_INDEX2 ON OBJ_UNIQUE_NUM__4 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__5
GO

CREATE TABLE OBJ_UNIQUE_NUM__5
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__5_INDEX1 ON OBJ_UNIQUE_NUM__5 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__5_INDEX2 ON OBJ_UNIQUE_NUM__5 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__6
GO

CREATE TABLE OBJ_UNIQUE_NUM__6
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__6_INDEX1 ON OBJ_UNIQUE_NUM__6 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__6_INDEX2 ON OBJ_UNIQUE_NUM__6 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__7
GO

CREATE TABLE OBJ_UNIQUE_NUM__7
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__7_INDEX1 ON OBJ_UNIQUE_NUM__7 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__7_INDEX2 ON OBJ_UNIQUE_NUM__7 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__8
GO

CREATE TABLE OBJ_UNIQUE_NUM__8
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__8_INDEX1 ON OBJ_UNIQUE_NUM__8 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__8_INDEX2 ON OBJ_UNIQUE_NUM__8 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__9
GO

CREATE TABLE OBJ_UNIQUE_NUM__9
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__9_INDEX1 ON OBJ_UNIQUE_NUM__9 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__9_INDEX2 ON OBJ_UNIQUE_NUM__9 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__10
GO

CREATE TABLE OBJ_UNIQUE_NUM__10
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__10_INDEX1 ON OBJ_UNIQUE_NUM__10 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__10_INDEX2 ON OBJ_UNIQUE_NUM__10 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__11
GO

CREATE TABLE OBJ_UNIQUE_NUM__11
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__11_INDEX1 ON OBJ_UNIQUE_NUM__11 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__11_INDEX2 ON OBJ_UNIQUE_NUM__11 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__12
GO

CREATE TABLE OBJ_UNIQUE_NUM__12
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__12_INDEX1 ON OBJ_UNIQUE_NUM__12 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__12_INDEX2 ON OBJ_UNIQUE_NUM__12 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__13
GO

CREATE TABLE OBJ_UNIQUE_NUM__13
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__13_INDEX1 ON OBJ_UNIQUE_NUM__13 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__13_INDEX2 ON OBJ_UNIQUE_NUM__13 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__14
GO

CREATE TABLE OBJ_UNIQUE_NUM__14
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__14_INDEX1 ON OBJ_UNIQUE_NUM__14 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__14_INDEX2 ON OBJ_UNIQUE_NUM__14 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__15
GO

CREATE TABLE OBJ_UNIQUE_NUM__15
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__15_INDEX1 ON OBJ_UNIQUE_NUM__15 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__15_INDEX2 ON OBJ_UNIQUE_NUM__15 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__16
GO

CREATE TABLE OBJ_UNIQUE_NUM__16
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__16_INDEX1 ON OBJ_UNIQUE_NUM__16 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__16_INDEX2 ON OBJ_UNIQUE_NUM__16 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__17
GO

CREATE TABLE OBJ_UNIQUE_NUM__17
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__17_INDEX1 ON OBJ_UNIQUE_NUM__17 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__17_INDEX2 ON OBJ_UNIQUE_NUM__17 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__18
GO

CREATE TABLE OBJ_UNIQUE_NUM__18
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__18_INDEX1 ON OBJ_UNIQUE_NUM__18 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__18_INDEX2 ON OBJ_UNIQUE_NUM__18 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__19
GO

CREATE TABLE OBJ_UNIQUE_NUM__19
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__19_INDEX1 ON OBJ_UNIQUE_NUM__19 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__19_INDEX2 ON OBJ_UNIQUE_NUM__19 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__20
GO

CREATE TABLE OBJ_UNIQUE_NUM__20
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__20_INDEX1 ON OBJ_UNIQUE_NUM__20 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__20_INDEX2 ON OBJ_UNIQUE_NUM__20 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__21
GO

CREATE TABLE OBJ_UNIQUE_NUM__21
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__21_INDEX1 ON OBJ_UNIQUE_NUM__21 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__21_INDEX2 ON OBJ_UNIQUE_NUM__21 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__22
GO

CREATE TABLE OBJ_UNIQUE_NUM__22
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__22_INDEX1 ON OBJ_UNIQUE_NUM__22 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__22_INDEX2 ON OBJ_UNIQUE_NUM__22 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__23
GO

CREATE TABLE OBJ_UNIQUE_NUM__23
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__23_INDEX1 ON OBJ_UNIQUE_NUM__23 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__23_INDEX2 ON OBJ_UNIQUE_NUM__23 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__24
GO

CREATE TABLE OBJ_UNIQUE_NUM__24
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__24_INDEX1 ON OBJ_UNIQUE_NUM__24 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__24_INDEX2 ON OBJ_UNIQUE_NUM__24 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__25
GO

CREATE TABLE OBJ_UNIQUE_NUM__25
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__25_INDEX1 ON OBJ_UNIQUE_NUM__25 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__25_INDEX2 ON OBJ_UNIQUE_NUM__25 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__26
GO

CREATE TABLE OBJ_UNIQUE_NUM__26
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__26_INDEX1 ON OBJ_UNIQUE_NUM__26 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__26_INDEX2 ON OBJ_UNIQUE_NUM__26 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__27
GO

CREATE TABLE OBJ_UNIQUE_NUM__27
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__27_INDEX1 ON OBJ_UNIQUE_NUM__27 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__27_INDEX2 ON OBJ_UNIQUE_NUM__27 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__28
GO

CREATE TABLE OBJ_UNIQUE_NUM__28
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__28_INDEX1 ON OBJ_UNIQUE_NUM__28 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__28_INDEX2 ON OBJ_UNIQUE_NUM__28 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__29
GO

CREATE TABLE OBJ_UNIQUE_NUM__29
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__29_INDEX1 ON OBJ_UNIQUE_NUM__29 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__29_INDEX2 ON OBJ_UNIQUE_NUM__29 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__30
GO

CREATE TABLE OBJ_UNIQUE_NUM__30
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__30_INDEX1 ON OBJ_UNIQUE_NUM__30 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__30_INDEX2 ON OBJ_UNIQUE_NUM__30 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE OBJ_UNIQUE_NUM__31
GO

CREATE TABLE OBJ_UNIQUE_NUM__31
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NUMERIC
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_NUM__31_INDEX1 ON OBJ_UNIQUE_NUM__31 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_NUM__31_INDEX2 ON OBJ_UNIQUE_NUM__31 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
