use mtdb
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE
GO

CREATE TABLE OBJ_UNIQUE_DATE
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE_INDEX1 ON OBJ_UNIQUE_DATE (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE_INDEX2 ON OBJ_UNIQUE_DATE (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__1
GO

CREATE TABLE OBJ_UNIQUE_DATE__1
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__1_INDEX1 ON OBJ_UNIQUE_DATE__1 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__1_INDEX2 ON OBJ_UNIQUE_DATE__1 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__2
GO

CREATE TABLE OBJ_UNIQUE_DATE__2
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__2_INDEX1 ON OBJ_UNIQUE_DATE__2 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__2_INDEX2 ON OBJ_UNIQUE_DATE__2 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__3
GO

CREATE TABLE OBJ_UNIQUE_DATE__3
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__3_INDEX1 ON OBJ_UNIQUE_DATE__3 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__3_INDEX2 ON OBJ_UNIQUE_DATE__3 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__4
GO

CREATE TABLE OBJ_UNIQUE_DATE__4
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__4_INDEX1 ON OBJ_UNIQUE_DATE__4 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__4_INDEX2 ON OBJ_UNIQUE_DATE__4 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__5
GO

CREATE TABLE OBJ_UNIQUE_DATE__5
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__5_INDEX1 ON OBJ_UNIQUE_DATE__5 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__5_INDEX2 ON OBJ_UNIQUE_DATE__5 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__6
GO

CREATE TABLE OBJ_UNIQUE_DATE__6
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__6_INDEX1 ON OBJ_UNIQUE_DATE__6 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__6_INDEX2 ON OBJ_UNIQUE_DATE__6 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__7
GO

CREATE TABLE OBJ_UNIQUE_DATE__7
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__7_INDEX1 ON OBJ_UNIQUE_DATE__7 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__7_INDEX2 ON OBJ_UNIQUE_DATE__7 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__8
GO

CREATE TABLE OBJ_UNIQUE_DATE__8
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__8_INDEX1 ON OBJ_UNIQUE_DATE__8 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__8_INDEX2 ON OBJ_UNIQUE_DATE__8 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__9
GO

CREATE TABLE OBJ_UNIQUE_DATE__9
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__9_INDEX1 ON OBJ_UNIQUE_DATE__9 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__9_INDEX2 ON OBJ_UNIQUE_DATE__9 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__10
GO

CREATE TABLE OBJ_UNIQUE_DATE__10
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__10_INDEX1 ON OBJ_UNIQUE_DATE__10 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__10_INDEX2 ON OBJ_UNIQUE_DATE__10 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__11
GO

CREATE TABLE OBJ_UNIQUE_DATE__11
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__11_INDEX1 ON OBJ_UNIQUE_DATE__11 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__11_INDEX2 ON OBJ_UNIQUE_DATE__11 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__12
GO

CREATE TABLE OBJ_UNIQUE_DATE__12
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__12_INDEX1 ON OBJ_UNIQUE_DATE__12 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__12_INDEX2 ON OBJ_UNIQUE_DATE__12 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__13
GO

CREATE TABLE OBJ_UNIQUE_DATE__13
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__13_INDEX1 ON OBJ_UNIQUE_DATE__13 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__13_INDEX2 ON OBJ_UNIQUE_DATE__13 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__14
GO

CREATE TABLE OBJ_UNIQUE_DATE__14
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__14_INDEX1 ON OBJ_UNIQUE_DATE__14 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__14_INDEX2 ON OBJ_UNIQUE_DATE__14 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__15
GO

CREATE TABLE OBJ_UNIQUE_DATE__15
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__15_INDEX1 ON OBJ_UNIQUE_DATE__15 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__15_INDEX2 ON OBJ_UNIQUE_DATE__15 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__16
GO

CREATE TABLE OBJ_UNIQUE_DATE__16
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__16_INDEX1 ON OBJ_UNIQUE_DATE__16 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__16_INDEX2 ON OBJ_UNIQUE_DATE__16 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__17
GO

CREATE TABLE OBJ_UNIQUE_DATE__17
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__17_INDEX1 ON OBJ_UNIQUE_DATE__17 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__17_INDEX2 ON OBJ_UNIQUE_DATE__17 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__18
GO

CREATE TABLE OBJ_UNIQUE_DATE__18
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__18_INDEX1 ON OBJ_UNIQUE_DATE__18 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__18_INDEX2 ON OBJ_UNIQUE_DATE__18 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__19
GO

CREATE TABLE OBJ_UNIQUE_DATE__19
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__19_INDEX1 ON OBJ_UNIQUE_DATE__19 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__19_INDEX2 ON OBJ_UNIQUE_DATE__19 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__20
GO

CREATE TABLE OBJ_UNIQUE_DATE__20
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__20_INDEX1 ON OBJ_UNIQUE_DATE__20 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__20_INDEX2 ON OBJ_UNIQUE_DATE__20 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__21
GO

CREATE TABLE OBJ_UNIQUE_DATE__21
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__21_INDEX1 ON OBJ_UNIQUE_DATE__21 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__21_INDEX2 ON OBJ_UNIQUE_DATE__21 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__22
GO

CREATE TABLE OBJ_UNIQUE_DATE__22
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__22_INDEX1 ON OBJ_UNIQUE_DATE__22 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__22_INDEX2 ON OBJ_UNIQUE_DATE__22 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__23
GO

CREATE TABLE OBJ_UNIQUE_DATE__23
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__23_INDEX1 ON OBJ_UNIQUE_DATE__23 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__23_INDEX2 ON OBJ_UNIQUE_DATE__23 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__24
GO

CREATE TABLE OBJ_UNIQUE_DATE__24
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__24_INDEX1 ON OBJ_UNIQUE_DATE__24 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__24_INDEX2 ON OBJ_UNIQUE_DATE__24 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__25
GO

CREATE TABLE OBJ_UNIQUE_DATE__25
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__25_INDEX1 ON OBJ_UNIQUE_DATE__25 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__25_INDEX2 ON OBJ_UNIQUE_DATE__25 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__26
GO

CREATE TABLE OBJ_UNIQUE_DATE__26
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__26_INDEX1 ON OBJ_UNIQUE_DATE__26 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__26_INDEX2 ON OBJ_UNIQUE_DATE__26 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__27
GO

CREATE TABLE OBJ_UNIQUE_DATE__27
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__27_INDEX1 ON OBJ_UNIQUE_DATE__27 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__27_INDEX2 ON OBJ_UNIQUE_DATE__27 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__28
GO

CREATE TABLE OBJ_UNIQUE_DATE__28
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__28_INDEX1 ON OBJ_UNIQUE_DATE__28 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__28_INDEX2 ON OBJ_UNIQUE_DATE__28 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__29
GO

CREATE TABLE OBJ_UNIQUE_DATE__29
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__29_INDEX1 ON OBJ_UNIQUE_DATE__29 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__29_INDEX2 ON OBJ_UNIQUE_DATE__29 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__30
GO

CREATE TABLE OBJ_UNIQUE_DATE__30
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__30_INDEX1 ON OBJ_UNIQUE_DATE__30 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__30_INDEX2 ON OBJ_UNIQUE_DATE__30 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE OBJ_UNIQUE_DATE__31
GO

CREATE TABLE OBJ_UNIQUE_DATE__31
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATE
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_DATE__31_INDEX1 ON OBJ_UNIQUE_DATE__31 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_DATE__31_INDEX2 ON OBJ_UNIQUE_DATE__31 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
