use mtdb
GO

DROP TABLE COUNTER
GO

CREATE TABLE COUNTER
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    CNT_NAME VARCHAR(128) NOT NULL,
    INC_UNIT_KEY VARCHAR(128) NOT NULL,
    CNT_VAL NUMERIC(18,0),
    CONSTRAINT COUNTER_PK PRIMARY KEY (TENANT_ID, CNT_NAME, INC_UNIT_KEY)
)
GO
