use mtdb
GO

DROP TABLE DELETE_LOG
GO

CREATE TABLE DELETE_LOG
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    STATUS CHAR(1),
    CRE_DATE DATETIME2(3),
    UP_DATE DATETIME2(3)
)
GO
