use mtdb
GO

DROP TABLE OBJ_BLOB
GO

CREATE TABLE OBJ_BLOB
(
    TENANT_ID NUMERIC(7,0),
    LOB_ID NUMERIC(16,0),
    LOB_NAME NVARCHAR(256),
    LOB_TYPE VARCHAR(256),
    LOB_STAT CHAR(1),
    LOB_DATA_ID NUMERIC(16,0),
    CRE_DATE DATETIME2(3),
    UP_DATE DATETIME2(3),
    CRE_USER VARCHAR(64),
    UP_USER VARCHAR(64),
    SESS_ID VARCHAR(128),
    OBJ_DEF_ID VARCHAR(128),
    PROP_DEF_ID VARCHAR(128),
    OBJ_ID VARCHAR(64),
    OBJ_VER NUMERIC(10,0)
)
GO

CREATE INDEX OBJ_BLOB_INDEX1 ON OBJ_BLOB (TENANT_ID, LOB_ID)
GO
