use mtdb
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB
GO

CREATE TABLE OBJ_REF_RB
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB_INDEX1 ON OBJ_REF_RB (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__1
GO

CREATE TABLE OBJ_REF_RB__1
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__1_INDEX1 ON OBJ_REF_RB__1 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__2
GO

CREATE TABLE OBJ_REF_RB__2
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__2_INDEX1 ON OBJ_REF_RB__2 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__3
GO

CREATE TABLE OBJ_REF_RB__3
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__3_INDEX1 ON OBJ_REF_RB__3 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__4
GO

CREATE TABLE OBJ_REF_RB__4
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__4_INDEX1 ON OBJ_REF_RB__4 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__5
GO

CREATE TABLE OBJ_REF_RB__5
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__5_INDEX1 ON OBJ_REF_RB__5 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__6
GO

CREATE TABLE OBJ_REF_RB__6
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__6_INDEX1 ON OBJ_REF_RB__6 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__7
GO

CREATE TABLE OBJ_REF_RB__7
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__7_INDEX1 ON OBJ_REF_RB__7 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__8
GO

CREATE TABLE OBJ_REF_RB__8
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__8_INDEX1 ON OBJ_REF_RB__8 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__9
GO

CREATE TABLE OBJ_REF_RB__9
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__9_INDEX1 ON OBJ_REF_RB__9 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__10
GO

CREATE TABLE OBJ_REF_RB__10
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__10_INDEX1 ON OBJ_REF_RB__10 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__11
GO

CREATE TABLE OBJ_REF_RB__11
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__11_INDEX1 ON OBJ_REF_RB__11 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__12
GO

CREATE TABLE OBJ_REF_RB__12
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__12_INDEX1 ON OBJ_REF_RB__12 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__13
GO

CREATE TABLE OBJ_REF_RB__13
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__13_INDEX1 ON OBJ_REF_RB__13 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__14
GO

CREATE TABLE OBJ_REF_RB__14
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__14_INDEX1 ON OBJ_REF_RB__14 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__15
GO

CREATE TABLE OBJ_REF_RB__15
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__15_INDEX1 ON OBJ_REF_RB__15 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__16
GO

CREATE TABLE OBJ_REF_RB__16
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__16_INDEX1 ON OBJ_REF_RB__16 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__17
GO

CREATE TABLE OBJ_REF_RB__17
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__17_INDEX1 ON OBJ_REF_RB__17 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__18
GO

CREATE TABLE OBJ_REF_RB__18
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__18_INDEX1 ON OBJ_REF_RB__18 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__19
GO

CREATE TABLE OBJ_REF_RB__19
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__19_INDEX1 ON OBJ_REF_RB__19 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__20
GO

CREATE TABLE OBJ_REF_RB__20
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__20_INDEX1 ON OBJ_REF_RB__20 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__21
GO

CREATE TABLE OBJ_REF_RB__21
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__21_INDEX1 ON OBJ_REF_RB__21 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__22
GO

CREATE TABLE OBJ_REF_RB__22
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__22_INDEX1 ON OBJ_REF_RB__22 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__23
GO

CREATE TABLE OBJ_REF_RB__23
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__23_INDEX1 ON OBJ_REF_RB__23 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__24
GO

CREATE TABLE OBJ_REF_RB__24
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__24_INDEX1 ON OBJ_REF_RB__24 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__25
GO

CREATE TABLE OBJ_REF_RB__25
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__25_INDEX1 ON OBJ_REF_RB__25 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__26
GO

CREATE TABLE OBJ_REF_RB__26
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__26_INDEX1 ON OBJ_REF_RB__26 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__27
GO

CREATE TABLE OBJ_REF_RB__27
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__27_INDEX1 ON OBJ_REF_RB__27 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__28
GO

CREATE TABLE OBJ_REF_RB__28
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__28_INDEX1 ON OBJ_REF_RB__28 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__29
GO

CREATE TABLE OBJ_REF_RB__29
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__29_INDEX1 ON OBJ_REF_RB__29 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__30
GO

CREATE TABLE OBJ_REF_RB__30
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__30_INDEX1 ON OBJ_REF_RB__30 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__31
GO

CREATE TABLE OBJ_REF_RB__31
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__31_INDEX1 ON OBJ_REF_RB__31 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__32
GO

CREATE TABLE OBJ_REF_RB__32
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__32_INDEX1 ON OBJ_REF_RB__32 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__33
GO

CREATE TABLE OBJ_REF_RB__33
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__33_INDEX1 ON OBJ_REF_RB__33 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__34
GO

CREATE TABLE OBJ_REF_RB__34
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__34_INDEX1 ON OBJ_REF_RB__34 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__35
GO

CREATE TABLE OBJ_REF_RB__35
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__35_INDEX1 ON OBJ_REF_RB__35 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__36
GO

CREATE TABLE OBJ_REF_RB__36
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__36_INDEX1 ON OBJ_REF_RB__36 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__37
GO

CREATE TABLE OBJ_REF_RB__37
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__37_INDEX1 ON OBJ_REF_RB__37 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__38
GO

CREATE TABLE OBJ_REF_RB__38
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__38_INDEX1 ON OBJ_REF_RB__38 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__39
GO

CREATE TABLE OBJ_REF_RB__39
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__39_INDEX1 ON OBJ_REF_RB__39 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__40
GO

CREATE TABLE OBJ_REF_RB__40
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__40_INDEX1 ON OBJ_REF_RB__40 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__41
GO

CREATE TABLE OBJ_REF_RB__41
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__41_INDEX1 ON OBJ_REF_RB__41 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__42
GO

CREATE TABLE OBJ_REF_RB__42
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__42_INDEX1 ON OBJ_REF_RB__42 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__43
GO

CREATE TABLE OBJ_REF_RB__43
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__43_INDEX1 ON OBJ_REF_RB__43 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__44
GO

CREATE TABLE OBJ_REF_RB__44
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__44_INDEX1 ON OBJ_REF_RB__44 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__45
GO

CREATE TABLE OBJ_REF_RB__45
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__45_INDEX1 ON OBJ_REF_RB__45 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__46
GO

CREATE TABLE OBJ_REF_RB__46
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__46_INDEX1 ON OBJ_REF_RB__46 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__47
GO

CREATE TABLE OBJ_REF_RB__47
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__47_INDEX1 ON OBJ_REF_RB__47 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__48
GO

CREATE TABLE OBJ_REF_RB__48
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__48_INDEX1 ON OBJ_REF_RB__48 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__49
GO

CREATE TABLE OBJ_REF_RB__49
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__49_INDEX1 ON OBJ_REF_RB__49 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__50
GO

CREATE TABLE OBJ_REF_RB__50
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__50_INDEX1 ON OBJ_REF_RB__50 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__51
GO

CREATE TABLE OBJ_REF_RB__51
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__51_INDEX1 ON OBJ_REF_RB__51 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__52
GO

CREATE TABLE OBJ_REF_RB__52
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__52_INDEX1 ON OBJ_REF_RB__52 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__53
GO

CREATE TABLE OBJ_REF_RB__53
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__53_INDEX1 ON OBJ_REF_RB__53 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__54
GO

CREATE TABLE OBJ_REF_RB__54
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__54_INDEX1 ON OBJ_REF_RB__54 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__55
GO

CREATE TABLE OBJ_REF_RB__55
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__55_INDEX1 ON OBJ_REF_RB__55 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__56
GO

CREATE TABLE OBJ_REF_RB__56
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__56_INDEX1 ON OBJ_REF_RB__56 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__57
GO

CREATE TABLE OBJ_REF_RB__57
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__57_INDEX1 ON OBJ_REF_RB__57 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__58
GO

CREATE TABLE OBJ_REF_RB__58
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__58_INDEX1 ON OBJ_REF_RB__58 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__59
GO

CREATE TABLE OBJ_REF_RB__59
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__59_INDEX1 ON OBJ_REF_RB__59 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__60
GO

CREATE TABLE OBJ_REF_RB__60
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__60_INDEX1 ON OBJ_REF_RB__60 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__61
GO

CREATE TABLE OBJ_REF_RB__61
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__61_INDEX1 ON OBJ_REF_RB__61 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__62
GO

CREATE TABLE OBJ_REF_RB__62
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__62_INDEX1 ON OBJ_REF_RB__62 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__63
GO

CREATE TABLE OBJ_REF_RB__63
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__63_INDEX1 ON OBJ_REF_RB__63 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__64
GO

CREATE TABLE OBJ_REF_RB__64
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__64_INDEX1 ON OBJ_REF_RB__64 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__65
GO

CREATE TABLE OBJ_REF_RB__65
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__65_INDEX1 ON OBJ_REF_RB__65 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__66
GO

CREATE TABLE OBJ_REF_RB__66
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__66_INDEX1 ON OBJ_REF_RB__66 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__67
GO

CREATE TABLE OBJ_REF_RB__67
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__67_INDEX1 ON OBJ_REF_RB__67 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__68
GO

CREATE TABLE OBJ_REF_RB__68
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__68_INDEX1 ON OBJ_REF_RB__68 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__69
GO

CREATE TABLE OBJ_REF_RB__69
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__69_INDEX1 ON OBJ_REF_RB__69 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__70
GO

CREATE TABLE OBJ_REF_RB__70
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__70_INDEX1 ON OBJ_REF_RB__70 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__71
GO

CREATE TABLE OBJ_REF_RB__71
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__71_INDEX1 ON OBJ_REF_RB__71 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__72
GO

CREATE TABLE OBJ_REF_RB__72
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__72_INDEX1 ON OBJ_REF_RB__72 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__73
GO

CREATE TABLE OBJ_REF_RB__73
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__73_INDEX1 ON OBJ_REF_RB__73 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__74
GO

CREATE TABLE OBJ_REF_RB__74
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__74_INDEX1 ON OBJ_REF_RB__74 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__75
GO

CREATE TABLE OBJ_REF_RB__75
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__75_INDEX1 ON OBJ_REF_RB__75 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__76
GO

CREATE TABLE OBJ_REF_RB__76
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__76_INDEX1 ON OBJ_REF_RB__76 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__77
GO

CREATE TABLE OBJ_REF_RB__77
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__77_INDEX1 ON OBJ_REF_RB__77 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__78
GO

CREATE TABLE OBJ_REF_RB__78
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__78_INDEX1 ON OBJ_REF_RB__78 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__79
GO

CREATE TABLE OBJ_REF_RB__79
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__79_INDEX1 ON OBJ_REF_RB__79 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__80
GO

CREATE TABLE OBJ_REF_RB__80
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__80_INDEX1 ON OBJ_REF_RB__80 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__81
GO

CREATE TABLE OBJ_REF_RB__81
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__81_INDEX1 ON OBJ_REF_RB__81 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__82
GO

CREATE TABLE OBJ_REF_RB__82
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__82_INDEX1 ON OBJ_REF_RB__82 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__83
GO

CREATE TABLE OBJ_REF_RB__83
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__83_INDEX1 ON OBJ_REF_RB__83 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__84
GO

CREATE TABLE OBJ_REF_RB__84
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__84_INDEX1 ON OBJ_REF_RB__84 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__85
GO

CREATE TABLE OBJ_REF_RB__85
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__85_INDEX1 ON OBJ_REF_RB__85 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__86
GO

CREATE TABLE OBJ_REF_RB__86
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__86_INDEX1 ON OBJ_REF_RB__86 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__87
GO

CREATE TABLE OBJ_REF_RB__87
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__87_INDEX1 ON OBJ_REF_RB__87 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__88
GO

CREATE TABLE OBJ_REF_RB__88
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__88_INDEX1 ON OBJ_REF_RB__88 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__89
GO

CREATE TABLE OBJ_REF_RB__89
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__89_INDEX1 ON OBJ_REF_RB__89 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__90
GO

CREATE TABLE OBJ_REF_RB__90
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__90_INDEX1 ON OBJ_REF_RB__90 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__91
GO

CREATE TABLE OBJ_REF_RB__91
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__91_INDEX1 ON OBJ_REF_RB__91 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__92
GO

CREATE TABLE OBJ_REF_RB__92
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__92_INDEX1 ON OBJ_REF_RB__92 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__93
GO

CREATE TABLE OBJ_REF_RB__93
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__93_INDEX1 ON OBJ_REF_RB__93 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__94
GO

CREATE TABLE OBJ_REF_RB__94
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__94_INDEX1 ON OBJ_REF_RB__94 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__95
GO

CREATE TABLE OBJ_REF_RB__95
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__95_INDEX1 ON OBJ_REF_RB__95 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__96
GO

CREATE TABLE OBJ_REF_RB__96
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__96_INDEX1 ON OBJ_REF_RB__96 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__97
GO

CREATE TABLE OBJ_REF_RB__97
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__97_INDEX1 ON OBJ_REF_RB__97 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__98
GO

CREATE TABLE OBJ_REF_RB__98
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__98_INDEX1 ON OBJ_REF_RB__98 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__99
GO

CREATE TABLE OBJ_REF_RB__99
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__99_INDEX1 ON OBJ_REF_RB__99 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__100
GO

CREATE TABLE OBJ_REF_RB__100
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__100_INDEX1 ON OBJ_REF_RB__100 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__101
GO

CREATE TABLE OBJ_REF_RB__101
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__101_INDEX1 ON OBJ_REF_RB__101 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__102
GO

CREATE TABLE OBJ_REF_RB__102
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__102_INDEX1 ON OBJ_REF_RB__102 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__103
GO

CREATE TABLE OBJ_REF_RB__103
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__103_INDEX1 ON OBJ_REF_RB__103 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__104
GO

CREATE TABLE OBJ_REF_RB__104
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__104_INDEX1 ON OBJ_REF_RB__104 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__105
GO

CREATE TABLE OBJ_REF_RB__105
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__105_INDEX1 ON OBJ_REF_RB__105 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__106
GO

CREATE TABLE OBJ_REF_RB__106
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__106_INDEX1 ON OBJ_REF_RB__106 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__107
GO

CREATE TABLE OBJ_REF_RB__107
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__107_INDEX1 ON OBJ_REF_RB__107 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__108
GO

CREATE TABLE OBJ_REF_RB__108
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__108_INDEX1 ON OBJ_REF_RB__108 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__109
GO

CREATE TABLE OBJ_REF_RB__109
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__109_INDEX1 ON OBJ_REF_RB__109 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__110
GO

CREATE TABLE OBJ_REF_RB__110
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__110_INDEX1 ON OBJ_REF_RB__110 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__111
GO

CREATE TABLE OBJ_REF_RB__111
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__111_INDEX1 ON OBJ_REF_RB__111 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__112
GO

CREATE TABLE OBJ_REF_RB__112
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__112_INDEX1 ON OBJ_REF_RB__112 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__113
GO

CREATE TABLE OBJ_REF_RB__113
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__113_INDEX1 ON OBJ_REF_RB__113 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__114
GO

CREATE TABLE OBJ_REF_RB__114
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__114_INDEX1 ON OBJ_REF_RB__114 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__115
GO

CREATE TABLE OBJ_REF_RB__115
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__115_INDEX1 ON OBJ_REF_RB__115 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__116
GO

CREATE TABLE OBJ_REF_RB__116
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__116_INDEX1 ON OBJ_REF_RB__116 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__117
GO

CREATE TABLE OBJ_REF_RB__117
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__117_INDEX1 ON OBJ_REF_RB__117 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__118
GO

CREATE TABLE OBJ_REF_RB__118
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__118_INDEX1 ON OBJ_REF_RB__118 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__119
GO

CREATE TABLE OBJ_REF_RB__119
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__119_INDEX1 ON OBJ_REF_RB__119 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__120
GO

CREATE TABLE OBJ_REF_RB__120
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__120_INDEX1 ON OBJ_REF_RB__120 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__121
GO

CREATE TABLE OBJ_REF_RB__121
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__121_INDEX1 ON OBJ_REF_RB__121 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__122
GO

CREATE TABLE OBJ_REF_RB__122
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__122_INDEX1 ON OBJ_REF_RB__122 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__123
GO

CREATE TABLE OBJ_REF_RB__123
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__123_INDEX1 ON OBJ_REF_RB__123 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__124
GO

CREATE TABLE OBJ_REF_RB__124
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__124_INDEX1 ON OBJ_REF_RB__124 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__125
GO

CREATE TABLE OBJ_REF_RB__125
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__125_INDEX1 ON OBJ_REF_RB__125 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__126
GO

CREATE TABLE OBJ_REF_RB__126
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__126_INDEX1 ON OBJ_REF_RB__126 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__127
GO

CREATE TABLE OBJ_REF_RB__127
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__127_INDEX1 ON OBJ_REF_RB__127 (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__MTP
GO

CREATE TABLE OBJ_REF_RB__MTP
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__MTP_INDEX1 ON OBJ_REF_RB__MTP (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

/* drop/create OBJ_REF_RB */
DROP TABLE OBJ_REF_RB__USER
GO

CREATE TABLE OBJ_REF_RB__USER
(
    RB_ID NUMERIC(16,0),
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    REF_DEF_ID VARCHAR(128) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    TARGET_OBJ_DEF_ID VARCHAR(128) NOT NULL,
    TARGET_OBJ_ID VARCHAR(64) NOT NULL,
    TARGET_OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL
)
GO

CREATE INDEX OBJ_REF_RB__USER_INDEX1 ON OBJ_REF_RB__USER (TENANT_ID, OBJ_DEF_ID, RB_ID)
GO

