use mtdb
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM
GO

CREATE TABLE OBJ_INDEX_NUM
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM_INDEX1 ON OBJ_INDEX_NUM (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM_INDEX2 ON OBJ_INDEX_NUM (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__1
GO

CREATE TABLE OBJ_INDEX_NUM__1
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__1_INDEX1 ON OBJ_INDEX_NUM__1 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__1_INDEX2 ON OBJ_INDEX_NUM__1 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__2
GO

CREATE TABLE OBJ_INDEX_NUM__2
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__2_INDEX1 ON OBJ_INDEX_NUM__2 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__2_INDEX2 ON OBJ_INDEX_NUM__2 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__3
GO

CREATE TABLE OBJ_INDEX_NUM__3
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__3_INDEX1 ON OBJ_INDEX_NUM__3 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__3_INDEX2 ON OBJ_INDEX_NUM__3 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__4
GO

CREATE TABLE OBJ_INDEX_NUM__4
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__4_INDEX1 ON OBJ_INDEX_NUM__4 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__4_INDEX2 ON OBJ_INDEX_NUM__4 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__5
GO

CREATE TABLE OBJ_INDEX_NUM__5
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__5_INDEX1 ON OBJ_INDEX_NUM__5 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__5_INDEX2 ON OBJ_INDEX_NUM__5 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__6
GO

CREATE TABLE OBJ_INDEX_NUM__6
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__6_INDEX1 ON OBJ_INDEX_NUM__6 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__6_INDEX2 ON OBJ_INDEX_NUM__6 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__7
GO

CREATE TABLE OBJ_INDEX_NUM__7
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__7_INDEX1 ON OBJ_INDEX_NUM__7 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__7_INDEX2 ON OBJ_INDEX_NUM__7 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__8
GO

CREATE TABLE OBJ_INDEX_NUM__8
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__8_INDEX1 ON OBJ_INDEX_NUM__8 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__8_INDEX2 ON OBJ_INDEX_NUM__8 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__9
GO

CREATE TABLE OBJ_INDEX_NUM__9
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__9_INDEX1 ON OBJ_INDEX_NUM__9 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__9_INDEX2 ON OBJ_INDEX_NUM__9 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__10
GO

CREATE TABLE OBJ_INDEX_NUM__10
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__10_INDEX1 ON OBJ_INDEX_NUM__10 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__10_INDEX2 ON OBJ_INDEX_NUM__10 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__11
GO

CREATE TABLE OBJ_INDEX_NUM__11
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__11_INDEX1 ON OBJ_INDEX_NUM__11 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__11_INDEX2 ON OBJ_INDEX_NUM__11 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__12
GO

CREATE TABLE OBJ_INDEX_NUM__12
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__12_INDEX1 ON OBJ_INDEX_NUM__12 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__12_INDEX2 ON OBJ_INDEX_NUM__12 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__13
GO

CREATE TABLE OBJ_INDEX_NUM__13
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__13_INDEX1 ON OBJ_INDEX_NUM__13 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__13_INDEX2 ON OBJ_INDEX_NUM__13 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__14
GO

CREATE TABLE OBJ_INDEX_NUM__14
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__14_INDEX1 ON OBJ_INDEX_NUM__14 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__14_INDEX2 ON OBJ_INDEX_NUM__14 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__15
GO

CREATE TABLE OBJ_INDEX_NUM__15
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__15_INDEX1 ON OBJ_INDEX_NUM__15 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__15_INDEX2 ON OBJ_INDEX_NUM__15 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__16
GO

CREATE TABLE OBJ_INDEX_NUM__16
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__16_INDEX1 ON OBJ_INDEX_NUM__16 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__16_INDEX2 ON OBJ_INDEX_NUM__16 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__17
GO

CREATE TABLE OBJ_INDEX_NUM__17
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__17_INDEX1 ON OBJ_INDEX_NUM__17 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__17_INDEX2 ON OBJ_INDEX_NUM__17 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__18
GO

CREATE TABLE OBJ_INDEX_NUM__18
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__18_INDEX1 ON OBJ_INDEX_NUM__18 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__18_INDEX2 ON OBJ_INDEX_NUM__18 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__19
GO

CREATE TABLE OBJ_INDEX_NUM__19
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__19_INDEX1 ON OBJ_INDEX_NUM__19 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__19_INDEX2 ON OBJ_INDEX_NUM__19 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__20
GO

CREATE TABLE OBJ_INDEX_NUM__20
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__20_INDEX1 ON OBJ_INDEX_NUM__20 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__20_INDEX2 ON OBJ_INDEX_NUM__20 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__21
GO

CREATE TABLE OBJ_INDEX_NUM__21
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__21_INDEX1 ON OBJ_INDEX_NUM__21 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__21_INDEX2 ON OBJ_INDEX_NUM__21 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__22
GO

CREATE TABLE OBJ_INDEX_NUM__22
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__22_INDEX1 ON OBJ_INDEX_NUM__22 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__22_INDEX2 ON OBJ_INDEX_NUM__22 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__23
GO

CREATE TABLE OBJ_INDEX_NUM__23
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__23_INDEX1 ON OBJ_INDEX_NUM__23 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__23_INDEX2 ON OBJ_INDEX_NUM__23 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__24
GO

CREATE TABLE OBJ_INDEX_NUM__24
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__24_INDEX1 ON OBJ_INDEX_NUM__24 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__24_INDEX2 ON OBJ_INDEX_NUM__24 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__25
GO

CREATE TABLE OBJ_INDEX_NUM__25
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__25_INDEX1 ON OBJ_INDEX_NUM__25 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__25_INDEX2 ON OBJ_INDEX_NUM__25 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__26
GO

CREATE TABLE OBJ_INDEX_NUM__26
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__26_INDEX1 ON OBJ_INDEX_NUM__26 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__26_INDEX2 ON OBJ_INDEX_NUM__26 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__27
GO

CREATE TABLE OBJ_INDEX_NUM__27
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__27_INDEX1 ON OBJ_INDEX_NUM__27 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__27_INDEX2 ON OBJ_INDEX_NUM__27 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__28
GO

CREATE TABLE OBJ_INDEX_NUM__28
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__28_INDEX1 ON OBJ_INDEX_NUM__28 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__28_INDEX2 ON OBJ_INDEX_NUM__28 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__29
GO

CREATE TABLE OBJ_INDEX_NUM__29
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__29_INDEX1 ON OBJ_INDEX_NUM__29 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__29_INDEX2 ON OBJ_INDEX_NUM__29 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__30
GO

CREATE TABLE OBJ_INDEX_NUM__30
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__30_INDEX1 ON OBJ_INDEX_NUM__30 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__30_INDEX2 ON OBJ_INDEX_NUM__30 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__31
GO

CREATE TABLE OBJ_INDEX_NUM__31
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__31_INDEX1 ON OBJ_INDEX_NUM__31 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__31_INDEX2 ON OBJ_INDEX_NUM__31 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__32
GO

CREATE TABLE OBJ_INDEX_NUM__32
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__32_INDEX1 ON OBJ_INDEX_NUM__32 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__32_INDEX2 ON OBJ_INDEX_NUM__32 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__33
GO

CREATE TABLE OBJ_INDEX_NUM__33
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__33_INDEX1 ON OBJ_INDEX_NUM__33 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__33_INDEX2 ON OBJ_INDEX_NUM__33 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__34
GO

CREATE TABLE OBJ_INDEX_NUM__34
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__34_INDEX1 ON OBJ_INDEX_NUM__34 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__34_INDEX2 ON OBJ_INDEX_NUM__34 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__35
GO

CREATE TABLE OBJ_INDEX_NUM__35
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__35_INDEX1 ON OBJ_INDEX_NUM__35 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__35_INDEX2 ON OBJ_INDEX_NUM__35 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__36
GO

CREATE TABLE OBJ_INDEX_NUM__36
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__36_INDEX1 ON OBJ_INDEX_NUM__36 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__36_INDEX2 ON OBJ_INDEX_NUM__36 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__37
GO

CREATE TABLE OBJ_INDEX_NUM__37
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__37_INDEX1 ON OBJ_INDEX_NUM__37 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__37_INDEX2 ON OBJ_INDEX_NUM__37 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__38
GO

CREATE TABLE OBJ_INDEX_NUM__38
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__38_INDEX1 ON OBJ_INDEX_NUM__38 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__38_INDEX2 ON OBJ_INDEX_NUM__38 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__39
GO

CREATE TABLE OBJ_INDEX_NUM__39
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__39_INDEX1 ON OBJ_INDEX_NUM__39 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__39_INDEX2 ON OBJ_INDEX_NUM__39 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__40
GO

CREATE TABLE OBJ_INDEX_NUM__40
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__40_INDEX1 ON OBJ_INDEX_NUM__40 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__40_INDEX2 ON OBJ_INDEX_NUM__40 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__41
GO

CREATE TABLE OBJ_INDEX_NUM__41
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__41_INDEX1 ON OBJ_INDEX_NUM__41 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__41_INDEX2 ON OBJ_INDEX_NUM__41 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__42
GO

CREATE TABLE OBJ_INDEX_NUM__42
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__42_INDEX1 ON OBJ_INDEX_NUM__42 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__42_INDEX2 ON OBJ_INDEX_NUM__42 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__43
GO

CREATE TABLE OBJ_INDEX_NUM__43
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__43_INDEX1 ON OBJ_INDEX_NUM__43 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__43_INDEX2 ON OBJ_INDEX_NUM__43 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__44
GO

CREATE TABLE OBJ_INDEX_NUM__44
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__44_INDEX1 ON OBJ_INDEX_NUM__44 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__44_INDEX2 ON OBJ_INDEX_NUM__44 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__45
GO

CREATE TABLE OBJ_INDEX_NUM__45
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__45_INDEX1 ON OBJ_INDEX_NUM__45 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__45_INDEX2 ON OBJ_INDEX_NUM__45 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__46
GO

CREATE TABLE OBJ_INDEX_NUM__46
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__46_INDEX1 ON OBJ_INDEX_NUM__46 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__46_INDEX2 ON OBJ_INDEX_NUM__46 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__47
GO

CREATE TABLE OBJ_INDEX_NUM__47
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__47_INDEX1 ON OBJ_INDEX_NUM__47 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__47_INDEX2 ON OBJ_INDEX_NUM__47 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__48
GO

CREATE TABLE OBJ_INDEX_NUM__48
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__48_INDEX1 ON OBJ_INDEX_NUM__48 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__48_INDEX2 ON OBJ_INDEX_NUM__48 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__49
GO

CREATE TABLE OBJ_INDEX_NUM__49
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__49_INDEX1 ON OBJ_INDEX_NUM__49 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__49_INDEX2 ON OBJ_INDEX_NUM__49 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__50
GO

CREATE TABLE OBJ_INDEX_NUM__50
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__50_INDEX1 ON OBJ_INDEX_NUM__50 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__50_INDEX2 ON OBJ_INDEX_NUM__50 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__51
GO

CREATE TABLE OBJ_INDEX_NUM__51
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__51_INDEX1 ON OBJ_INDEX_NUM__51 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__51_INDEX2 ON OBJ_INDEX_NUM__51 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__52
GO

CREATE TABLE OBJ_INDEX_NUM__52
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__52_INDEX1 ON OBJ_INDEX_NUM__52 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__52_INDEX2 ON OBJ_INDEX_NUM__52 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__53
GO

CREATE TABLE OBJ_INDEX_NUM__53
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__53_INDEX1 ON OBJ_INDEX_NUM__53 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__53_INDEX2 ON OBJ_INDEX_NUM__53 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__54
GO

CREATE TABLE OBJ_INDEX_NUM__54
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__54_INDEX1 ON OBJ_INDEX_NUM__54 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__54_INDEX2 ON OBJ_INDEX_NUM__54 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__55
GO

CREATE TABLE OBJ_INDEX_NUM__55
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__55_INDEX1 ON OBJ_INDEX_NUM__55 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__55_INDEX2 ON OBJ_INDEX_NUM__55 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__56
GO

CREATE TABLE OBJ_INDEX_NUM__56
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__56_INDEX1 ON OBJ_INDEX_NUM__56 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__56_INDEX2 ON OBJ_INDEX_NUM__56 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__57
GO

CREATE TABLE OBJ_INDEX_NUM__57
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__57_INDEX1 ON OBJ_INDEX_NUM__57 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__57_INDEX2 ON OBJ_INDEX_NUM__57 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__58
GO

CREATE TABLE OBJ_INDEX_NUM__58
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__58_INDEX1 ON OBJ_INDEX_NUM__58 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__58_INDEX2 ON OBJ_INDEX_NUM__58 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__59
GO

CREATE TABLE OBJ_INDEX_NUM__59
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__59_INDEX1 ON OBJ_INDEX_NUM__59 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__59_INDEX2 ON OBJ_INDEX_NUM__59 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__60
GO

CREATE TABLE OBJ_INDEX_NUM__60
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__60_INDEX1 ON OBJ_INDEX_NUM__60 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__60_INDEX2 ON OBJ_INDEX_NUM__60 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__61
GO

CREATE TABLE OBJ_INDEX_NUM__61
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__61_INDEX1 ON OBJ_INDEX_NUM__61 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__61_INDEX2 ON OBJ_INDEX_NUM__61 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__62
GO

CREATE TABLE OBJ_INDEX_NUM__62
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__62_INDEX1 ON OBJ_INDEX_NUM__62 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__62_INDEX2 ON OBJ_INDEX_NUM__62 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__63
GO

CREATE TABLE OBJ_INDEX_NUM__63
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__63_INDEX1 ON OBJ_INDEX_NUM__63 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__63_INDEX2 ON OBJ_INDEX_NUM__63 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__64
GO

CREATE TABLE OBJ_INDEX_NUM__64
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__64_INDEX1 ON OBJ_INDEX_NUM__64 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__64_INDEX2 ON OBJ_INDEX_NUM__64 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__65
GO

CREATE TABLE OBJ_INDEX_NUM__65
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__65_INDEX1 ON OBJ_INDEX_NUM__65 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__65_INDEX2 ON OBJ_INDEX_NUM__65 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__66
GO

CREATE TABLE OBJ_INDEX_NUM__66
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__66_INDEX1 ON OBJ_INDEX_NUM__66 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__66_INDEX2 ON OBJ_INDEX_NUM__66 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__67
GO

CREATE TABLE OBJ_INDEX_NUM__67
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__67_INDEX1 ON OBJ_INDEX_NUM__67 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__67_INDEX2 ON OBJ_INDEX_NUM__67 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__68
GO

CREATE TABLE OBJ_INDEX_NUM__68
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__68_INDEX1 ON OBJ_INDEX_NUM__68 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__68_INDEX2 ON OBJ_INDEX_NUM__68 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__69
GO

CREATE TABLE OBJ_INDEX_NUM__69
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__69_INDEX1 ON OBJ_INDEX_NUM__69 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__69_INDEX2 ON OBJ_INDEX_NUM__69 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__70
GO

CREATE TABLE OBJ_INDEX_NUM__70
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__70_INDEX1 ON OBJ_INDEX_NUM__70 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__70_INDEX2 ON OBJ_INDEX_NUM__70 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__71
GO

CREATE TABLE OBJ_INDEX_NUM__71
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__71_INDEX1 ON OBJ_INDEX_NUM__71 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__71_INDEX2 ON OBJ_INDEX_NUM__71 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__72
GO

CREATE TABLE OBJ_INDEX_NUM__72
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__72_INDEX1 ON OBJ_INDEX_NUM__72 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__72_INDEX2 ON OBJ_INDEX_NUM__72 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__73
GO

CREATE TABLE OBJ_INDEX_NUM__73
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__73_INDEX1 ON OBJ_INDEX_NUM__73 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__73_INDEX2 ON OBJ_INDEX_NUM__73 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__74
GO

CREATE TABLE OBJ_INDEX_NUM__74
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__74_INDEX1 ON OBJ_INDEX_NUM__74 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__74_INDEX2 ON OBJ_INDEX_NUM__74 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__75
GO

CREATE TABLE OBJ_INDEX_NUM__75
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__75_INDEX1 ON OBJ_INDEX_NUM__75 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__75_INDEX2 ON OBJ_INDEX_NUM__75 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__76
GO

CREATE TABLE OBJ_INDEX_NUM__76
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__76_INDEX1 ON OBJ_INDEX_NUM__76 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__76_INDEX2 ON OBJ_INDEX_NUM__76 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__77
GO

CREATE TABLE OBJ_INDEX_NUM__77
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__77_INDEX1 ON OBJ_INDEX_NUM__77 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__77_INDEX2 ON OBJ_INDEX_NUM__77 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__78
GO

CREATE TABLE OBJ_INDEX_NUM__78
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__78_INDEX1 ON OBJ_INDEX_NUM__78 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__78_INDEX2 ON OBJ_INDEX_NUM__78 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__79
GO

CREATE TABLE OBJ_INDEX_NUM__79
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__79_INDEX1 ON OBJ_INDEX_NUM__79 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__79_INDEX2 ON OBJ_INDEX_NUM__79 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__80
GO

CREATE TABLE OBJ_INDEX_NUM__80
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__80_INDEX1 ON OBJ_INDEX_NUM__80 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__80_INDEX2 ON OBJ_INDEX_NUM__80 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__81
GO

CREATE TABLE OBJ_INDEX_NUM__81
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__81_INDEX1 ON OBJ_INDEX_NUM__81 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__81_INDEX2 ON OBJ_INDEX_NUM__81 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__82
GO

CREATE TABLE OBJ_INDEX_NUM__82
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__82_INDEX1 ON OBJ_INDEX_NUM__82 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__82_INDEX2 ON OBJ_INDEX_NUM__82 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__83
GO

CREATE TABLE OBJ_INDEX_NUM__83
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__83_INDEX1 ON OBJ_INDEX_NUM__83 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__83_INDEX2 ON OBJ_INDEX_NUM__83 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__84
GO

CREATE TABLE OBJ_INDEX_NUM__84
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__84_INDEX1 ON OBJ_INDEX_NUM__84 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__84_INDEX2 ON OBJ_INDEX_NUM__84 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__85
GO

CREATE TABLE OBJ_INDEX_NUM__85
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__85_INDEX1 ON OBJ_INDEX_NUM__85 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__85_INDEX2 ON OBJ_INDEX_NUM__85 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__86
GO

CREATE TABLE OBJ_INDEX_NUM__86
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__86_INDEX1 ON OBJ_INDEX_NUM__86 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__86_INDEX2 ON OBJ_INDEX_NUM__86 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__87
GO

CREATE TABLE OBJ_INDEX_NUM__87
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__87_INDEX1 ON OBJ_INDEX_NUM__87 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__87_INDEX2 ON OBJ_INDEX_NUM__87 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__88
GO

CREATE TABLE OBJ_INDEX_NUM__88
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__88_INDEX1 ON OBJ_INDEX_NUM__88 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__88_INDEX2 ON OBJ_INDEX_NUM__88 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__89
GO

CREATE TABLE OBJ_INDEX_NUM__89
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__89_INDEX1 ON OBJ_INDEX_NUM__89 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__89_INDEX2 ON OBJ_INDEX_NUM__89 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__90
GO

CREATE TABLE OBJ_INDEX_NUM__90
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__90_INDEX1 ON OBJ_INDEX_NUM__90 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__90_INDEX2 ON OBJ_INDEX_NUM__90 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__91
GO

CREATE TABLE OBJ_INDEX_NUM__91
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__91_INDEX1 ON OBJ_INDEX_NUM__91 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__91_INDEX2 ON OBJ_INDEX_NUM__91 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__92
GO

CREATE TABLE OBJ_INDEX_NUM__92
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__92_INDEX1 ON OBJ_INDEX_NUM__92 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__92_INDEX2 ON OBJ_INDEX_NUM__92 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__93
GO

CREATE TABLE OBJ_INDEX_NUM__93
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__93_INDEX1 ON OBJ_INDEX_NUM__93 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__93_INDEX2 ON OBJ_INDEX_NUM__93 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__94
GO

CREATE TABLE OBJ_INDEX_NUM__94
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__94_INDEX1 ON OBJ_INDEX_NUM__94 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__94_INDEX2 ON OBJ_INDEX_NUM__94 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__95
GO

CREATE TABLE OBJ_INDEX_NUM__95
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__95_INDEX1 ON OBJ_INDEX_NUM__95 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__95_INDEX2 ON OBJ_INDEX_NUM__95 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__96
GO

CREATE TABLE OBJ_INDEX_NUM__96
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__96_INDEX1 ON OBJ_INDEX_NUM__96 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__96_INDEX2 ON OBJ_INDEX_NUM__96 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__97
GO

CREATE TABLE OBJ_INDEX_NUM__97
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__97_INDEX1 ON OBJ_INDEX_NUM__97 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__97_INDEX2 ON OBJ_INDEX_NUM__97 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__98
GO

CREATE TABLE OBJ_INDEX_NUM__98
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__98_INDEX1 ON OBJ_INDEX_NUM__98 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__98_INDEX2 ON OBJ_INDEX_NUM__98 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__99
GO

CREATE TABLE OBJ_INDEX_NUM__99
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__99_INDEX1 ON OBJ_INDEX_NUM__99 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__99_INDEX2 ON OBJ_INDEX_NUM__99 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__100
GO

CREATE TABLE OBJ_INDEX_NUM__100
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__100_INDEX1 ON OBJ_INDEX_NUM__100 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__100_INDEX2 ON OBJ_INDEX_NUM__100 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__101
GO

CREATE TABLE OBJ_INDEX_NUM__101
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__101_INDEX1 ON OBJ_INDEX_NUM__101 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__101_INDEX2 ON OBJ_INDEX_NUM__101 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__102
GO

CREATE TABLE OBJ_INDEX_NUM__102
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__102_INDEX1 ON OBJ_INDEX_NUM__102 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__102_INDEX2 ON OBJ_INDEX_NUM__102 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__103
GO

CREATE TABLE OBJ_INDEX_NUM__103
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__103_INDEX1 ON OBJ_INDEX_NUM__103 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__103_INDEX2 ON OBJ_INDEX_NUM__103 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__104
GO

CREATE TABLE OBJ_INDEX_NUM__104
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__104_INDEX1 ON OBJ_INDEX_NUM__104 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__104_INDEX2 ON OBJ_INDEX_NUM__104 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__105
GO

CREATE TABLE OBJ_INDEX_NUM__105
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__105_INDEX1 ON OBJ_INDEX_NUM__105 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__105_INDEX2 ON OBJ_INDEX_NUM__105 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__106
GO

CREATE TABLE OBJ_INDEX_NUM__106
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__106_INDEX1 ON OBJ_INDEX_NUM__106 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__106_INDEX2 ON OBJ_INDEX_NUM__106 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__107
GO

CREATE TABLE OBJ_INDEX_NUM__107
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__107_INDEX1 ON OBJ_INDEX_NUM__107 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__107_INDEX2 ON OBJ_INDEX_NUM__107 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__108
GO

CREATE TABLE OBJ_INDEX_NUM__108
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__108_INDEX1 ON OBJ_INDEX_NUM__108 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__108_INDEX2 ON OBJ_INDEX_NUM__108 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__109
GO

CREATE TABLE OBJ_INDEX_NUM__109
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__109_INDEX1 ON OBJ_INDEX_NUM__109 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__109_INDEX2 ON OBJ_INDEX_NUM__109 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__110
GO

CREATE TABLE OBJ_INDEX_NUM__110
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__110_INDEX1 ON OBJ_INDEX_NUM__110 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__110_INDEX2 ON OBJ_INDEX_NUM__110 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__111
GO

CREATE TABLE OBJ_INDEX_NUM__111
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__111_INDEX1 ON OBJ_INDEX_NUM__111 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__111_INDEX2 ON OBJ_INDEX_NUM__111 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__112
GO

CREATE TABLE OBJ_INDEX_NUM__112
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__112_INDEX1 ON OBJ_INDEX_NUM__112 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__112_INDEX2 ON OBJ_INDEX_NUM__112 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__113
GO

CREATE TABLE OBJ_INDEX_NUM__113
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__113_INDEX1 ON OBJ_INDEX_NUM__113 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__113_INDEX2 ON OBJ_INDEX_NUM__113 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__114
GO

CREATE TABLE OBJ_INDEX_NUM__114
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__114_INDEX1 ON OBJ_INDEX_NUM__114 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__114_INDEX2 ON OBJ_INDEX_NUM__114 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__115
GO

CREATE TABLE OBJ_INDEX_NUM__115
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__115_INDEX1 ON OBJ_INDEX_NUM__115 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__115_INDEX2 ON OBJ_INDEX_NUM__115 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__116
GO

CREATE TABLE OBJ_INDEX_NUM__116
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__116_INDEX1 ON OBJ_INDEX_NUM__116 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__116_INDEX2 ON OBJ_INDEX_NUM__116 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__117
GO

CREATE TABLE OBJ_INDEX_NUM__117
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__117_INDEX1 ON OBJ_INDEX_NUM__117 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__117_INDEX2 ON OBJ_INDEX_NUM__117 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__118
GO

CREATE TABLE OBJ_INDEX_NUM__118
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__118_INDEX1 ON OBJ_INDEX_NUM__118 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__118_INDEX2 ON OBJ_INDEX_NUM__118 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__119
GO

CREATE TABLE OBJ_INDEX_NUM__119
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__119_INDEX1 ON OBJ_INDEX_NUM__119 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__119_INDEX2 ON OBJ_INDEX_NUM__119 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__120
GO

CREATE TABLE OBJ_INDEX_NUM__120
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__120_INDEX1 ON OBJ_INDEX_NUM__120 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__120_INDEX2 ON OBJ_INDEX_NUM__120 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__121
GO

CREATE TABLE OBJ_INDEX_NUM__121
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__121_INDEX1 ON OBJ_INDEX_NUM__121 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__121_INDEX2 ON OBJ_INDEX_NUM__121 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__122
GO

CREATE TABLE OBJ_INDEX_NUM__122
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__122_INDEX1 ON OBJ_INDEX_NUM__122 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__122_INDEX2 ON OBJ_INDEX_NUM__122 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__123
GO

CREATE TABLE OBJ_INDEX_NUM__123
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__123_INDEX1 ON OBJ_INDEX_NUM__123 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__123_INDEX2 ON OBJ_INDEX_NUM__123 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__124
GO

CREATE TABLE OBJ_INDEX_NUM__124
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__124_INDEX1 ON OBJ_INDEX_NUM__124 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__124_INDEX2 ON OBJ_INDEX_NUM__124 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__125
GO

CREATE TABLE OBJ_INDEX_NUM__125
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__125_INDEX1 ON OBJ_INDEX_NUM__125 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__125_INDEX2 ON OBJ_INDEX_NUM__125 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__126
GO

CREATE TABLE OBJ_INDEX_NUM__126
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__126_INDEX1 ON OBJ_INDEX_NUM__126 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__126_INDEX2 ON OBJ_INDEX_NUM__126 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_NUM */
DROP TABLE OBJ_INDEX_NUM__127
GO

CREATE TABLE OBJ_INDEX_NUM__127
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL NUMERIC
)
GO

CREATE INDEX OBJ_INDEX_NUM__127_INDEX1 ON OBJ_INDEX_NUM__127 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_NUM__127_INDEX2 ON OBJ_INDEX_NUM__127 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
