use mtdb
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS
GO

CREATE TABLE OBJ_UNIQUE_TS
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS_INDEX1 ON OBJ_UNIQUE_TS (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS_INDEX2 ON OBJ_UNIQUE_TS (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__1
GO

CREATE TABLE OBJ_UNIQUE_TS__1
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__1_INDEX1 ON OBJ_UNIQUE_TS__1 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__1_INDEX2 ON OBJ_UNIQUE_TS__1 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__2
GO

CREATE TABLE OBJ_UNIQUE_TS__2
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__2_INDEX1 ON OBJ_UNIQUE_TS__2 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__2_INDEX2 ON OBJ_UNIQUE_TS__2 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__3
GO

CREATE TABLE OBJ_UNIQUE_TS__3
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__3_INDEX1 ON OBJ_UNIQUE_TS__3 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__3_INDEX2 ON OBJ_UNIQUE_TS__3 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__4
GO

CREATE TABLE OBJ_UNIQUE_TS__4
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__4_INDEX1 ON OBJ_UNIQUE_TS__4 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__4_INDEX2 ON OBJ_UNIQUE_TS__4 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__5
GO

CREATE TABLE OBJ_UNIQUE_TS__5
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__5_INDEX1 ON OBJ_UNIQUE_TS__5 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__5_INDEX2 ON OBJ_UNIQUE_TS__5 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__6
GO

CREATE TABLE OBJ_UNIQUE_TS__6
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__6_INDEX1 ON OBJ_UNIQUE_TS__6 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__6_INDEX2 ON OBJ_UNIQUE_TS__6 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__7
GO

CREATE TABLE OBJ_UNIQUE_TS__7
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__7_INDEX1 ON OBJ_UNIQUE_TS__7 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__7_INDEX2 ON OBJ_UNIQUE_TS__7 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__8
GO

CREATE TABLE OBJ_UNIQUE_TS__8
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__8_INDEX1 ON OBJ_UNIQUE_TS__8 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__8_INDEX2 ON OBJ_UNIQUE_TS__8 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__9
GO

CREATE TABLE OBJ_UNIQUE_TS__9
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__9_INDEX1 ON OBJ_UNIQUE_TS__9 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__9_INDEX2 ON OBJ_UNIQUE_TS__9 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__10
GO

CREATE TABLE OBJ_UNIQUE_TS__10
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__10_INDEX1 ON OBJ_UNIQUE_TS__10 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__10_INDEX2 ON OBJ_UNIQUE_TS__10 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__11
GO

CREATE TABLE OBJ_UNIQUE_TS__11
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__11_INDEX1 ON OBJ_UNIQUE_TS__11 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__11_INDEX2 ON OBJ_UNIQUE_TS__11 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__12
GO

CREATE TABLE OBJ_UNIQUE_TS__12
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__12_INDEX1 ON OBJ_UNIQUE_TS__12 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__12_INDEX2 ON OBJ_UNIQUE_TS__12 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__13
GO

CREATE TABLE OBJ_UNIQUE_TS__13
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__13_INDEX1 ON OBJ_UNIQUE_TS__13 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__13_INDEX2 ON OBJ_UNIQUE_TS__13 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__14
GO

CREATE TABLE OBJ_UNIQUE_TS__14
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__14_INDEX1 ON OBJ_UNIQUE_TS__14 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__14_INDEX2 ON OBJ_UNIQUE_TS__14 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__15
GO

CREATE TABLE OBJ_UNIQUE_TS__15
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__15_INDEX1 ON OBJ_UNIQUE_TS__15 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__15_INDEX2 ON OBJ_UNIQUE_TS__15 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__16
GO

CREATE TABLE OBJ_UNIQUE_TS__16
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__16_INDEX1 ON OBJ_UNIQUE_TS__16 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__16_INDEX2 ON OBJ_UNIQUE_TS__16 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__17
GO

CREATE TABLE OBJ_UNIQUE_TS__17
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__17_INDEX1 ON OBJ_UNIQUE_TS__17 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__17_INDEX2 ON OBJ_UNIQUE_TS__17 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__18
GO

CREATE TABLE OBJ_UNIQUE_TS__18
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__18_INDEX1 ON OBJ_UNIQUE_TS__18 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__18_INDEX2 ON OBJ_UNIQUE_TS__18 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__19
GO

CREATE TABLE OBJ_UNIQUE_TS__19
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__19_INDEX1 ON OBJ_UNIQUE_TS__19 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__19_INDEX2 ON OBJ_UNIQUE_TS__19 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__20
GO

CREATE TABLE OBJ_UNIQUE_TS__20
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__20_INDEX1 ON OBJ_UNIQUE_TS__20 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__20_INDEX2 ON OBJ_UNIQUE_TS__20 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__21
GO

CREATE TABLE OBJ_UNIQUE_TS__21
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__21_INDEX1 ON OBJ_UNIQUE_TS__21 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__21_INDEX2 ON OBJ_UNIQUE_TS__21 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__22
GO

CREATE TABLE OBJ_UNIQUE_TS__22
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__22_INDEX1 ON OBJ_UNIQUE_TS__22 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__22_INDEX2 ON OBJ_UNIQUE_TS__22 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__23
GO

CREATE TABLE OBJ_UNIQUE_TS__23
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__23_INDEX1 ON OBJ_UNIQUE_TS__23 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__23_INDEX2 ON OBJ_UNIQUE_TS__23 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__24
GO

CREATE TABLE OBJ_UNIQUE_TS__24
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__24_INDEX1 ON OBJ_UNIQUE_TS__24 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__24_INDEX2 ON OBJ_UNIQUE_TS__24 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__25
GO

CREATE TABLE OBJ_UNIQUE_TS__25
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__25_INDEX1 ON OBJ_UNIQUE_TS__25 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__25_INDEX2 ON OBJ_UNIQUE_TS__25 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__26
GO

CREATE TABLE OBJ_UNIQUE_TS__26
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__26_INDEX1 ON OBJ_UNIQUE_TS__26 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__26_INDEX2 ON OBJ_UNIQUE_TS__26 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__27
GO

CREATE TABLE OBJ_UNIQUE_TS__27
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__27_INDEX1 ON OBJ_UNIQUE_TS__27 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__27_INDEX2 ON OBJ_UNIQUE_TS__27 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__28
GO

CREATE TABLE OBJ_UNIQUE_TS__28
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__28_INDEX1 ON OBJ_UNIQUE_TS__28 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__28_INDEX2 ON OBJ_UNIQUE_TS__28 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__29
GO

CREATE TABLE OBJ_UNIQUE_TS__29
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__29_INDEX1 ON OBJ_UNIQUE_TS__29 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__29_INDEX2 ON OBJ_UNIQUE_TS__29 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__30
GO

CREATE TABLE OBJ_UNIQUE_TS__30
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__30_INDEX1 ON OBJ_UNIQUE_TS__30 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__30_INDEX2 ON OBJ_UNIQUE_TS__30 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__31
GO

CREATE TABLE OBJ_UNIQUE_TS__31
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__31_INDEX1 ON OBJ_UNIQUE_TS__31 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__31_INDEX2 ON OBJ_UNIQUE_TS__31 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__32
GO

CREATE TABLE OBJ_UNIQUE_TS__32
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__32_INDEX1 ON OBJ_UNIQUE_TS__32 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__32_INDEX2 ON OBJ_UNIQUE_TS__32 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__33
GO

CREATE TABLE OBJ_UNIQUE_TS__33
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__33_INDEX1 ON OBJ_UNIQUE_TS__33 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__33_INDEX2 ON OBJ_UNIQUE_TS__33 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__34
GO

CREATE TABLE OBJ_UNIQUE_TS__34
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__34_INDEX1 ON OBJ_UNIQUE_TS__34 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__34_INDEX2 ON OBJ_UNIQUE_TS__34 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__35
GO

CREATE TABLE OBJ_UNIQUE_TS__35
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__35_INDEX1 ON OBJ_UNIQUE_TS__35 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__35_INDEX2 ON OBJ_UNIQUE_TS__35 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__36
GO

CREATE TABLE OBJ_UNIQUE_TS__36
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__36_INDEX1 ON OBJ_UNIQUE_TS__36 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__36_INDEX2 ON OBJ_UNIQUE_TS__36 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__37
GO

CREATE TABLE OBJ_UNIQUE_TS__37
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__37_INDEX1 ON OBJ_UNIQUE_TS__37 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__37_INDEX2 ON OBJ_UNIQUE_TS__37 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__38
GO

CREATE TABLE OBJ_UNIQUE_TS__38
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__38_INDEX1 ON OBJ_UNIQUE_TS__38 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__38_INDEX2 ON OBJ_UNIQUE_TS__38 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__39
GO

CREATE TABLE OBJ_UNIQUE_TS__39
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__39_INDEX1 ON OBJ_UNIQUE_TS__39 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__39_INDEX2 ON OBJ_UNIQUE_TS__39 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__40
GO

CREATE TABLE OBJ_UNIQUE_TS__40
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__40_INDEX1 ON OBJ_UNIQUE_TS__40 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__40_INDEX2 ON OBJ_UNIQUE_TS__40 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__41
GO

CREATE TABLE OBJ_UNIQUE_TS__41
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__41_INDEX1 ON OBJ_UNIQUE_TS__41 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__41_INDEX2 ON OBJ_UNIQUE_TS__41 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__42
GO

CREATE TABLE OBJ_UNIQUE_TS__42
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__42_INDEX1 ON OBJ_UNIQUE_TS__42 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__42_INDEX2 ON OBJ_UNIQUE_TS__42 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__43
GO

CREATE TABLE OBJ_UNIQUE_TS__43
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__43_INDEX1 ON OBJ_UNIQUE_TS__43 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__43_INDEX2 ON OBJ_UNIQUE_TS__43 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__44
GO

CREATE TABLE OBJ_UNIQUE_TS__44
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__44_INDEX1 ON OBJ_UNIQUE_TS__44 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__44_INDEX2 ON OBJ_UNIQUE_TS__44 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__45
GO

CREATE TABLE OBJ_UNIQUE_TS__45
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__45_INDEX1 ON OBJ_UNIQUE_TS__45 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__45_INDEX2 ON OBJ_UNIQUE_TS__45 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__46
GO

CREATE TABLE OBJ_UNIQUE_TS__46
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__46_INDEX1 ON OBJ_UNIQUE_TS__46 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__46_INDEX2 ON OBJ_UNIQUE_TS__46 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__47
GO

CREATE TABLE OBJ_UNIQUE_TS__47
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__47_INDEX1 ON OBJ_UNIQUE_TS__47 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__47_INDEX2 ON OBJ_UNIQUE_TS__47 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__48
GO

CREATE TABLE OBJ_UNIQUE_TS__48
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__48_INDEX1 ON OBJ_UNIQUE_TS__48 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__48_INDEX2 ON OBJ_UNIQUE_TS__48 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__49
GO

CREATE TABLE OBJ_UNIQUE_TS__49
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__49_INDEX1 ON OBJ_UNIQUE_TS__49 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__49_INDEX2 ON OBJ_UNIQUE_TS__49 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__50
GO

CREATE TABLE OBJ_UNIQUE_TS__50
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__50_INDEX1 ON OBJ_UNIQUE_TS__50 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__50_INDEX2 ON OBJ_UNIQUE_TS__50 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__51
GO

CREATE TABLE OBJ_UNIQUE_TS__51
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__51_INDEX1 ON OBJ_UNIQUE_TS__51 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__51_INDEX2 ON OBJ_UNIQUE_TS__51 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__52
GO

CREATE TABLE OBJ_UNIQUE_TS__52
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__52_INDEX1 ON OBJ_UNIQUE_TS__52 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__52_INDEX2 ON OBJ_UNIQUE_TS__52 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__53
GO

CREATE TABLE OBJ_UNIQUE_TS__53
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__53_INDEX1 ON OBJ_UNIQUE_TS__53 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__53_INDEX2 ON OBJ_UNIQUE_TS__53 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__54
GO

CREATE TABLE OBJ_UNIQUE_TS__54
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__54_INDEX1 ON OBJ_UNIQUE_TS__54 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__54_INDEX2 ON OBJ_UNIQUE_TS__54 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__55
GO

CREATE TABLE OBJ_UNIQUE_TS__55
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__55_INDEX1 ON OBJ_UNIQUE_TS__55 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__55_INDEX2 ON OBJ_UNIQUE_TS__55 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__56
GO

CREATE TABLE OBJ_UNIQUE_TS__56
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__56_INDEX1 ON OBJ_UNIQUE_TS__56 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__56_INDEX2 ON OBJ_UNIQUE_TS__56 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__57
GO

CREATE TABLE OBJ_UNIQUE_TS__57
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__57_INDEX1 ON OBJ_UNIQUE_TS__57 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__57_INDEX2 ON OBJ_UNIQUE_TS__57 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__58
GO

CREATE TABLE OBJ_UNIQUE_TS__58
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__58_INDEX1 ON OBJ_UNIQUE_TS__58 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__58_INDEX2 ON OBJ_UNIQUE_TS__58 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__59
GO

CREATE TABLE OBJ_UNIQUE_TS__59
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__59_INDEX1 ON OBJ_UNIQUE_TS__59 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__59_INDEX2 ON OBJ_UNIQUE_TS__59 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__60
GO

CREATE TABLE OBJ_UNIQUE_TS__60
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__60_INDEX1 ON OBJ_UNIQUE_TS__60 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__60_INDEX2 ON OBJ_UNIQUE_TS__60 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__61
GO

CREATE TABLE OBJ_UNIQUE_TS__61
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__61_INDEX1 ON OBJ_UNIQUE_TS__61 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__61_INDEX2 ON OBJ_UNIQUE_TS__61 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__62
GO

CREATE TABLE OBJ_UNIQUE_TS__62
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__62_INDEX1 ON OBJ_UNIQUE_TS__62 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__62_INDEX2 ON OBJ_UNIQUE_TS__62 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__63
GO

CREATE TABLE OBJ_UNIQUE_TS__63
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__63_INDEX1 ON OBJ_UNIQUE_TS__63 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__63_INDEX2 ON OBJ_UNIQUE_TS__63 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__64
GO

CREATE TABLE OBJ_UNIQUE_TS__64
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__64_INDEX1 ON OBJ_UNIQUE_TS__64 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__64_INDEX2 ON OBJ_UNIQUE_TS__64 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__65
GO

CREATE TABLE OBJ_UNIQUE_TS__65
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__65_INDEX1 ON OBJ_UNIQUE_TS__65 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__65_INDEX2 ON OBJ_UNIQUE_TS__65 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__66
GO

CREATE TABLE OBJ_UNIQUE_TS__66
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__66_INDEX1 ON OBJ_UNIQUE_TS__66 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__66_INDEX2 ON OBJ_UNIQUE_TS__66 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__67
GO

CREATE TABLE OBJ_UNIQUE_TS__67
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__67_INDEX1 ON OBJ_UNIQUE_TS__67 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__67_INDEX2 ON OBJ_UNIQUE_TS__67 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__68
GO

CREATE TABLE OBJ_UNIQUE_TS__68
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__68_INDEX1 ON OBJ_UNIQUE_TS__68 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__68_INDEX2 ON OBJ_UNIQUE_TS__68 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__69
GO

CREATE TABLE OBJ_UNIQUE_TS__69
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__69_INDEX1 ON OBJ_UNIQUE_TS__69 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__69_INDEX2 ON OBJ_UNIQUE_TS__69 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__70
GO

CREATE TABLE OBJ_UNIQUE_TS__70
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__70_INDEX1 ON OBJ_UNIQUE_TS__70 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__70_INDEX2 ON OBJ_UNIQUE_TS__70 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__71
GO

CREATE TABLE OBJ_UNIQUE_TS__71
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__71_INDEX1 ON OBJ_UNIQUE_TS__71 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__71_INDEX2 ON OBJ_UNIQUE_TS__71 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__72
GO

CREATE TABLE OBJ_UNIQUE_TS__72
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__72_INDEX1 ON OBJ_UNIQUE_TS__72 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__72_INDEX2 ON OBJ_UNIQUE_TS__72 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__73
GO

CREATE TABLE OBJ_UNIQUE_TS__73
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__73_INDEX1 ON OBJ_UNIQUE_TS__73 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__73_INDEX2 ON OBJ_UNIQUE_TS__73 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__74
GO

CREATE TABLE OBJ_UNIQUE_TS__74
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__74_INDEX1 ON OBJ_UNIQUE_TS__74 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__74_INDEX2 ON OBJ_UNIQUE_TS__74 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__75
GO

CREATE TABLE OBJ_UNIQUE_TS__75
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__75_INDEX1 ON OBJ_UNIQUE_TS__75 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__75_INDEX2 ON OBJ_UNIQUE_TS__75 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__76
GO

CREATE TABLE OBJ_UNIQUE_TS__76
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__76_INDEX1 ON OBJ_UNIQUE_TS__76 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__76_INDEX2 ON OBJ_UNIQUE_TS__76 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__77
GO

CREATE TABLE OBJ_UNIQUE_TS__77
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__77_INDEX1 ON OBJ_UNIQUE_TS__77 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__77_INDEX2 ON OBJ_UNIQUE_TS__77 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__78
GO

CREATE TABLE OBJ_UNIQUE_TS__78
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__78_INDEX1 ON OBJ_UNIQUE_TS__78 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__78_INDEX2 ON OBJ_UNIQUE_TS__78 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__79
GO

CREATE TABLE OBJ_UNIQUE_TS__79
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__79_INDEX1 ON OBJ_UNIQUE_TS__79 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__79_INDEX2 ON OBJ_UNIQUE_TS__79 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__80
GO

CREATE TABLE OBJ_UNIQUE_TS__80
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__80_INDEX1 ON OBJ_UNIQUE_TS__80 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__80_INDEX2 ON OBJ_UNIQUE_TS__80 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__81
GO

CREATE TABLE OBJ_UNIQUE_TS__81
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__81_INDEX1 ON OBJ_UNIQUE_TS__81 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__81_INDEX2 ON OBJ_UNIQUE_TS__81 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__82
GO

CREATE TABLE OBJ_UNIQUE_TS__82
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__82_INDEX1 ON OBJ_UNIQUE_TS__82 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__82_INDEX2 ON OBJ_UNIQUE_TS__82 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__83
GO

CREATE TABLE OBJ_UNIQUE_TS__83
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__83_INDEX1 ON OBJ_UNIQUE_TS__83 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__83_INDEX2 ON OBJ_UNIQUE_TS__83 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__84
GO

CREATE TABLE OBJ_UNIQUE_TS__84
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__84_INDEX1 ON OBJ_UNIQUE_TS__84 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__84_INDEX2 ON OBJ_UNIQUE_TS__84 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__85
GO

CREATE TABLE OBJ_UNIQUE_TS__85
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__85_INDEX1 ON OBJ_UNIQUE_TS__85 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__85_INDEX2 ON OBJ_UNIQUE_TS__85 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__86
GO

CREATE TABLE OBJ_UNIQUE_TS__86
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__86_INDEX1 ON OBJ_UNIQUE_TS__86 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__86_INDEX2 ON OBJ_UNIQUE_TS__86 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__87
GO

CREATE TABLE OBJ_UNIQUE_TS__87
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__87_INDEX1 ON OBJ_UNIQUE_TS__87 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__87_INDEX2 ON OBJ_UNIQUE_TS__87 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__88
GO

CREATE TABLE OBJ_UNIQUE_TS__88
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__88_INDEX1 ON OBJ_UNIQUE_TS__88 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__88_INDEX2 ON OBJ_UNIQUE_TS__88 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__89
GO

CREATE TABLE OBJ_UNIQUE_TS__89
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__89_INDEX1 ON OBJ_UNIQUE_TS__89 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__89_INDEX2 ON OBJ_UNIQUE_TS__89 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__90
GO

CREATE TABLE OBJ_UNIQUE_TS__90
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__90_INDEX1 ON OBJ_UNIQUE_TS__90 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__90_INDEX2 ON OBJ_UNIQUE_TS__90 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__91
GO

CREATE TABLE OBJ_UNIQUE_TS__91
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__91_INDEX1 ON OBJ_UNIQUE_TS__91 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__91_INDEX2 ON OBJ_UNIQUE_TS__91 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__92
GO

CREATE TABLE OBJ_UNIQUE_TS__92
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__92_INDEX1 ON OBJ_UNIQUE_TS__92 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__92_INDEX2 ON OBJ_UNIQUE_TS__92 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__93
GO

CREATE TABLE OBJ_UNIQUE_TS__93
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__93_INDEX1 ON OBJ_UNIQUE_TS__93 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__93_INDEX2 ON OBJ_UNIQUE_TS__93 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__94
GO

CREATE TABLE OBJ_UNIQUE_TS__94
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__94_INDEX1 ON OBJ_UNIQUE_TS__94 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__94_INDEX2 ON OBJ_UNIQUE_TS__94 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__95
GO

CREATE TABLE OBJ_UNIQUE_TS__95
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__95_INDEX1 ON OBJ_UNIQUE_TS__95 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__95_INDEX2 ON OBJ_UNIQUE_TS__95 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__96
GO

CREATE TABLE OBJ_UNIQUE_TS__96
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__96_INDEX1 ON OBJ_UNIQUE_TS__96 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__96_INDEX2 ON OBJ_UNIQUE_TS__96 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__97
GO

CREATE TABLE OBJ_UNIQUE_TS__97
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__97_INDEX1 ON OBJ_UNIQUE_TS__97 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__97_INDEX2 ON OBJ_UNIQUE_TS__97 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__98
GO

CREATE TABLE OBJ_UNIQUE_TS__98
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__98_INDEX1 ON OBJ_UNIQUE_TS__98 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__98_INDEX2 ON OBJ_UNIQUE_TS__98 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__99
GO

CREATE TABLE OBJ_UNIQUE_TS__99
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__99_INDEX1 ON OBJ_UNIQUE_TS__99 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__99_INDEX2 ON OBJ_UNIQUE_TS__99 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__100
GO

CREATE TABLE OBJ_UNIQUE_TS__100
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__100_INDEX1 ON OBJ_UNIQUE_TS__100 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__100_INDEX2 ON OBJ_UNIQUE_TS__100 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__101
GO

CREATE TABLE OBJ_UNIQUE_TS__101
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__101_INDEX1 ON OBJ_UNIQUE_TS__101 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__101_INDEX2 ON OBJ_UNIQUE_TS__101 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__102
GO

CREATE TABLE OBJ_UNIQUE_TS__102
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__102_INDEX1 ON OBJ_UNIQUE_TS__102 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__102_INDEX2 ON OBJ_UNIQUE_TS__102 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__103
GO

CREATE TABLE OBJ_UNIQUE_TS__103
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__103_INDEX1 ON OBJ_UNIQUE_TS__103 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__103_INDEX2 ON OBJ_UNIQUE_TS__103 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__104
GO

CREATE TABLE OBJ_UNIQUE_TS__104
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__104_INDEX1 ON OBJ_UNIQUE_TS__104 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__104_INDEX2 ON OBJ_UNIQUE_TS__104 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__105
GO

CREATE TABLE OBJ_UNIQUE_TS__105
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__105_INDEX1 ON OBJ_UNIQUE_TS__105 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__105_INDEX2 ON OBJ_UNIQUE_TS__105 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__106
GO

CREATE TABLE OBJ_UNIQUE_TS__106
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__106_INDEX1 ON OBJ_UNIQUE_TS__106 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__106_INDEX2 ON OBJ_UNIQUE_TS__106 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__107
GO

CREATE TABLE OBJ_UNIQUE_TS__107
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__107_INDEX1 ON OBJ_UNIQUE_TS__107 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__107_INDEX2 ON OBJ_UNIQUE_TS__107 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__108
GO

CREATE TABLE OBJ_UNIQUE_TS__108
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__108_INDEX1 ON OBJ_UNIQUE_TS__108 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__108_INDEX2 ON OBJ_UNIQUE_TS__108 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__109
GO

CREATE TABLE OBJ_UNIQUE_TS__109
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__109_INDEX1 ON OBJ_UNIQUE_TS__109 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__109_INDEX2 ON OBJ_UNIQUE_TS__109 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__110
GO

CREATE TABLE OBJ_UNIQUE_TS__110
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__110_INDEX1 ON OBJ_UNIQUE_TS__110 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__110_INDEX2 ON OBJ_UNIQUE_TS__110 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__111
GO

CREATE TABLE OBJ_UNIQUE_TS__111
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__111_INDEX1 ON OBJ_UNIQUE_TS__111 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__111_INDEX2 ON OBJ_UNIQUE_TS__111 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__112
GO

CREATE TABLE OBJ_UNIQUE_TS__112
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__112_INDEX1 ON OBJ_UNIQUE_TS__112 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__112_INDEX2 ON OBJ_UNIQUE_TS__112 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__113
GO

CREATE TABLE OBJ_UNIQUE_TS__113
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__113_INDEX1 ON OBJ_UNIQUE_TS__113 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__113_INDEX2 ON OBJ_UNIQUE_TS__113 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__114
GO

CREATE TABLE OBJ_UNIQUE_TS__114
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__114_INDEX1 ON OBJ_UNIQUE_TS__114 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__114_INDEX2 ON OBJ_UNIQUE_TS__114 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__115
GO

CREATE TABLE OBJ_UNIQUE_TS__115
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__115_INDEX1 ON OBJ_UNIQUE_TS__115 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__115_INDEX2 ON OBJ_UNIQUE_TS__115 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__116
GO

CREATE TABLE OBJ_UNIQUE_TS__116
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__116_INDEX1 ON OBJ_UNIQUE_TS__116 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__116_INDEX2 ON OBJ_UNIQUE_TS__116 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__117
GO

CREATE TABLE OBJ_UNIQUE_TS__117
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__117_INDEX1 ON OBJ_UNIQUE_TS__117 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__117_INDEX2 ON OBJ_UNIQUE_TS__117 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__118
GO

CREATE TABLE OBJ_UNIQUE_TS__118
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__118_INDEX1 ON OBJ_UNIQUE_TS__118 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__118_INDEX2 ON OBJ_UNIQUE_TS__118 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__119
GO

CREATE TABLE OBJ_UNIQUE_TS__119
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__119_INDEX1 ON OBJ_UNIQUE_TS__119 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__119_INDEX2 ON OBJ_UNIQUE_TS__119 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__120
GO

CREATE TABLE OBJ_UNIQUE_TS__120
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__120_INDEX1 ON OBJ_UNIQUE_TS__120 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__120_INDEX2 ON OBJ_UNIQUE_TS__120 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__121
GO

CREATE TABLE OBJ_UNIQUE_TS__121
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__121_INDEX1 ON OBJ_UNIQUE_TS__121 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__121_INDEX2 ON OBJ_UNIQUE_TS__121 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__122
GO

CREATE TABLE OBJ_UNIQUE_TS__122
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__122_INDEX1 ON OBJ_UNIQUE_TS__122 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__122_INDEX2 ON OBJ_UNIQUE_TS__122 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__123
GO

CREATE TABLE OBJ_UNIQUE_TS__123
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__123_INDEX1 ON OBJ_UNIQUE_TS__123 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__123_INDEX2 ON OBJ_UNIQUE_TS__123 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__124
GO

CREATE TABLE OBJ_UNIQUE_TS__124
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__124_INDEX1 ON OBJ_UNIQUE_TS__124 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__124_INDEX2 ON OBJ_UNIQUE_TS__124 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__125
GO

CREATE TABLE OBJ_UNIQUE_TS__125
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__125_INDEX1 ON OBJ_UNIQUE_TS__125 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__125_INDEX2 ON OBJ_UNIQUE_TS__125 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__126
GO

CREATE TABLE OBJ_UNIQUE_TS__126
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__126_INDEX1 ON OBJ_UNIQUE_TS__126 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__126_INDEX2 ON OBJ_UNIQUE_TS__126 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_TS */
DROP TABLE OBJ_UNIQUE_TS__127
GO

CREATE TABLE OBJ_UNIQUE_TS__127
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL DATETIME2(3)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_TS__127_INDEX1 ON OBJ_UNIQUE_TS__127 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_TS__127_INDEX2 ON OBJ_UNIQUE_TS__127 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
