use mtdb
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL
GO

CREATE TABLE OBJ_INDEX_DBL
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL_INDEX1 ON OBJ_INDEX_DBL (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL_INDEX2 ON OBJ_INDEX_DBL (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__1
GO

CREATE TABLE OBJ_INDEX_DBL__1
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__1_INDEX1 ON OBJ_INDEX_DBL__1 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__1_INDEX2 ON OBJ_INDEX_DBL__1 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__2
GO

CREATE TABLE OBJ_INDEX_DBL__2
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__2_INDEX1 ON OBJ_INDEX_DBL__2 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__2_INDEX2 ON OBJ_INDEX_DBL__2 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__3
GO

CREATE TABLE OBJ_INDEX_DBL__3
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__3_INDEX1 ON OBJ_INDEX_DBL__3 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__3_INDEX2 ON OBJ_INDEX_DBL__3 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__4
GO

CREATE TABLE OBJ_INDEX_DBL__4
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__4_INDEX1 ON OBJ_INDEX_DBL__4 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__4_INDEX2 ON OBJ_INDEX_DBL__4 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__5
GO

CREATE TABLE OBJ_INDEX_DBL__5
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__5_INDEX1 ON OBJ_INDEX_DBL__5 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__5_INDEX2 ON OBJ_INDEX_DBL__5 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__6
GO

CREATE TABLE OBJ_INDEX_DBL__6
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__6_INDEX1 ON OBJ_INDEX_DBL__6 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__6_INDEX2 ON OBJ_INDEX_DBL__6 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__7
GO

CREATE TABLE OBJ_INDEX_DBL__7
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__7_INDEX1 ON OBJ_INDEX_DBL__7 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__7_INDEX2 ON OBJ_INDEX_DBL__7 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__8
GO

CREATE TABLE OBJ_INDEX_DBL__8
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__8_INDEX1 ON OBJ_INDEX_DBL__8 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__8_INDEX2 ON OBJ_INDEX_DBL__8 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__9
GO

CREATE TABLE OBJ_INDEX_DBL__9
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__9_INDEX1 ON OBJ_INDEX_DBL__9 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__9_INDEX2 ON OBJ_INDEX_DBL__9 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__10
GO

CREATE TABLE OBJ_INDEX_DBL__10
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__10_INDEX1 ON OBJ_INDEX_DBL__10 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__10_INDEX2 ON OBJ_INDEX_DBL__10 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__11
GO

CREATE TABLE OBJ_INDEX_DBL__11
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__11_INDEX1 ON OBJ_INDEX_DBL__11 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__11_INDEX2 ON OBJ_INDEX_DBL__11 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__12
GO

CREATE TABLE OBJ_INDEX_DBL__12
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__12_INDEX1 ON OBJ_INDEX_DBL__12 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__12_INDEX2 ON OBJ_INDEX_DBL__12 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__13
GO

CREATE TABLE OBJ_INDEX_DBL__13
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__13_INDEX1 ON OBJ_INDEX_DBL__13 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__13_INDEX2 ON OBJ_INDEX_DBL__13 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__14
GO

CREATE TABLE OBJ_INDEX_DBL__14
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__14_INDEX1 ON OBJ_INDEX_DBL__14 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__14_INDEX2 ON OBJ_INDEX_DBL__14 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__15
GO

CREATE TABLE OBJ_INDEX_DBL__15
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__15_INDEX1 ON OBJ_INDEX_DBL__15 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__15_INDEX2 ON OBJ_INDEX_DBL__15 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__16
GO

CREATE TABLE OBJ_INDEX_DBL__16
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__16_INDEX1 ON OBJ_INDEX_DBL__16 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__16_INDEX2 ON OBJ_INDEX_DBL__16 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__17
GO

CREATE TABLE OBJ_INDEX_DBL__17
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__17_INDEX1 ON OBJ_INDEX_DBL__17 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__17_INDEX2 ON OBJ_INDEX_DBL__17 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__18
GO

CREATE TABLE OBJ_INDEX_DBL__18
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__18_INDEX1 ON OBJ_INDEX_DBL__18 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__18_INDEX2 ON OBJ_INDEX_DBL__18 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__19
GO

CREATE TABLE OBJ_INDEX_DBL__19
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__19_INDEX1 ON OBJ_INDEX_DBL__19 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__19_INDEX2 ON OBJ_INDEX_DBL__19 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__20
GO

CREATE TABLE OBJ_INDEX_DBL__20
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__20_INDEX1 ON OBJ_INDEX_DBL__20 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__20_INDEX2 ON OBJ_INDEX_DBL__20 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__21
GO

CREATE TABLE OBJ_INDEX_DBL__21
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__21_INDEX1 ON OBJ_INDEX_DBL__21 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__21_INDEX2 ON OBJ_INDEX_DBL__21 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__22
GO

CREATE TABLE OBJ_INDEX_DBL__22
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__22_INDEX1 ON OBJ_INDEX_DBL__22 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__22_INDEX2 ON OBJ_INDEX_DBL__22 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__23
GO

CREATE TABLE OBJ_INDEX_DBL__23
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__23_INDEX1 ON OBJ_INDEX_DBL__23 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__23_INDEX2 ON OBJ_INDEX_DBL__23 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__24
GO

CREATE TABLE OBJ_INDEX_DBL__24
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__24_INDEX1 ON OBJ_INDEX_DBL__24 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__24_INDEX2 ON OBJ_INDEX_DBL__24 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__25
GO

CREATE TABLE OBJ_INDEX_DBL__25
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__25_INDEX1 ON OBJ_INDEX_DBL__25 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__25_INDEX2 ON OBJ_INDEX_DBL__25 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__26
GO

CREATE TABLE OBJ_INDEX_DBL__26
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__26_INDEX1 ON OBJ_INDEX_DBL__26 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__26_INDEX2 ON OBJ_INDEX_DBL__26 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__27
GO

CREATE TABLE OBJ_INDEX_DBL__27
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__27_INDEX1 ON OBJ_INDEX_DBL__27 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__27_INDEX2 ON OBJ_INDEX_DBL__27 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__28
GO

CREATE TABLE OBJ_INDEX_DBL__28
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__28_INDEX1 ON OBJ_INDEX_DBL__28 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__28_INDEX2 ON OBJ_INDEX_DBL__28 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__29
GO

CREATE TABLE OBJ_INDEX_DBL__29
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__29_INDEX1 ON OBJ_INDEX_DBL__29 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__29_INDEX2 ON OBJ_INDEX_DBL__29 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__30
GO

CREATE TABLE OBJ_INDEX_DBL__30
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__30_INDEX1 ON OBJ_INDEX_DBL__30 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__30_INDEX2 ON OBJ_INDEX_DBL__30 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__31
GO

CREATE TABLE OBJ_INDEX_DBL__31
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__31_INDEX1 ON OBJ_INDEX_DBL__31 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__31_INDEX2 ON OBJ_INDEX_DBL__31 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__32
GO

CREATE TABLE OBJ_INDEX_DBL__32
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__32_INDEX1 ON OBJ_INDEX_DBL__32 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__32_INDEX2 ON OBJ_INDEX_DBL__32 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__33
GO

CREATE TABLE OBJ_INDEX_DBL__33
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__33_INDEX1 ON OBJ_INDEX_DBL__33 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__33_INDEX2 ON OBJ_INDEX_DBL__33 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__34
GO

CREATE TABLE OBJ_INDEX_DBL__34
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__34_INDEX1 ON OBJ_INDEX_DBL__34 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__34_INDEX2 ON OBJ_INDEX_DBL__34 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__35
GO

CREATE TABLE OBJ_INDEX_DBL__35
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__35_INDEX1 ON OBJ_INDEX_DBL__35 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__35_INDEX2 ON OBJ_INDEX_DBL__35 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__36
GO

CREATE TABLE OBJ_INDEX_DBL__36
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__36_INDEX1 ON OBJ_INDEX_DBL__36 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__36_INDEX2 ON OBJ_INDEX_DBL__36 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__37
GO

CREATE TABLE OBJ_INDEX_DBL__37
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__37_INDEX1 ON OBJ_INDEX_DBL__37 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__37_INDEX2 ON OBJ_INDEX_DBL__37 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__38
GO

CREATE TABLE OBJ_INDEX_DBL__38
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__38_INDEX1 ON OBJ_INDEX_DBL__38 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__38_INDEX2 ON OBJ_INDEX_DBL__38 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__39
GO

CREATE TABLE OBJ_INDEX_DBL__39
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__39_INDEX1 ON OBJ_INDEX_DBL__39 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__39_INDEX2 ON OBJ_INDEX_DBL__39 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__40
GO

CREATE TABLE OBJ_INDEX_DBL__40
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__40_INDEX1 ON OBJ_INDEX_DBL__40 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__40_INDEX2 ON OBJ_INDEX_DBL__40 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__41
GO

CREATE TABLE OBJ_INDEX_DBL__41
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__41_INDEX1 ON OBJ_INDEX_DBL__41 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__41_INDEX2 ON OBJ_INDEX_DBL__41 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__42
GO

CREATE TABLE OBJ_INDEX_DBL__42
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__42_INDEX1 ON OBJ_INDEX_DBL__42 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__42_INDEX2 ON OBJ_INDEX_DBL__42 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__43
GO

CREATE TABLE OBJ_INDEX_DBL__43
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__43_INDEX1 ON OBJ_INDEX_DBL__43 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__43_INDEX2 ON OBJ_INDEX_DBL__43 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__44
GO

CREATE TABLE OBJ_INDEX_DBL__44
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__44_INDEX1 ON OBJ_INDEX_DBL__44 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__44_INDEX2 ON OBJ_INDEX_DBL__44 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__45
GO

CREATE TABLE OBJ_INDEX_DBL__45
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__45_INDEX1 ON OBJ_INDEX_DBL__45 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__45_INDEX2 ON OBJ_INDEX_DBL__45 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__46
GO

CREATE TABLE OBJ_INDEX_DBL__46
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__46_INDEX1 ON OBJ_INDEX_DBL__46 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__46_INDEX2 ON OBJ_INDEX_DBL__46 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__47
GO

CREATE TABLE OBJ_INDEX_DBL__47
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__47_INDEX1 ON OBJ_INDEX_DBL__47 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__47_INDEX2 ON OBJ_INDEX_DBL__47 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__48
GO

CREATE TABLE OBJ_INDEX_DBL__48
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__48_INDEX1 ON OBJ_INDEX_DBL__48 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__48_INDEX2 ON OBJ_INDEX_DBL__48 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__49
GO

CREATE TABLE OBJ_INDEX_DBL__49
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__49_INDEX1 ON OBJ_INDEX_DBL__49 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__49_INDEX2 ON OBJ_INDEX_DBL__49 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__50
GO

CREATE TABLE OBJ_INDEX_DBL__50
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__50_INDEX1 ON OBJ_INDEX_DBL__50 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__50_INDEX2 ON OBJ_INDEX_DBL__50 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__51
GO

CREATE TABLE OBJ_INDEX_DBL__51
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__51_INDEX1 ON OBJ_INDEX_DBL__51 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__51_INDEX2 ON OBJ_INDEX_DBL__51 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__52
GO

CREATE TABLE OBJ_INDEX_DBL__52
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__52_INDEX1 ON OBJ_INDEX_DBL__52 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__52_INDEX2 ON OBJ_INDEX_DBL__52 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__53
GO

CREATE TABLE OBJ_INDEX_DBL__53
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__53_INDEX1 ON OBJ_INDEX_DBL__53 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__53_INDEX2 ON OBJ_INDEX_DBL__53 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__54
GO

CREATE TABLE OBJ_INDEX_DBL__54
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__54_INDEX1 ON OBJ_INDEX_DBL__54 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__54_INDEX2 ON OBJ_INDEX_DBL__54 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__55
GO

CREATE TABLE OBJ_INDEX_DBL__55
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__55_INDEX1 ON OBJ_INDEX_DBL__55 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__55_INDEX2 ON OBJ_INDEX_DBL__55 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__56
GO

CREATE TABLE OBJ_INDEX_DBL__56
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__56_INDEX1 ON OBJ_INDEX_DBL__56 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__56_INDEX2 ON OBJ_INDEX_DBL__56 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__57
GO

CREATE TABLE OBJ_INDEX_DBL__57
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__57_INDEX1 ON OBJ_INDEX_DBL__57 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__57_INDEX2 ON OBJ_INDEX_DBL__57 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__58
GO

CREATE TABLE OBJ_INDEX_DBL__58
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__58_INDEX1 ON OBJ_INDEX_DBL__58 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__58_INDEX2 ON OBJ_INDEX_DBL__58 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__59
GO

CREATE TABLE OBJ_INDEX_DBL__59
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__59_INDEX1 ON OBJ_INDEX_DBL__59 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__59_INDEX2 ON OBJ_INDEX_DBL__59 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__60
GO

CREATE TABLE OBJ_INDEX_DBL__60
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__60_INDEX1 ON OBJ_INDEX_DBL__60 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__60_INDEX2 ON OBJ_INDEX_DBL__60 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__61
GO

CREATE TABLE OBJ_INDEX_DBL__61
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__61_INDEX1 ON OBJ_INDEX_DBL__61 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__61_INDEX2 ON OBJ_INDEX_DBL__61 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__62
GO

CREATE TABLE OBJ_INDEX_DBL__62
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__62_INDEX1 ON OBJ_INDEX_DBL__62 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__62_INDEX2 ON OBJ_INDEX_DBL__62 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__63
GO

CREATE TABLE OBJ_INDEX_DBL__63
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__63_INDEX1 ON OBJ_INDEX_DBL__63 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__63_INDEX2 ON OBJ_INDEX_DBL__63 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__64
GO

CREATE TABLE OBJ_INDEX_DBL__64
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__64_INDEX1 ON OBJ_INDEX_DBL__64 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__64_INDEX2 ON OBJ_INDEX_DBL__64 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__65
GO

CREATE TABLE OBJ_INDEX_DBL__65
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__65_INDEX1 ON OBJ_INDEX_DBL__65 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__65_INDEX2 ON OBJ_INDEX_DBL__65 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__66
GO

CREATE TABLE OBJ_INDEX_DBL__66
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__66_INDEX1 ON OBJ_INDEX_DBL__66 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__66_INDEX2 ON OBJ_INDEX_DBL__66 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__67
GO

CREATE TABLE OBJ_INDEX_DBL__67
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__67_INDEX1 ON OBJ_INDEX_DBL__67 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__67_INDEX2 ON OBJ_INDEX_DBL__67 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__68
GO

CREATE TABLE OBJ_INDEX_DBL__68
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__68_INDEX1 ON OBJ_INDEX_DBL__68 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__68_INDEX2 ON OBJ_INDEX_DBL__68 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__69
GO

CREATE TABLE OBJ_INDEX_DBL__69
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__69_INDEX1 ON OBJ_INDEX_DBL__69 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__69_INDEX2 ON OBJ_INDEX_DBL__69 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__70
GO

CREATE TABLE OBJ_INDEX_DBL__70
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__70_INDEX1 ON OBJ_INDEX_DBL__70 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__70_INDEX2 ON OBJ_INDEX_DBL__70 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__71
GO

CREATE TABLE OBJ_INDEX_DBL__71
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__71_INDEX1 ON OBJ_INDEX_DBL__71 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__71_INDEX2 ON OBJ_INDEX_DBL__71 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__72
GO

CREATE TABLE OBJ_INDEX_DBL__72
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__72_INDEX1 ON OBJ_INDEX_DBL__72 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__72_INDEX2 ON OBJ_INDEX_DBL__72 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__73
GO

CREATE TABLE OBJ_INDEX_DBL__73
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__73_INDEX1 ON OBJ_INDEX_DBL__73 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__73_INDEX2 ON OBJ_INDEX_DBL__73 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__74
GO

CREATE TABLE OBJ_INDEX_DBL__74
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__74_INDEX1 ON OBJ_INDEX_DBL__74 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__74_INDEX2 ON OBJ_INDEX_DBL__74 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__75
GO

CREATE TABLE OBJ_INDEX_DBL__75
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__75_INDEX1 ON OBJ_INDEX_DBL__75 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__75_INDEX2 ON OBJ_INDEX_DBL__75 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__76
GO

CREATE TABLE OBJ_INDEX_DBL__76
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__76_INDEX1 ON OBJ_INDEX_DBL__76 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__76_INDEX2 ON OBJ_INDEX_DBL__76 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__77
GO

CREATE TABLE OBJ_INDEX_DBL__77
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__77_INDEX1 ON OBJ_INDEX_DBL__77 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__77_INDEX2 ON OBJ_INDEX_DBL__77 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__78
GO

CREATE TABLE OBJ_INDEX_DBL__78
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__78_INDEX1 ON OBJ_INDEX_DBL__78 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__78_INDEX2 ON OBJ_INDEX_DBL__78 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__79
GO

CREATE TABLE OBJ_INDEX_DBL__79
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__79_INDEX1 ON OBJ_INDEX_DBL__79 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__79_INDEX2 ON OBJ_INDEX_DBL__79 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__80
GO

CREATE TABLE OBJ_INDEX_DBL__80
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__80_INDEX1 ON OBJ_INDEX_DBL__80 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__80_INDEX2 ON OBJ_INDEX_DBL__80 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__81
GO

CREATE TABLE OBJ_INDEX_DBL__81
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__81_INDEX1 ON OBJ_INDEX_DBL__81 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__81_INDEX2 ON OBJ_INDEX_DBL__81 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__82
GO

CREATE TABLE OBJ_INDEX_DBL__82
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__82_INDEX1 ON OBJ_INDEX_DBL__82 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__82_INDEX2 ON OBJ_INDEX_DBL__82 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__83
GO

CREATE TABLE OBJ_INDEX_DBL__83
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__83_INDEX1 ON OBJ_INDEX_DBL__83 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__83_INDEX2 ON OBJ_INDEX_DBL__83 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__84
GO

CREATE TABLE OBJ_INDEX_DBL__84
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__84_INDEX1 ON OBJ_INDEX_DBL__84 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__84_INDEX2 ON OBJ_INDEX_DBL__84 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__85
GO

CREATE TABLE OBJ_INDEX_DBL__85
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__85_INDEX1 ON OBJ_INDEX_DBL__85 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__85_INDEX2 ON OBJ_INDEX_DBL__85 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__86
GO

CREATE TABLE OBJ_INDEX_DBL__86
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__86_INDEX1 ON OBJ_INDEX_DBL__86 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__86_INDEX2 ON OBJ_INDEX_DBL__86 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__87
GO

CREATE TABLE OBJ_INDEX_DBL__87
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__87_INDEX1 ON OBJ_INDEX_DBL__87 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__87_INDEX2 ON OBJ_INDEX_DBL__87 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__88
GO

CREATE TABLE OBJ_INDEX_DBL__88
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__88_INDEX1 ON OBJ_INDEX_DBL__88 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__88_INDEX2 ON OBJ_INDEX_DBL__88 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__89
GO

CREATE TABLE OBJ_INDEX_DBL__89
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__89_INDEX1 ON OBJ_INDEX_DBL__89 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__89_INDEX2 ON OBJ_INDEX_DBL__89 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__90
GO

CREATE TABLE OBJ_INDEX_DBL__90
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__90_INDEX1 ON OBJ_INDEX_DBL__90 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__90_INDEX2 ON OBJ_INDEX_DBL__90 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__91
GO

CREATE TABLE OBJ_INDEX_DBL__91
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__91_INDEX1 ON OBJ_INDEX_DBL__91 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__91_INDEX2 ON OBJ_INDEX_DBL__91 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__92
GO

CREATE TABLE OBJ_INDEX_DBL__92
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__92_INDEX1 ON OBJ_INDEX_DBL__92 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__92_INDEX2 ON OBJ_INDEX_DBL__92 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__93
GO

CREATE TABLE OBJ_INDEX_DBL__93
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__93_INDEX1 ON OBJ_INDEX_DBL__93 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__93_INDEX2 ON OBJ_INDEX_DBL__93 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__94
GO

CREATE TABLE OBJ_INDEX_DBL__94
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__94_INDEX1 ON OBJ_INDEX_DBL__94 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__94_INDEX2 ON OBJ_INDEX_DBL__94 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__95
GO

CREATE TABLE OBJ_INDEX_DBL__95
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__95_INDEX1 ON OBJ_INDEX_DBL__95 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__95_INDEX2 ON OBJ_INDEX_DBL__95 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__96
GO

CREATE TABLE OBJ_INDEX_DBL__96
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__96_INDEX1 ON OBJ_INDEX_DBL__96 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__96_INDEX2 ON OBJ_INDEX_DBL__96 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__97
GO

CREATE TABLE OBJ_INDEX_DBL__97
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__97_INDEX1 ON OBJ_INDEX_DBL__97 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__97_INDEX2 ON OBJ_INDEX_DBL__97 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__98
GO

CREATE TABLE OBJ_INDEX_DBL__98
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__98_INDEX1 ON OBJ_INDEX_DBL__98 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__98_INDEX2 ON OBJ_INDEX_DBL__98 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__99
GO

CREATE TABLE OBJ_INDEX_DBL__99
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__99_INDEX1 ON OBJ_INDEX_DBL__99 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__99_INDEX2 ON OBJ_INDEX_DBL__99 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__100
GO

CREATE TABLE OBJ_INDEX_DBL__100
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__100_INDEX1 ON OBJ_INDEX_DBL__100 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__100_INDEX2 ON OBJ_INDEX_DBL__100 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__101
GO

CREATE TABLE OBJ_INDEX_DBL__101
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__101_INDEX1 ON OBJ_INDEX_DBL__101 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__101_INDEX2 ON OBJ_INDEX_DBL__101 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__102
GO

CREATE TABLE OBJ_INDEX_DBL__102
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__102_INDEX1 ON OBJ_INDEX_DBL__102 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__102_INDEX2 ON OBJ_INDEX_DBL__102 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__103
GO

CREATE TABLE OBJ_INDEX_DBL__103
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__103_INDEX1 ON OBJ_INDEX_DBL__103 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__103_INDEX2 ON OBJ_INDEX_DBL__103 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__104
GO

CREATE TABLE OBJ_INDEX_DBL__104
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__104_INDEX1 ON OBJ_INDEX_DBL__104 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__104_INDEX2 ON OBJ_INDEX_DBL__104 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__105
GO

CREATE TABLE OBJ_INDEX_DBL__105
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__105_INDEX1 ON OBJ_INDEX_DBL__105 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__105_INDEX2 ON OBJ_INDEX_DBL__105 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__106
GO

CREATE TABLE OBJ_INDEX_DBL__106
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__106_INDEX1 ON OBJ_INDEX_DBL__106 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__106_INDEX2 ON OBJ_INDEX_DBL__106 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__107
GO

CREATE TABLE OBJ_INDEX_DBL__107
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__107_INDEX1 ON OBJ_INDEX_DBL__107 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__107_INDEX2 ON OBJ_INDEX_DBL__107 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__108
GO

CREATE TABLE OBJ_INDEX_DBL__108
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__108_INDEX1 ON OBJ_INDEX_DBL__108 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__108_INDEX2 ON OBJ_INDEX_DBL__108 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__109
GO

CREATE TABLE OBJ_INDEX_DBL__109
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__109_INDEX1 ON OBJ_INDEX_DBL__109 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__109_INDEX2 ON OBJ_INDEX_DBL__109 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__110
GO

CREATE TABLE OBJ_INDEX_DBL__110
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__110_INDEX1 ON OBJ_INDEX_DBL__110 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__110_INDEX2 ON OBJ_INDEX_DBL__110 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__111
GO

CREATE TABLE OBJ_INDEX_DBL__111
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__111_INDEX1 ON OBJ_INDEX_DBL__111 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__111_INDEX2 ON OBJ_INDEX_DBL__111 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__112
GO

CREATE TABLE OBJ_INDEX_DBL__112
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__112_INDEX1 ON OBJ_INDEX_DBL__112 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__112_INDEX2 ON OBJ_INDEX_DBL__112 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__113
GO

CREATE TABLE OBJ_INDEX_DBL__113
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__113_INDEX1 ON OBJ_INDEX_DBL__113 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__113_INDEX2 ON OBJ_INDEX_DBL__113 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__114
GO

CREATE TABLE OBJ_INDEX_DBL__114
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__114_INDEX1 ON OBJ_INDEX_DBL__114 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__114_INDEX2 ON OBJ_INDEX_DBL__114 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__115
GO

CREATE TABLE OBJ_INDEX_DBL__115
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__115_INDEX1 ON OBJ_INDEX_DBL__115 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__115_INDEX2 ON OBJ_INDEX_DBL__115 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__116
GO

CREATE TABLE OBJ_INDEX_DBL__116
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__116_INDEX1 ON OBJ_INDEX_DBL__116 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__116_INDEX2 ON OBJ_INDEX_DBL__116 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__117
GO

CREATE TABLE OBJ_INDEX_DBL__117
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__117_INDEX1 ON OBJ_INDEX_DBL__117 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__117_INDEX2 ON OBJ_INDEX_DBL__117 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__118
GO

CREATE TABLE OBJ_INDEX_DBL__118
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__118_INDEX1 ON OBJ_INDEX_DBL__118 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__118_INDEX2 ON OBJ_INDEX_DBL__118 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__119
GO

CREATE TABLE OBJ_INDEX_DBL__119
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__119_INDEX1 ON OBJ_INDEX_DBL__119 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__119_INDEX2 ON OBJ_INDEX_DBL__119 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__120
GO

CREATE TABLE OBJ_INDEX_DBL__120
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__120_INDEX1 ON OBJ_INDEX_DBL__120 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__120_INDEX2 ON OBJ_INDEX_DBL__120 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__121
GO

CREATE TABLE OBJ_INDEX_DBL__121
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__121_INDEX1 ON OBJ_INDEX_DBL__121 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__121_INDEX2 ON OBJ_INDEX_DBL__121 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__122
GO

CREATE TABLE OBJ_INDEX_DBL__122
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__122_INDEX1 ON OBJ_INDEX_DBL__122 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__122_INDEX2 ON OBJ_INDEX_DBL__122 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__123
GO

CREATE TABLE OBJ_INDEX_DBL__123
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__123_INDEX1 ON OBJ_INDEX_DBL__123 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__123_INDEX2 ON OBJ_INDEX_DBL__123 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__124
GO

CREATE TABLE OBJ_INDEX_DBL__124
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__124_INDEX1 ON OBJ_INDEX_DBL__124 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__124_INDEX2 ON OBJ_INDEX_DBL__124 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__125
GO

CREATE TABLE OBJ_INDEX_DBL__125
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__125_INDEX1 ON OBJ_INDEX_DBL__125 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__125_INDEX2 ON OBJ_INDEX_DBL__125 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__126
GO

CREATE TABLE OBJ_INDEX_DBL__126
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__126_INDEX1 ON OBJ_INDEX_DBL__126 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__126_INDEX2 ON OBJ_INDEX_DBL__126 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_INDEX_DBL */
DROP TABLE OBJ_INDEX_DBL__127
GO

CREATE TABLE OBJ_INDEX_DBL__127
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    OBJ_VER NUMERIC(10,0) DEFAULT 0 NOT NULL,
    VAL FLOAT
)
GO

CREATE INDEX OBJ_INDEX_DBL__127_INDEX1 ON OBJ_INDEX_DBL__127 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_INDEX_DBL__127_INDEX2 ON OBJ_INDEX_DBL__127 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
