use mtdb
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR
GO

CREATE TABLE OBJ_UNIQUE_STR
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR_INDEX1 ON OBJ_UNIQUE_STR (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR_INDEX2 ON OBJ_UNIQUE_STR (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__1
GO

CREATE TABLE OBJ_UNIQUE_STR__1
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__1_INDEX1 ON OBJ_UNIQUE_STR__1 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__1_INDEX2 ON OBJ_UNIQUE_STR__1 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__2
GO

CREATE TABLE OBJ_UNIQUE_STR__2
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__2_INDEX1 ON OBJ_UNIQUE_STR__2 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__2_INDEX2 ON OBJ_UNIQUE_STR__2 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__3
GO

CREATE TABLE OBJ_UNIQUE_STR__3
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__3_INDEX1 ON OBJ_UNIQUE_STR__3 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__3_INDEX2 ON OBJ_UNIQUE_STR__3 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__4
GO

CREATE TABLE OBJ_UNIQUE_STR__4
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__4_INDEX1 ON OBJ_UNIQUE_STR__4 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__4_INDEX2 ON OBJ_UNIQUE_STR__4 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__5
GO

CREATE TABLE OBJ_UNIQUE_STR__5
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__5_INDEX1 ON OBJ_UNIQUE_STR__5 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__5_INDEX2 ON OBJ_UNIQUE_STR__5 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__6
GO

CREATE TABLE OBJ_UNIQUE_STR__6
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__6_INDEX1 ON OBJ_UNIQUE_STR__6 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__6_INDEX2 ON OBJ_UNIQUE_STR__6 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__7
GO

CREATE TABLE OBJ_UNIQUE_STR__7
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__7_INDEX1 ON OBJ_UNIQUE_STR__7 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__7_INDEX2 ON OBJ_UNIQUE_STR__7 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__8
GO

CREATE TABLE OBJ_UNIQUE_STR__8
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__8_INDEX1 ON OBJ_UNIQUE_STR__8 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__8_INDEX2 ON OBJ_UNIQUE_STR__8 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__9
GO

CREATE TABLE OBJ_UNIQUE_STR__9
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__9_INDEX1 ON OBJ_UNIQUE_STR__9 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__9_INDEX2 ON OBJ_UNIQUE_STR__9 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__10
GO

CREATE TABLE OBJ_UNIQUE_STR__10
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__10_INDEX1 ON OBJ_UNIQUE_STR__10 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__10_INDEX2 ON OBJ_UNIQUE_STR__10 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__11
GO

CREATE TABLE OBJ_UNIQUE_STR__11
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__11_INDEX1 ON OBJ_UNIQUE_STR__11 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__11_INDEX2 ON OBJ_UNIQUE_STR__11 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__12
GO

CREATE TABLE OBJ_UNIQUE_STR__12
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__12_INDEX1 ON OBJ_UNIQUE_STR__12 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__12_INDEX2 ON OBJ_UNIQUE_STR__12 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__13
GO

CREATE TABLE OBJ_UNIQUE_STR__13
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__13_INDEX1 ON OBJ_UNIQUE_STR__13 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__13_INDEX2 ON OBJ_UNIQUE_STR__13 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__14
GO

CREATE TABLE OBJ_UNIQUE_STR__14
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__14_INDEX1 ON OBJ_UNIQUE_STR__14 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__14_INDEX2 ON OBJ_UNIQUE_STR__14 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__15
GO

CREATE TABLE OBJ_UNIQUE_STR__15
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__15_INDEX1 ON OBJ_UNIQUE_STR__15 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__15_INDEX2 ON OBJ_UNIQUE_STR__15 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__16
GO

CREATE TABLE OBJ_UNIQUE_STR__16
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__16_INDEX1 ON OBJ_UNIQUE_STR__16 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__16_INDEX2 ON OBJ_UNIQUE_STR__16 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__17
GO

CREATE TABLE OBJ_UNIQUE_STR__17
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__17_INDEX1 ON OBJ_UNIQUE_STR__17 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__17_INDEX2 ON OBJ_UNIQUE_STR__17 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__18
GO

CREATE TABLE OBJ_UNIQUE_STR__18
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__18_INDEX1 ON OBJ_UNIQUE_STR__18 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__18_INDEX2 ON OBJ_UNIQUE_STR__18 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__19
GO

CREATE TABLE OBJ_UNIQUE_STR__19
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__19_INDEX1 ON OBJ_UNIQUE_STR__19 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__19_INDEX2 ON OBJ_UNIQUE_STR__19 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__20
GO

CREATE TABLE OBJ_UNIQUE_STR__20
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__20_INDEX1 ON OBJ_UNIQUE_STR__20 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__20_INDEX2 ON OBJ_UNIQUE_STR__20 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__21
GO

CREATE TABLE OBJ_UNIQUE_STR__21
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__21_INDEX1 ON OBJ_UNIQUE_STR__21 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__21_INDEX2 ON OBJ_UNIQUE_STR__21 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__22
GO

CREATE TABLE OBJ_UNIQUE_STR__22
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__22_INDEX1 ON OBJ_UNIQUE_STR__22 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__22_INDEX2 ON OBJ_UNIQUE_STR__22 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__23
GO

CREATE TABLE OBJ_UNIQUE_STR__23
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__23_INDEX1 ON OBJ_UNIQUE_STR__23 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__23_INDEX2 ON OBJ_UNIQUE_STR__23 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__24
GO

CREATE TABLE OBJ_UNIQUE_STR__24
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__24_INDEX1 ON OBJ_UNIQUE_STR__24 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__24_INDEX2 ON OBJ_UNIQUE_STR__24 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__25
GO

CREATE TABLE OBJ_UNIQUE_STR__25
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__25_INDEX1 ON OBJ_UNIQUE_STR__25 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__25_INDEX2 ON OBJ_UNIQUE_STR__25 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__26
GO

CREATE TABLE OBJ_UNIQUE_STR__26
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__26_INDEX1 ON OBJ_UNIQUE_STR__26 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__26_INDEX2 ON OBJ_UNIQUE_STR__26 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__27
GO

CREATE TABLE OBJ_UNIQUE_STR__27
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__27_INDEX1 ON OBJ_UNIQUE_STR__27 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__27_INDEX2 ON OBJ_UNIQUE_STR__27 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__28
GO

CREATE TABLE OBJ_UNIQUE_STR__28
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__28_INDEX1 ON OBJ_UNIQUE_STR__28 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__28_INDEX2 ON OBJ_UNIQUE_STR__28 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__29
GO

CREATE TABLE OBJ_UNIQUE_STR__29
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__29_INDEX1 ON OBJ_UNIQUE_STR__29 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__29_INDEX2 ON OBJ_UNIQUE_STR__29 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__30
GO

CREATE TABLE OBJ_UNIQUE_STR__30
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__30_INDEX1 ON OBJ_UNIQUE_STR__30 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__30_INDEX2 ON OBJ_UNIQUE_STR__30 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__31
GO

CREATE TABLE OBJ_UNIQUE_STR__31
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__31_INDEX1 ON OBJ_UNIQUE_STR__31 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__31_INDEX2 ON OBJ_UNIQUE_STR__31 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__32
GO

CREATE TABLE OBJ_UNIQUE_STR__32
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__32_INDEX1 ON OBJ_UNIQUE_STR__32 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__32_INDEX2 ON OBJ_UNIQUE_STR__32 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__33
GO

CREATE TABLE OBJ_UNIQUE_STR__33
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__33_INDEX1 ON OBJ_UNIQUE_STR__33 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__33_INDEX2 ON OBJ_UNIQUE_STR__33 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__34
GO

CREATE TABLE OBJ_UNIQUE_STR__34
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__34_INDEX1 ON OBJ_UNIQUE_STR__34 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__34_INDEX2 ON OBJ_UNIQUE_STR__34 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__35
GO

CREATE TABLE OBJ_UNIQUE_STR__35
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__35_INDEX1 ON OBJ_UNIQUE_STR__35 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__35_INDEX2 ON OBJ_UNIQUE_STR__35 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__36
GO

CREATE TABLE OBJ_UNIQUE_STR__36
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__36_INDEX1 ON OBJ_UNIQUE_STR__36 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__36_INDEX2 ON OBJ_UNIQUE_STR__36 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__37
GO

CREATE TABLE OBJ_UNIQUE_STR__37
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__37_INDEX1 ON OBJ_UNIQUE_STR__37 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__37_INDEX2 ON OBJ_UNIQUE_STR__37 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__38
GO

CREATE TABLE OBJ_UNIQUE_STR__38
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__38_INDEX1 ON OBJ_UNIQUE_STR__38 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__38_INDEX2 ON OBJ_UNIQUE_STR__38 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__39
GO

CREATE TABLE OBJ_UNIQUE_STR__39
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__39_INDEX1 ON OBJ_UNIQUE_STR__39 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__39_INDEX2 ON OBJ_UNIQUE_STR__39 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__40
GO

CREATE TABLE OBJ_UNIQUE_STR__40
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__40_INDEX1 ON OBJ_UNIQUE_STR__40 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__40_INDEX2 ON OBJ_UNIQUE_STR__40 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__41
GO

CREATE TABLE OBJ_UNIQUE_STR__41
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__41_INDEX1 ON OBJ_UNIQUE_STR__41 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__41_INDEX2 ON OBJ_UNIQUE_STR__41 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__42
GO

CREATE TABLE OBJ_UNIQUE_STR__42
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__42_INDEX1 ON OBJ_UNIQUE_STR__42 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__42_INDEX2 ON OBJ_UNIQUE_STR__42 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__43
GO

CREATE TABLE OBJ_UNIQUE_STR__43
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__43_INDEX1 ON OBJ_UNIQUE_STR__43 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__43_INDEX2 ON OBJ_UNIQUE_STR__43 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__44
GO

CREATE TABLE OBJ_UNIQUE_STR__44
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__44_INDEX1 ON OBJ_UNIQUE_STR__44 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__44_INDEX2 ON OBJ_UNIQUE_STR__44 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__45
GO

CREATE TABLE OBJ_UNIQUE_STR__45
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__45_INDEX1 ON OBJ_UNIQUE_STR__45 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__45_INDEX2 ON OBJ_UNIQUE_STR__45 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__46
GO

CREATE TABLE OBJ_UNIQUE_STR__46
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__46_INDEX1 ON OBJ_UNIQUE_STR__46 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__46_INDEX2 ON OBJ_UNIQUE_STR__46 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__47
GO

CREATE TABLE OBJ_UNIQUE_STR__47
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__47_INDEX1 ON OBJ_UNIQUE_STR__47 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__47_INDEX2 ON OBJ_UNIQUE_STR__47 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__48
GO

CREATE TABLE OBJ_UNIQUE_STR__48
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__48_INDEX1 ON OBJ_UNIQUE_STR__48 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__48_INDEX2 ON OBJ_UNIQUE_STR__48 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__49
GO

CREATE TABLE OBJ_UNIQUE_STR__49
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__49_INDEX1 ON OBJ_UNIQUE_STR__49 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__49_INDEX2 ON OBJ_UNIQUE_STR__49 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__50
GO

CREATE TABLE OBJ_UNIQUE_STR__50
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__50_INDEX1 ON OBJ_UNIQUE_STR__50 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__50_INDEX2 ON OBJ_UNIQUE_STR__50 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__51
GO

CREATE TABLE OBJ_UNIQUE_STR__51
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__51_INDEX1 ON OBJ_UNIQUE_STR__51 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__51_INDEX2 ON OBJ_UNIQUE_STR__51 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__52
GO

CREATE TABLE OBJ_UNIQUE_STR__52
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__52_INDEX1 ON OBJ_UNIQUE_STR__52 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__52_INDEX2 ON OBJ_UNIQUE_STR__52 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__53
GO

CREATE TABLE OBJ_UNIQUE_STR__53
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__53_INDEX1 ON OBJ_UNIQUE_STR__53 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__53_INDEX2 ON OBJ_UNIQUE_STR__53 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__54
GO

CREATE TABLE OBJ_UNIQUE_STR__54
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__54_INDEX1 ON OBJ_UNIQUE_STR__54 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__54_INDEX2 ON OBJ_UNIQUE_STR__54 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__55
GO

CREATE TABLE OBJ_UNIQUE_STR__55
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__55_INDEX1 ON OBJ_UNIQUE_STR__55 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__55_INDEX2 ON OBJ_UNIQUE_STR__55 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__56
GO

CREATE TABLE OBJ_UNIQUE_STR__56
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__56_INDEX1 ON OBJ_UNIQUE_STR__56 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__56_INDEX2 ON OBJ_UNIQUE_STR__56 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__57
GO

CREATE TABLE OBJ_UNIQUE_STR__57
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__57_INDEX1 ON OBJ_UNIQUE_STR__57 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__57_INDEX2 ON OBJ_UNIQUE_STR__57 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__58
GO

CREATE TABLE OBJ_UNIQUE_STR__58
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__58_INDEX1 ON OBJ_UNIQUE_STR__58 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__58_INDEX2 ON OBJ_UNIQUE_STR__58 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__59
GO

CREATE TABLE OBJ_UNIQUE_STR__59
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__59_INDEX1 ON OBJ_UNIQUE_STR__59 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__59_INDEX2 ON OBJ_UNIQUE_STR__59 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__60
GO

CREATE TABLE OBJ_UNIQUE_STR__60
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__60_INDEX1 ON OBJ_UNIQUE_STR__60 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__60_INDEX2 ON OBJ_UNIQUE_STR__60 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__61
GO

CREATE TABLE OBJ_UNIQUE_STR__61
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__61_INDEX1 ON OBJ_UNIQUE_STR__61 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__61_INDEX2 ON OBJ_UNIQUE_STR__61 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__62
GO

CREATE TABLE OBJ_UNIQUE_STR__62
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__62_INDEX1 ON OBJ_UNIQUE_STR__62 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__62_INDEX2 ON OBJ_UNIQUE_STR__62 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__63
GO

CREATE TABLE OBJ_UNIQUE_STR__63
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__63_INDEX1 ON OBJ_UNIQUE_STR__63 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__63_INDEX2 ON OBJ_UNIQUE_STR__63 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__64
GO

CREATE TABLE OBJ_UNIQUE_STR__64
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__64_INDEX1 ON OBJ_UNIQUE_STR__64 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__64_INDEX2 ON OBJ_UNIQUE_STR__64 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__65
GO

CREATE TABLE OBJ_UNIQUE_STR__65
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__65_INDEX1 ON OBJ_UNIQUE_STR__65 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__65_INDEX2 ON OBJ_UNIQUE_STR__65 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__66
GO

CREATE TABLE OBJ_UNIQUE_STR__66
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__66_INDEX1 ON OBJ_UNIQUE_STR__66 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__66_INDEX2 ON OBJ_UNIQUE_STR__66 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__67
GO

CREATE TABLE OBJ_UNIQUE_STR__67
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__67_INDEX1 ON OBJ_UNIQUE_STR__67 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__67_INDEX2 ON OBJ_UNIQUE_STR__67 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__68
GO

CREATE TABLE OBJ_UNIQUE_STR__68
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__68_INDEX1 ON OBJ_UNIQUE_STR__68 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__68_INDEX2 ON OBJ_UNIQUE_STR__68 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__69
GO

CREATE TABLE OBJ_UNIQUE_STR__69
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__69_INDEX1 ON OBJ_UNIQUE_STR__69 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__69_INDEX2 ON OBJ_UNIQUE_STR__69 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__70
GO

CREATE TABLE OBJ_UNIQUE_STR__70
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__70_INDEX1 ON OBJ_UNIQUE_STR__70 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__70_INDEX2 ON OBJ_UNIQUE_STR__70 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__71
GO

CREATE TABLE OBJ_UNIQUE_STR__71
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__71_INDEX1 ON OBJ_UNIQUE_STR__71 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__71_INDEX2 ON OBJ_UNIQUE_STR__71 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__72
GO

CREATE TABLE OBJ_UNIQUE_STR__72
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__72_INDEX1 ON OBJ_UNIQUE_STR__72 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__72_INDEX2 ON OBJ_UNIQUE_STR__72 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__73
GO

CREATE TABLE OBJ_UNIQUE_STR__73
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__73_INDEX1 ON OBJ_UNIQUE_STR__73 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__73_INDEX2 ON OBJ_UNIQUE_STR__73 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__74
GO

CREATE TABLE OBJ_UNIQUE_STR__74
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__74_INDEX1 ON OBJ_UNIQUE_STR__74 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__74_INDEX2 ON OBJ_UNIQUE_STR__74 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__75
GO

CREATE TABLE OBJ_UNIQUE_STR__75
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__75_INDEX1 ON OBJ_UNIQUE_STR__75 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__75_INDEX2 ON OBJ_UNIQUE_STR__75 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__76
GO

CREATE TABLE OBJ_UNIQUE_STR__76
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__76_INDEX1 ON OBJ_UNIQUE_STR__76 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__76_INDEX2 ON OBJ_UNIQUE_STR__76 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__77
GO

CREATE TABLE OBJ_UNIQUE_STR__77
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__77_INDEX1 ON OBJ_UNIQUE_STR__77 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__77_INDEX2 ON OBJ_UNIQUE_STR__77 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__78
GO

CREATE TABLE OBJ_UNIQUE_STR__78
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__78_INDEX1 ON OBJ_UNIQUE_STR__78 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__78_INDEX2 ON OBJ_UNIQUE_STR__78 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__79
GO

CREATE TABLE OBJ_UNIQUE_STR__79
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__79_INDEX1 ON OBJ_UNIQUE_STR__79 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__79_INDEX2 ON OBJ_UNIQUE_STR__79 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__80
GO

CREATE TABLE OBJ_UNIQUE_STR__80
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__80_INDEX1 ON OBJ_UNIQUE_STR__80 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__80_INDEX2 ON OBJ_UNIQUE_STR__80 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__81
GO

CREATE TABLE OBJ_UNIQUE_STR__81
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__81_INDEX1 ON OBJ_UNIQUE_STR__81 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__81_INDEX2 ON OBJ_UNIQUE_STR__81 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__82
GO

CREATE TABLE OBJ_UNIQUE_STR__82
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__82_INDEX1 ON OBJ_UNIQUE_STR__82 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__82_INDEX2 ON OBJ_UNIQUE_STR__82 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__83
GO

CREATE TABLE OBJ_UNIQUE_STR__83
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__83_INDEX1 ON OBJ_UNIQUE_STR__83 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__83_INDEX2 ON OBJ_UNIQUE_STR__83 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__84
GO

CREATE TABLE OBJ_UNIQUE_STR__84
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__84_INDEX1 ON OBJ_UNIQUE_STR__84 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__84_INDEX2 ON OBJ_UNIQUE_STR__84 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__85
GO

CREATE TABLE OBJ_UNIQUE_STR__85
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__85_INDEX1 ON OBJ_UNIQUE_STR__85 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__85_INDEX2 ON OBJ_UNIQUE_STR__85 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__86
GO

CREATE TABLE OBJ_UNIQUE_STR__86
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__86_INDEX1 ON OBJ_UNIQUE_STR__86 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__86_INDEX2 ON OBJ_UNIQUE_STR__86 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__87
GO

CREATE TABLE OBJ_UNIQUE_STR__87
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__87_INDEX1 ON OBJ_UNIQUE_STR__87 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__87_INDEX2 ON OBJ_UNIQUE_STR__87 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__88
GO

CREATE TABLE OBJ_UNIQUE_STR__88
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__88_INDEX1 ON OBJ_UNIQUE_STR__88 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__88_INDEX2 ON OBJ_UNIQUE_STR__88 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__89
GO

CREATE TABLE OBJ_UNIQUE_STR__89
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__89_INDEX1 ON OBJ_UNIQUE_STR__89 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__89_INDEX2 ON OBJ_UNIQUE_STR__89 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__90
GO

CREATE TABLE OBJ_UNIQUE_STR__90
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__90_INDEX1 ON OBJ_UNIQUE_STR__90 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__90_INDEX2 ON OBJ_UNIQUE_STR__90 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__91
GO

CREATE TABLE OBJ_UNIQUE_STR__91
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__91_INDEX1 ON OBJ_UNIQUE_STR__91 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__91_INDEX2 ON OBJ_UNIQUE_STR__91 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__92
GO

CREATE TABLE OBJ_UNIQUE_STR__92
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__92_INDEX1 ON OBJ_UNIQUE_STR__92 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__92_INDEX2 ON OBJ_UNIQUE_STR__92 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__93
GO

CREATE TABLE OBJ_UNIQUE_STR__93
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__93_INDEX1 ON OBJ_UNIQUE_STR__93 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__93_INDEX2 ON OBJ_UNIQUE_STR__93 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__94
GO

CREATE TABLE OBJ_UNIQUE_STR__94
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__94_INDEX1 ON OBJ_UNIQUE_STR__94 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__94_INDEX2 ON OBJ_UNIQUE_STR__94 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__95
GO

CREATE TABLE OBJ_UNIQUE_STR__95
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__95_INDEX1 ON OBJ_UNIQUE_STR__95 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__95_INDEX2 ON OBJ_UNIQUE_STR__95 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__96
GO

CREATE TABLE OBJ_UNIQUE_STR__96
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__96_INDEX1 ON OBJ_UNIQUE_STR__96 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__96_INDEX2 ON OBJ_UNIQUE_STR__96 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__97
GO

CREATE TABLE OBJ_UNIQUE_STR__97
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__97_INDEX1 ON OBJ_UNIQUE_STR__97 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__97_INDEX2 ON OBJ_UNIQUE_STR__97 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__98
GO

CREATE TABLE OBJ_UNIQUE_STR__98
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__98_INDEX1 ON OBJ_UNIQUE_STR__98 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__98_INDEX2 ON OBJ_UNIQUE_STR__98 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__99
GO

CREATE TABLE OBJ_UNIQUE_STR__99
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__99_INDEX1 ON OBJ_UNIQUE_STR__99 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__99_INDEX2 ON OBJ_UNIQUE_STR__99 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__100
GO

CREATE TABLE OBJ_UNIQUE_STR__100
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__100_INDEX1 ON OBJ_UNIQUE_STR__100 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__100_INDEX2 ON OBJ_UNIQUE_STR__100 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__101
GO

CREATE TABLE OBJ_UNIQUE_STR__101
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__101_INDEX1 ON OBJ_UNIQUE_STR__101 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__101_INDEX2 ON OBJ_UNIQUE_STR__101 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__102
GO

CREATE TABLE OBJ_UNIQUE_STR__102
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__102_INDEX1 ON OBJ_UNIQUE_STR__102 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__102_INDEX2 ON OBJ_UNIQUE_STR__102 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__103
GO

CREATE TABLE OBJ_UNIQUE_STR__103
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__103_INDEX1 ON OBJ_UNIQUE_STR__103 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__103_INDEX2 ON OBJ_UNIQUE_STR__103 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__104
GO

CREATE TABLE OBJ_UNIQUE_STR__104
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__104_INDEX1 ON OBJ_UNIQUE_STR__104 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__104_INDEX2 ON OBJ_UNIQUE_STR__104 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__105
GO

CREATE TABLE OBJ_UNIQUE_STR__105
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__105_INDEX1 ON OBJ_UNIQUE_STR__105 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__105_INDEX2 ON OBJ_UNIQUE_STR__105 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__106
GO

CREATE TABLE OBJ_UNIQUE_STR__106
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__106_INDEX1 ON OBJ_UNIQUE_STR__106 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__106_INDEX2 ON OBJ_UNIQUE_STR__106 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__107
GO

CREATE TABLE OBJ_UNIQUE_STR__107
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__107_INDEX1 ON OBJ_UNIQUE_STR__107 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__107_INDEX2 ON OBJ_UNIQUE_STR__107 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__108
GO

CREATE TABLE OBJ_UNIQUE_STR__108
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__108_INDEX1 ON OBJ_UNIQUE_STR__108 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__108_INDEX2 ON OBJ_UNIQUE_STR__108 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__109
GO

CREATE TABLE OBJ_UNIQUE_STR__109
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__109_INDEX1 ON OBJ_UNIQUE_STR__109 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__109_INDEX2 ON OBJ_UNIQUE_STR__109 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__110
GO

CREATE TABLE OBJ_UNIQUE_STR__110
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__110_INDEX1 ON OBJ_UNIQUE_STR__110 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__110_INDEX2 ON OBJ_UNIQUE_STR__110 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__111
GO

CREATE TABLE OBJ_UNIQUE_STR__111
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__111_INDEX1 ON OBJ_UNIQUE_STR__111 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__111_INDEX2 ON OBJ_UNIQUE_STR__111 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__112
GO

CREATE TABLE OBJ_UNIQUE_STR__112
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__112_INDEX1 ON OBJ_UNIQUE_STR__112 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__112_INDEX2 ON OBJ_UNIQUE_STR__112 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__113
GO

CREATE TABLE OBJ_UNIQUE_STR__113
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__113_INDEX1 ON OBJ_UNIQUE_STR__113 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__113_INDEX2 ON OBJ_UNIQUE_STR__113 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__114
GO

CREATE TABLE OBJ_UNIQUE_STR__114
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__114_INDEX1 ON OBJ_UNIQUE_STR__114 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__114_INDEX2 ON OBJ_UNIQUE_STR__114 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__115
GO

CREATE TABLE OBJ_UNIQUE_STR__115
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__115_INDEX1 ON OBJ_UNIQUE_STR__115 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__115_INDEX2 ON OBJ_UNIQUE_STR__115 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__116
GO

CREATE TABLE OBJ_UNIQUE_STR__116
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__116_INDEX1 ON OBJ_UNIQUE_STR__116 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__116_INDEX2 ON OBJ_UNIQUE_STR__116 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__117
GO

CREATE TABLE OBJ_UNIQUE_STR__117
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__117_INDEX1 ON OBJ_UNIQUE_STR__117 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__117_INDEX2 ON OBJ_UNIQUE_STR__117 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__118
GO

CREATE TABLE OBJ_UNIQUE_STR__118
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__118_INDEX1 ON OBJ_UNIQUE_STR__118 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__118_INDEX2 ON OBJ_UNIQUE_STR__118 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__119
GO

CREATE TABLE OBJ_UNIQUE_STR__119
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__119_INDEX1 ON OBJ_UNIQUE_STR__119 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__119_INDEX2 ON OBJ_UNIQUE_STR__119 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__120
GO

CREATE TABLE OBJ_UNIQUE_STR__120
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__120_INDEX1 ON OBJ_UNIQUE_STR__120 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__120_INDEX2 ON OBJ_UNIQUE_STR__120 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__121
GO

CREATE TABLE OBJ_UNIQUE_STR__121
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__121_INDEX1 ON OBJ_UNIQUE_STR__121 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__121_INDEX2 ON OBJ_UNIQUE_STR__121 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__122
GO

CREATE TABLE OBJ_UNIQUE_STR__122
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__122_INDEX1 ON OBJ_UNIQUE_STR__122 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__122_INDEX2 ON OBJ_UNIQUE_STR__122 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__123
GO

CREATE TABLE OBJ_UNIQUE_STR__123
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__123_INDEX1 ON OBJ_UNIQUE_STR__123 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__123_INDEX2 ON OBJ_UNIQUE_STR__123 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__124
GO

CREATE TABLE OBJ_UNIQUE_STR__124
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__124_INDEX1 ON OBJ_UNIQUE_STR__124 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__124_INDEX2 ON OBJ_UNIQUE_STR__124 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__125
GO

CREATE TABLE OBJ_UNIQUE_STR__125
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__125_INDEX1 ON OBJ_UNIQUE_STR__125 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__125_INDEX2 ON OBJ_UNIQUE_STR__125 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__126
GO

CREATE TABLE OBJ_UNIQUE_STR__126
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__126_INDEX1 ON OBJ_UNIQUE_STR__126 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__126_INDEX2 ON OBJ_UNIQUE_STR__126 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO

/* drop/create OBJ_UNIQUE_STR */
DROP TABLE OBJ_UNIQUE_STR__127
GO

CREATE TABLE OBJ_UNIQUE_STR__127
(
    TENANT_ID NUMERIC(7,0) NOT NULL,
    OBJ_DEF_ID VARCHAR(128) NOT NULL,
    COL_NAME VARCHAR(36) NOT NULL,
    OBJ_ID VARCHAR(64) NOT NULL,
    VAL NVARCHAR(365)
)
GO

CREATE UNIQUE INDEX OBJ_UNIQUE_STR__127_INDEX1 ON OBJ_UNIQUE_STR__127 (TENANT_ID, OBJ_DEF_ID, COL_NAME, VAL)
GO
CREATE INDEX OBJ_UNIQUE_STR__127_INDEX2 ON OBJ_UNIQUE_STR__127 (TENANT_ID, OBJ_DEF_ID, OBJ_ID)
GO
