use mtdb
GO

DROP TABLE SCHEMA_CTRL
GO

CREATE TABLE SCHEMA_CTRL
(
    TENANT_ID NUMERIC(7,0),
    OBJ_DEF_ID VARCHAR(128),
    OBJ_DEF_VER NUMERIC(10,0),
    LOCK_STATUS CHAR(1),
    CR_DATA_VER NUMERIC(10,0),
    CONSTRAINT SCHEMA_CTRL_PK PRIMARY KEY (TENANT_ID, OBJ_DEF_ID)
)
GO
