DROP TABLE "COUNTER" CASCADE CONSTRAINT;
CREATE TABLE "COUNTER" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "CNT_NAME" VARCHAR2(128) NOT NULL, 
    "INC_UNIT_KEY" VARCHAR2(128) NOT NULL,
    "CNT_VAL" NUMBER(18,0),
    CONSTRAINT "COUNTER_PK" PRIMARY KEY ("TENANT_ID", "CNT_NAME", "INC_UNIT_KEY") USING INDEX LOCAL
)
PARTITION BY RANGE (TENANT_ID) INTERVAL(1)
(
    PARTITION COUNTER_0 VALUES LESS THAN (1)
)
;
