DROP TABLE "OBJ_BLOB_RB" CASCADE CONSTRAINT;
CREATE TABLE "OBJ_BLOB_RB" 
(
	"TENANT_ID" NUMBER(7,0),
	"RB_ID" NUMBER(16,0),
	"LOB_ID" NUMBER(16,0)
)
PARTITION BY RANGE (TENANT_ID) INTERVAL(1)
(
	PARTITION OBJ_BLOB_RB_0 VALUES LESS THAN (1)
)
;
 
CREATE INDEX "OBJ_BLOB_RB_INDEX1" ON "OBJ_BLOB_RB" ("TENANT_ID", "RB_ID") LOCAL
;
