DROP TABLE "SCHEMA_CTRL" CASCADE CONSTRAINT;
CREATE TABLE "SCHEMA_CTRL" 
(
    "TENANT_ID" NUMBER(7,0),
    "OBJ_DEF_ID" VARCHAR2(128), 
    "OBJ_DEF_VER" NUMBER(10,0),
    "LOCK_STATUS" CHAR(1),
    "CR_DATA_VER" NUMBER(10,0),
    CONSTRAINT "SCHEMA_CTRL_PK" PRIMARY KEY ("TENANT_ID", "OBJ_DEF_ID") USING INDEX LOCAL
)
PARTITION BY RANGE (TENANT_ID) INTERVAL(1)
(
    PARTITION SCHEMA_CTRL_0 VALUES LESS THAN (1)
)
;
