DROP TABLE "T_PASS_HI" CASCADE CONSTRAINT;
CREATE TABLE "T_PASS_HI" 
(
    "TENANT_ID" NUMBER(7) NOT NULL,
    "ACCOUNT_ID" VARCHAR2(128 BYTE) NOT NULL, 
    "PASSWORD" VARCHAR2(128 BYTE) NOT NULL, 
    "SALT" VARCHAR2(64 BYTE), 
    "UP_DATE" TIMESTAMP (3) 
)
PARTITION BY RANGE (TENANT_ID) INTERVAL(1)
(
    PARTITION T_PASS_HI_0 VALUES LESS THAN (1)
)
;

CREATE INDEX "T_PASS_HI_INDEX" ON "T_PASS_HI" ("TENANT_ID", "ACCOUNT_ID") LOCAL
;

