DROP TABLE "CACHE_STORE" CASCADE CONSTRAINTS;
CREATE TABLE "CACHE_STORE" 
(
  "NS" VARCHAR2(256) NOT NULL,
  "C_KEY" VARCHAR2(512) NOT NULL,
  "C_VAL" BLOB,
  "VER" NUMBER(19,0),
  "CRE_TIME" NUMBER(19,0),
  "INV_TIME" NUMBER(19,0),
  "CI_0" VARCHAR2(512),
  "CI_1" VARCHAR2(512),
  "CI_2" VARCHAR2(512),
  CONSTRAINT "CACHE_STORE_PK" PRIMARY KEY ("NS", "C_KEY") USING INDEX
)
;
CREATE INDEX "CACHE_STORE_INDEX0" ON "CACHE_STORE" ("NS", "CI_0");
CREATE INDEX "CACHE_STORE_INDEX1" ON "CACHE_STORE" ("NS", "CI_1");
CREATE INDEX "CACHE_STORE_INDEX2" ON "CACHE_STORE" ("NS", "CI_2");
