DROP TABLE "CRAWL_LOG" CASCADE CONSTRAINT;
CREATE TABLE "CRAWL_LOG"
(
    "TENANT_ID" NUMBER(7,0) NOT NULL,
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL,
    "OBJ_DEF_VER" NUMBER(10,0) NOT NULL,
    "CRE_DATE" TIMESTAMP (3),
    "UP_DATE" TIMESTAMP (3)
);

CREATE INDEX "CRAWL_LOG_INDEX1" ON "CRAWL_LOG" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_DEF_VER");
