DROP TABLE OBJ_BLOB CASCADE CONSTRAINT;
CREATE TABLE "OBJ_BLOB" 
 (	"TENANT_ID" NUMBER(7,0),
	"LOB_ID" NUMBER(16,0),
	"LOB_NAME" VARCHAR2(256),
	"LOB_TYPE" VARCHAR2(256),
	"LOB_STAT" CHAR(1),
	"LOB_DATA_ID" NUMBER(16,0),
	"CRE_DATE" TIMESTAMP (3), 
	"UP_DATE" TIMESTAMP (3), 
	"CRE_USER" VARCHAR2(64), 
	"UP_USER" VARCHAR2(64), 
	"SESS_ID" VARCHAR2(128),
	"OBJ_DEF_ID" VARCHAR2(128),
	"PROP_DEF_ID" VARCHAR2(128),
	"OBJ_ID" VARCHAR2(64),
	"OBJ_VER" NUMBER(10,0)
 )
;
 
CREATE INDEX "OBJ_BLOB_INDEX1" ON "OBJ_BLOB" ("TENANT_ID", "LOB_ID");

DROP SEQUENCE SEQ_LOB_ID;
CREATE SEQUENCE SEQ_LOB_ID MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1;
