DROP TABLE "OBJ_INDEX_DBL" CASCADE CONSTRAINT;
CREATE TABLE "OBJ_INDEX_DBL" 
   (
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
    "VAL" BINARY_DOUBLE
   )
;
 
CREATE INDEX "OBJ_INDEX_DBL_INDEX1" ON "OBJ_INDEX_DBL" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL");
CREATE INDEX "OBJ_INDEX_DBL_INDEX2" ON "OBJ_INDEX_DBL" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID");
