DROP TABLE "TASK_QUEUE_HI" CASCADE CONSTRAINT;
CREATE TABLE "TASK_QUEUE_HI" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL,
    "Q_ID" NUMBER(7,0) NOT NULL,
    "TASK_ID" NUMBER(16,0) NOT NULL,
    "V_TIME" NUMBER(16,0) NOT NULL,
    "STATUS" CHAR(1) NOT NULL,
    "G_KEY" VARCHAR2(128),
    "VW_ID" NUMBER(7,0),
    "EXP_MODE" CHAR(1) NOT NULL,
    "RES_FLG" CHAR(1) NOT NULL,
    "VER" NUMBER(16,0) NOT NULL,
    "UP_DATE" TIMESTAMP (3) NOT NULL,
    "SERVER_ID" VARCHAR2(128),
    "RE_CNT" NUMBER(7,0),
    "CALLABLE" BLOB,
    "RES" BLOB,
    CONSTRAINT "TASK_QUEUE_HI_PK" PRIMARY KEY ("Q_ID", "TENANT_ID", "TASK_ID") USING INDEX 
)
;