DROP TABLE "DELETE_LOG" CASCADE CONSTRAINT;
CREATE TABLE "DELETE_LOG"
(
    "TENANT_ID" NUMBER(7,0) NOT NULL,
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL,
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
    "STATUS" CHAR(1),
    "CRE_DATE" TIMESTAMP (3),
    "UP_DATE" TIMESTAMP (3)
);

