/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS_INDEX1" ON "OBJ_INDEX_TS" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS_INDEX2" ON "OBJ_INDEX_TS" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__1"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__1" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__1_INDEX1" ON "OBJ_INDEX_TS__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__1_INDEX2" ON "OBJ_INDEX_TS__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__2"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__2" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__2_INDEX1" ON "OBJ_INDEX_TS__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__2_INDEX2" ON "OBJ_INDEX_TS__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__3"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__3" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__3_INDEX1" ON "OBJ_INDEX_TS__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__3_INDEX2" ON "OBJ_INDEX_TS__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__4"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__4" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__4_INDEX1" ON "OBJ_INDEX_TS__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__4_INDEX2" ON "OBJ_INDEX_TS__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__5"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__5" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__5_INDEX1" ON "OBJ_INDEX_TS__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__5_INDEX2" ON "OBJ_INDEX_TS__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__6"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__6" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__6_INDEX1" ON "OBJ_INDEX_TS__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__6_INDEX2" ON "OBJ_INDEX_TS__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__7"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__7" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__7_INDEX1" ON "OBJ_INDEX_TS__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__7_INDEX2" ON "OBJ_INDEX_TS__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__8"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__8" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__8_INDEX1" ON "OBJ_INDEX_TS__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__8_INDEX2" ON "OBJ_INDEX_TS__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__9"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__9" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__9_INDEX1" ON "OBJ_INDEX_TS__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__9_INDEX2" ON "OBJ_INDEX_TS__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__10"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__10" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__10_INDEX1" ON "OBJ_INDEX_TS__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__10_INDEX2" ON "OBJ_INDEX_TS__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__11"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__11" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__11_INDEX1" ON "OBJ_INDEX_TS__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__11_INDEX2" ON "OBJ_INDEX_TS__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__12"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__12" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__12_INDEX1" ON "OBJ_INDEX_TS__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__12_INDEX2" ON "OBJ_INDEX_TS__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__13"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__13" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__13_INDEX1" ON "OBJ_INDEX_TS__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__13_INDEX2" ON "OBJ_INDEX_TS__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__14"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__14" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__14_INDEX1" ON "OBJ_INDEX_TS__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__14_INDEX2" ON "OBJ_INDEX_TS__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__15"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__15" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__15_INDEX1" ON "OBJ_INDEX_TS__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__15_INDEX2" ON "OBJ_INDEX_TS__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__16"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__16" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__16_INDEX1" ON "OBJ_INDEX_TS__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__16_INDEX2" ON "OBJ_INDEX_TS__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__17"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__17" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__17_INDEX1" ON "OBJ_INDEX_TS__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__17_INDEX2" ON "OBJ_INDEX_TS__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__18"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__18" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__18_INDEX1" ON "OBJ_INDEX_TS__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__18_INDEX2" ON "OBJ_INDEX_TS__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__19"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__19" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__19_INDEX1" ON "OBJ_INDEX_TS__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__19_INDEX2" ON "OBJ_INDEX_TS__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__20"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__20" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__20_INDEX1" ON "OBJ_INDEX_TS__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__20_INDEX2" ON "OBJ_INDEX_TS__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__21"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__21" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__21_INDEX1" ON "OBJ_INDEX_TS__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__21_INDEX2" ON "OBJ_INDEX_TS__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__22"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__22" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__22_INDEX1" ON "OBJ_INDEX_TS__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__22_INDEX2" ON "OBJ_INDEX_TS__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__23"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__23" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__23_INDEX1" ON "OBJ_INDEX_TS__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__23_INDEX2" ON "OBJ_INDEX_TS__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__24"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__24" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__24_INDEX1" ON "OBJ_INDEX_TS__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__24_INDEX2" ON "OBJ_INDEX_TS__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__25"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__25" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__25_INDEX1" ON "OBJ_INDEX_TS__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__25_INDEX2" ON "OBJ_INDEX_TS__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__26"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__26" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__26_INDEX1" ON "OBJ_INDEX_TS__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__26_INDEX2" ON "OBJ_INDEX_TS__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__27"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__27" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__27_INDEX1" ON "OBJ_INDEX_TS__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__27_INDEX2" ON "OBJ_INDEX_TS__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__28"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__28" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__28_INDEX1" ON "OBJ_INDEX_TS__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__28_INDEX2" ON "OBJ_INDEX_TS__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__29"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__29" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__29_INDEX1" ON "OBJ_INDEX_TS__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__29_INDEX2" ON "OBJ_INDEX_TS__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__30"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__30" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__30_INDEX1" ON "OBJ_INDEX_TS__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__30_INDEX2" ON "OBJ_INDEX_TS__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__31"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__31" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__31_INDEX1" ON "OBJ_INDEX_TS__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__31_INDEX2" ON "OBJ_INDEX_TS__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__32"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__32" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__32_INDEX1" ON "OBJ_INDEX_TS__32" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__32_INDEX2" ON "OBJ_INDEX_TS__32" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__33"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__33" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__33_INDEX1" ON "OBJ_INDEX_TS__33" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__33_INDEX2" ON "OBJ_INDEX_TS__33" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__34"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__34" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__34_INDEX1" ON "OBJ_INDEX_TS__34" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__34_INDEX2" ON "OBJ_INDEX_TS__34" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__35"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__35" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__35_INDEX1" ON "OBJ_INDEX_TS__35" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__35_INDEX2" ON "OBJ_INDEX_TS__35" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__36"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__36" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__36_INDEX1" ON "OBJ_INDEX_TS__36" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__36_INDEX2" ON "OBJ_INDEX_TS__36" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__37"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__37" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__37_INDEX1" ON "OBJ_INDEX_TS__37" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__37_INDEX2" ON "OBJ_INDEX_TS__37" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__38"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__38" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__38_INDEX1" ON "OBJ_INDEX_TS__38" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__38_INDEX2" ON "OBJ_INDEX_TS__38" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__39"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__39" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__39_INDEX1" ON "OBJ_INDEX_TS__39" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__39_INDEX2" ON "OBJ_INDEX_TS__39" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__40"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__40" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__40_INDEX1" ON "OBJ_INDEX_TS__40" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__40_INDEX2" ON "OBJ_INDEX_TS__40" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__41"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__41" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__41_INDEX1" ON "OBJ_INDEX_TS__41" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__41_INDEX2" ON "OBJ_INDEX_TS__41" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__42"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__42" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__42_INDEX1" ON "OBJ_INDEX_TS__42" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__42_INDEX2" ON "OBJ_INDEX_TS__42" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__43"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__43" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__43_INDEX1" ON "OBJ_INDEX_TS__43" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__43_INDEX2" ON "OBJ_INDEX_TS__43" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__44"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__44" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__44_INDEX1" ON "OBJ_INDEX_TS__44" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__44_INDEX2" ON "OBJ_INDEX_TS__44" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__45"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__45" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__45_INDEX1" ON "OBJ_INDEX_TS__45" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__45_INDEX2" ON "OBJ_INDEX_TS__45" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__46"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__46" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__46_INDEX1" ON "OBJ_INDEX_TS__46" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__46_INDEX2" ON "OBJ_INDEX_TS__46" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__47"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__47" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__47_INDEX1" ON "OBJ_INDEX_TS__47" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__47_INDEX2" ON "OBJ_INDEX_TS__47" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__48"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__48" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__48_INDEX1" ON "OBJ_INDEX_TS__48" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__48_INDEX2" ON "OBJ_INDEX_TS__48" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__49"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__49" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__49_INDEX1" ON "OBJ_INDEX_TS__49" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__49_INDEX2" ON "OBJ_INDEX_TS__49" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__50"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__50" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__50_INDEX1" ON "OBJ_INDEX_TS__50" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__50_INDEX2" ON "OBJ_INDEX_TS__50" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__51"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__51" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__51_INDEX1" ON "OBJ_INDEX_TS__51" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__51_INDEX2" ON "OBJ_INDEX_TS__51" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__52"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__52" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__52_INDEX1" ON "OBJ_INDEX_TS__52" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__52_INDEX2" ON "OBJ_INDEX_TS__52" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__53"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__53" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__53_INDEX1" ON "OBJ_INDEX_TS__53" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__53_INDEX2" ON "OBJ_INDEX_TS__53" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__54"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__54" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__54_INDEX1" ON "OBJ_INDEX_TS__54" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__54_INDEX2" ON "OBJ_INDEX_TS__54" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__55"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__55" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__55_INDEX1" ON "OBJ_INDEX_TS__55" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__55_INDEX2" ON "OBJ_INDEX_TS__55" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__56"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__56" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__56_INDEX1" ON "OBJ_INDEX_TS__56" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__56_INDEX2" ON "OBJ_INDEX_TS__56" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__57"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__57" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__57_INDEX1" ON "OBJ_INDEX_TS__57" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__57_INDEX2" ON "OBJ_INDEX_TS__57" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__58"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__58" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__58_INDEX1" ON "OBJ_INDEX_TS__58" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__58_INDEX2" ON "OBJ_INDEX_TS__58" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__59"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__59" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__59_INDEX1" ON "OBJ_INDEX_TS__59" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__59_INDEX2" ON "OBJ_INDEX_TS__59" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__60"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__60" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__60_INDEX1" ON "OBJ_INDEX_TS__60" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__60_INDEX2" ON "OBJ_INDEX_TS__60" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__61"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__61" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__61_INDEX1" ON "OBJ_INDEX_TS__61" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__61_INDEX2" ON "OBJ_INDEX_TS__61" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__62"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__62" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__62_INDEX1" ON "OBJ_INDEX_TS__62" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__62_INDEX2" ON "OBJ_INDEX_TS__62" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__63"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__63" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__63_INDEX1" ON "OBJ_INDEX_TS__63" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__63_INDEX2" ON "OBJ_INDEX_TS__63" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__64"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__64" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__64_INDEX1" ON "OBJ_INDEX_TS__64" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__64_INDEX2" ON "OBJ_INDEX_TS__64" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__65"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__65" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__65_INDEX1" ON "OBJ_INDEX_TS__65" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__65_INDEX2" ON "OBJ_INDEX_TS__65" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__66"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__66" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__66_INDEX1" ON "OBJ_INDEX_TS__66" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__66_INDEX2" ON "OBJ_INDEX_TS__66" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__67"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__67" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__67_INDEX1" ON "OBJ_INDEX_TS__67" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__67_INDEX2" ON "OBJ_INDEX_TS__67" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__68"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__68" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__68_INDEX1" ON "OBJ_INDEX_TS__68" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__68_INDEX2" ON "OBJ_INDEX_TS__68" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__69"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__69" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__69_INDEX1" ON "OBJ_INDEX_TS__69" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__69_INDEX2" ON "OBJ_INDEX_TS__69" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__70"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__70" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__70_INDEX1" ON "OBJ_INDEX_TS__70" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__70_INDEX2" ON "OBJ_INDEX_TS__70" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__71"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__71" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__71_INDEX1" ON "OBJ_INDEX_TS__71" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__71_INDEX2" ON "OBJ_INDEX_TS__71" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__72"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__72" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__72_INDEX1" ON "OBJ_INDEX_TS__72" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__72_INDEX2" ON "OBJ_INDEX_TS__72" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__73"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__73" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__73_INDEX1" ON "OBJ_INDEX_TS__73" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__73_INDEX2" ON "OBJ_INDEX_TS__73" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__74"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__74" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__74_INDEX1" ON "OBJ_INDEX_TS__74" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__74_INDEX2" ON "OBJ_INDEX_TS__74" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__75"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__75" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__75_INDEX1" ON "OBJ_INDEX_TS__75" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__75_INDEX2" ON "OBJ_INDEX_TS__75" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__76"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__76" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__76_INDEX1" ON "OBJ_INDEX_TS__76" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__76_INDEX2" ON "OBJ_INDEX_TS__76" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__77"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__77" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__77_INDEX1" ON "OBJ_INDEX_TS__77" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__77_INDEX2" ON "OBJ_INDEX_TS__77" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__78"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__78" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__78_INDEX1" ON "OBJ_INDEX_TS__78" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__78_INDEX2" ON "OBJ_INDEX_TS__78" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__79"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__79" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__79_INDEX1" ON "OBJ_INDEX_TS__79" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__79_INDEX2" ON "OBJ_INDEX_TS__79" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__80"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__80" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__80_INDEX1" ON "OBJ_INDEX_TS__80" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__80_INDEX2" ON "OBJ_INDEX_TS__80" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__81"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__81" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__81_INDEX1" ON "OBJ_INDEX_TS__81" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__81_INDEX2" ON "OBJ_INDEX_TS__81" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__82"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__82" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__82_INDEX1" ON "OBJ_INDEX_TS__82" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__82_INDEX2" ON "OBJ_INDEX_TS__82" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__83"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__83" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__83_INDEX1" ON "OBJ_INDEX_TS__83" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__83_INDEX2" ON "OBJ_INDEX_TS__83" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__84"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__84" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__84_INDEX1" ON "OBJ_INDEX_TS__84" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__84_INDEX2" ON "OBJ_INDEX_TS__84" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__85"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__85" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__85_INDEX1" ON "OBJ_INDEX_TS__85" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__85_INDEX2" ON "OBJ_INDEX_TS__85" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__86"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__86" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__86_INDEX1" ON "OBJ_INDEX_TS__86" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__86_INDEX2" ON "OBJ_INDEX_TS__86" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__87"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__87" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__87_INDEX1" ON "OBJ_INDEX_TS__87" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__87_INDEX2" ON "OBJ_INDEX_TS__87" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__88"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__88" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__88_INDEX1" ON "OBJ_INDEX_TS__88" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__88_INDEX2" ON "OBJ_INDEX_TS__88" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__89"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__89" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__89_INDEX1" ON "OBJ_INDEX_TS__89" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__89_INDEX2" ON "OBJ_INDEX_TS__89" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__90"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__90" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__90_INDEX1" ON "OBJ_INDEX_TS__90" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__90_INDEX2" ON "OBJ_INDEX_TS__90" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__91"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__91" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__91_INDEX1" ON "OBJ_INDEX_TS__91" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__91_INDEX2" ON "OBJ_INDEX_TS__91" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__92"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__92" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__92_INDEX1" ON "OBJ_INDEX_TS__92" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__92_INDEX2" ON "OBJ_INDEX_TS__92" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__93"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__93" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__93_INDEX1" ON "OBJ_INDEX_TS__93" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__93_INDEX2" ON "OBJ_INDEX_TS__93" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__94"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__94" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__94_INDEX1" ON "OBJ_INDEX_TS__94" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__94_INDEX2" ON "OBJ_INDEX_TS__94" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__95"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__95" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__95_INDEX1" ON "OBJ_INDEX_TS__95" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__95_INDEX2" ON "OBJ_INDEX_TS__95" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__96"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__96" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__96_INDEX1" ON "OBJ_INDEX_TS__96" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__96_INDEX2" ON "OBJ_INDEX_TS__96" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__97"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__97" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__97_INDEX1" ON "OBJ_INDEX_TS__97" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__97_INDEX2" ON "OBJ_INDEX_TS__97" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__98"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__98" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__98_INDEX1" ON "OBJ_INDEX_TS__98" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__98_INDEX2" ON "OBJ_INDEX_TS__98" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__99"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__99" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__99_INDEX1" ON "OBJ_INDEX_TS__99" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__99_INDEX2" ON "OBJ_INDEX_TS__99" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__100"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__100" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__100_INDEX1" ON "OBJ_INDEX_TS__100" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__100_INDEX2" ON "OBJ_INDEX_TS__100" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__101"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__101" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__101_INDEX1" ON "OBJ_INDEX_TS__101" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__101_INDEX2" ON "OBJ_INDEX_TS__101" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__102"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__102" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__102_INDEX1" ON "OBJ_INDEX_TS__102" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__102_INDEX2" ON "OBJ_INDEX_TS__102" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__103"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__103" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__103_INDEX1" ON "OBJ_INDEX_TS__103" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__103_INDEX2" ON "OBJ_INDEX_TS__103" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__104"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__104" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__104_INDEX1" ON "OBJ_INDEX_TS__104" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__104_INDEX2" ON "OBJ_INDEX_TS__104" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__105"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__105" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__105_INDEX1" ON "OBJ_INDEX_TS__105" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__105_INDEX2" ON "OBJ_INDEX_TS__105" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__106"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__106" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__106_INDEX1" ON "OBJ_INDEX_TS__106" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__106_INDEX2" ON "OBJ_INDEX_TS__106" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__107"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__107" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__107_INDEX1" ON "OBJ_INDEX_TS__107" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__107_INDEX2" ON "OBJ_INDEX_TS__107" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__108"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__108" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__108_INDEX1" ON "OBJ_INDEX_TS__108" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__108_INDEX2" ON "OBJ_INDEX_TS__108" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__109"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__109" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__109_INDEX1" ON "OBJ_INDEX_TS__109" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__109_INDEX2" ON "OBJ_INDEX_TS__109" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__110"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__110" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__110_INDEX1" ON "OBJ_INDEX_TS__110" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__110_INDEX2" ON "OBJ_INDEX_TS__110" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__111"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__111" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__111_INDEX1" ON "OBJ_INDEX_TS__111" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__111_INDEX2" ON "OBJ_INDEX_TS__111" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__112"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__112" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__112_INDEX1" ON "OBJ_INDEX_TS__112" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__112_INDEX2" ON "OBJ_INDEX_TS__112" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__113"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__113" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__113_INDEX1" ON "OBJ_INDEX_TS__113" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__113_INDEX2" ON "OBJ_INDEX_TS__113" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__114"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__114" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__114_INDEX1" ON "OBJ_INDEX_TS__114" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__114_INDEX2" ON "OBJ_INDEX_TS__114" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__115"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__115" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__115_INDEX1" ON "OBJ_INDEX_TS__115" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__115_INDEX2" ON "OBJ_INDEX_TS__115" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__116"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__116" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__116_INDEX1" ON "OBJ_INDEX_TS__116" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__116_INDEX2" ON "OBJ_INDEX_TS__116" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__117"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__117" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__117_INDEX1" ON "OBJ_INDEX_TS__117" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__117_INDEX2" ON "OBJ_INDEX_TS__117" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__118"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__118" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__118_INDEX1" ON "OBJ_INDEX_TS__118" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__118_INDEX2" ON "OBJ_INDEX_TS__118" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__119"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__119" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__119_INDEX1" ON "OBJ_INDEX_TS__119" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__119_INDEX2" ON "OBJ_INDEX_TS__119" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__120"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__120" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__120_INDEX1" ON "OBJ_INDEX_TS__120" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__120_INDEX2" ON "OBJ_INDEX_TS__120" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__121"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__121" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__121_INDEX1" ON "OBJ_INDEX_TS__121" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__121_INDEX2" ON "OBJ_INDEX_TS__121" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__122"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__122" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__122_INDEX1" ON "OBJ_INDEX_TS__122" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__122_INDEX2" ON "OBJ_INDEX_TS__122" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__123"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__123" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__123_INDEX1" ON "OBJ_INDEX_TS__123" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__123_INDEX2" ON "OBJ_INDEX_TS__123" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__124"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__124" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__124_INDEX1" ON "OBJ_INDEX_TS__124" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__124_INDEX2" ON "OBJ_INDEX_TS__124" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__125"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__125" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__125_INDEX1" ON "OBJ_INDEX_TS__125" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__125_INDEX2" ON "OBJ_INDEX_TS__125" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__126"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__126" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__126_INDEX1" ON "OBJ_INDEX_TS__126" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__126_INDEX2" ON "OBJ_INDEX_TS__126" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__127"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__127" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__127_INDEX1" ON "OBJ_INDEX_TS__127" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__127_INDEX2" ON "OBJ_INDEX_TS__127" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;
