/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE_INDEX1" ON "OBJ_UNIQUE_DATE" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE_INDEX2" ON "OBJ_UNIQUE_DATE" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__1" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__1" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__1_INDEX1" ON "OBJ_UNIQUE_DATE__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__1_INDEX2" ON "OBJ_UNIQUE_DATE__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__2" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__2" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__2_INDEX1" ON "OBJ_UNIQUE_DATE__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__2_INDEX2" ON "OBJ_UNIQUE_DATE__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__3" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__3" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__3_INDEX1" ON "OBJ_UNIQUE_DATE__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__3_INDEX2" ON "OBJ_UNIQUE_DATE__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__4" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__4" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__4_INDEX1" ON "OBJ_UNIQUE_DATE__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__4_INDEX2" ON "OBJ_UNIQUE_DATE__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__5" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__5" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__5_INDEX1" ON "OBJ_UNIQUE_DATE__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__5_INDEX2" ON "OBJ_UNIQUE_DATE__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__6" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__6" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__6_INDEX1" ON "OBJ_UNIQUE_DATE__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__6_INDEX2" ON "OBJ_UNIQUE_DATE__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__7" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__7" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__7_INDEX1" ON "OBJ_UNIQUE_DATE__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__7_INDEX2" ON "OBJ_UNIQUE_DATE__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__8" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__8" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__8_INDEX1" ON "OBJ_UNIQUE_DATE__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__8_INDEX2" ON "OBJ_UNIQUE_DATE__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__9" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__9" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__9_INDEX1" ON "OBJ_UNIQUE_DATE__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__9_INDEX2" ON "OBJ_UNIQUE_DATE__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__10" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__10" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__10_INDEX1" ON "OBJ_UNIQUE_DATE__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__10_INDEX2" ON "OBJ_UNIQUE_DATE__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__11" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__11" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__11_INDEX1" ON "OBJ_UNIQUE_DATE__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__11_INDEX2" ON "OBJ_UNIQUE_DATE__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__12" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__12" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__12_INDEX1" ON "OBJ_UNIQUE_DATE__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__12_INDEX2" ON "OBJ_UNIQUE_DATE__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__13" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__13" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__13_INDEX1" ON "OBJ_UNIQUE_DATE__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__13_INDEX2" ON "OBJ_UNIQUE_DATE__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__14" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__14" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__14_INDEX1" ON "OBJ_UNIQUE_DATE__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__14_INDEX2" ON "OBJ_UNIQUE_DATE__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__15" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__15" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__15_INDEX1" ON "OBJ_UNIQUE_DATE__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__15_INDEX2" ON "OBJ_UNIQUE_DATE__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__16" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__16" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__16_INDEX1" ON "OBJ_UNIQUE_DATE__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__16_INDEX2" ON "OBJ_UNIQUE_DATE__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__17" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__17" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__17_INDEX1" ON "OBJ_UNIQUE_DATE__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__17_INDEX2" ON "OBJ_UNIQUE_DATE__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__18" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__18" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__18_INDEX1" ON "OBJ_UNIQUE_DATE__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__18_INDEX2" ON "OBJ_UNIQUE_DATE__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__19" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__19" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__19_INDEX1" ON "OBJ_UNIQUE_DATE__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__19_INDEX2" ON "OBJ_UNIQUE_DATE__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__20" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__20" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__20_INDEX1" ON "OBJ_UNIQUE_DATE__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__20_INDEX2" ON "OBJ_UNIQUE_DATE__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__21" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__21" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__21_INDEX1" ON "OBJ_UNIQUE_DATE__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__21_INDEX2" ON "OBJ_UNIQUE_DATE__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__22" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__22" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__22_INDEX1" ON "OBJ_UNIQUE_DATE__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__22_INDEX2" ON "OBJ_UNIQUE_DATE__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__23" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__23" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__23_INDEX1" ON "OBJ_UNIQUE_DATE__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__23_INDEX2" ON "OBJ_UNIQUE_DATE__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__24" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__24" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__24_INDEX1" ON "OBJ_UNIQUE_DATE__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__24_INDEX2" ON "OBJ_UNIQUE_DATE__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__25" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__25" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__25_INDEX1" ON "OBJ_UNIQUE_DATE__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__25_INDEX2" ON "OBJ_UNIQUE_DATE__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__26" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__26" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__26_INDEX1" ON "OBJ_UNIQUE_DATE__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__26_INDEX2" ON "OBJ_UNIQUE_DATE__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__27" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__27" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__27_INDEX1" ON "OBJ_UNIQUE_DATE__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__27_INDEX2" ON "OBJ_UNIQUE_DATE__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__28" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__28" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__28_INDEX1" ON "OBJ_UNIQUE_DATE__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__28_INDEX2" ON "OBJ_UNIQUE_DATE__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__29" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__29" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__29_INDEX1" ON "OBJ_UNIQUE_DATE__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__29_INDEX2" ON "OBJ_UNIQUE_DATE__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__30" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__30" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__30_INDEX1" ON "OBJ_UNIQUE_DATE__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__30_INDEX2" ON "OBJ_UNIQUE_DATE__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__31" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__31" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__31_INDEX1" ON "OBJ_UNIQUE_DATE__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__31_INDEX2" ON "OBJ_UNIQUE_DATE__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__32" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__32" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__32_INDEX1" ON "OBJ_UNIQUE_DATE__32" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__32_INDEX2" ON "OBJ_UNIQUE_DATE__32" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__33" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__33" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__33_INDEX1" ON "OBJ_UNIQUE_DATE__33" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__33_INDEX2" ON "OBJ_UNIQUE_DATE__33" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__34" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__34" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__34_INDEX1" ON "OBJ_UNIQUE_DATE__34" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__34_INDEX2" ON "OBJ_UNIQUE_DATE__34" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__35" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__35" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__35_INDEX1" ON "OBJ_UNIQUE_DATE__35" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__35_INDEX2" ON "OBJ_UNIQUE_DATE__35" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__36" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__36" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__36_INDEX1" ON "OBJ_UNIQUE_DATE__36" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__36_INDEX2" ON "OBJ_UNIQUE_DATE__36" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__37" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__37" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__37_INDEX1" ON "OBJ_UNIQUE_DATE__37" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__37_INDEX2" ON "OBJ_UNIQUE_DATE__37" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__38" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__38" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__38_INDEX1" ON "OBJ_UNIQUE_DATE__38" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__38_INDEX2" ON "OBJ_UNIQUE_DATE__38" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__39" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__39" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__39_INDEX1" ON "OBJ_UNIQUE_DATE__39" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__39_INDEX2" ON "OBJ_UNIQUE_DATE__39" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__40" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__40" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__40_INDEX1" ON "OBJ_UNIQUE_DATE__40" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__40_INDEX2" ON "OBJ_UNIQUE_DATE__40" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__41" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__41" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__41_INDEX1" ON "OBJ_UNIQUE_DATE__41" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__41_INDEX2" ON "OBJ_UNIQUE_DATE__41" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__42" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__42" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__42_INDEX1" ON "OBJ_UNIQUE_DATE__42" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__42_INDEX2" ON "OBJ_UNIQUE_DATE__42" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__43" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__43" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__43_INDEX1" ON "OBJ_UNIQUE_DATE__43" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__43_INDEX2" ON "OBJ_UNIQUE_DATE__43" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__44" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__44" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__44_INDEX1" ON "OBJ_UNIQUE_DATE__44" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__44_INDEX2" ON "OBJ_UNIQUE_DATE__44" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__45" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__45" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__45_INDEX1" ON "OBJ_UNIQUE_DATE__45" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__45_INDEX2" ON "OBJ_UNIQUE_DATE__45" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__46" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__46" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__46_INDEX1" ON "OBJ_UNIQUE_DATE__46" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__46_INDEX2" ON "OBJ_UNIQUE_DATE__46" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__47" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__47" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__47_INDEX1" ON "OBJ_UNIQUE_DATE__47" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__47_INDEX2" ON "OBJ_UNIQUE_DATE__47" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__48" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__48" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__48_INDEX1" ON "OBJ_UNIQUE_DATE__48" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__48_INDEX2" ON "OBJ_UNIQUE_DATE__48" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__49" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__49" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__49_INDEX1" ON "OBJ_UNIQUE_DATE__49" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__49_INDEX2" ON "OBJ_UNIQUE_DATE__49" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__50" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__50" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__50_INDEX1" ON "OBJ_UNIQUE_DATE__50" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__50_INDEX2" ON "OBJ_UNIQUE_DATE__50" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__51" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__51" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__51_INDEX1" ON "OBJ_UNIQUE_DATE__51" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__51_INDEX2" ON "OBJ_UNIQUE_DATE__51" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__52" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__52" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__52_INDEX1" ON "OBJ_UNIQUE_DATE__52" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__52_INDEX2" ON "OBJ_UNIQUE_DATE__52" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__53" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__53" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__53_INDEX1" ON "OBJ_UNIQUE_DATE__53" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__53_INDEX2" ON "OBJ_UNIQUE_DATE__53" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__54" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__54" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__54_INDEX1" ON "OBJ_UNIQUE_DATE__54" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__54_INDEX2" ON "OBJ_UNIQUE_DATE__54" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__55" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__55" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__55_INDEX1" ON "OBJ_UNIQUE_DATE__55" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__55_INDEX2" ON "OBJ_UNIQUE_DATE__55" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__56" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__56" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__56_INDEX1" ON "OBJ_UNIQUE_DATE__56" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__56_INDEX2" ON "OBJ_UNIQUE_DATE__56" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__57" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__57" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__57_INDEX1" ON "OBJ_UNIQUE_DATE__57" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__57_INDEX2" ON "OBJ_UNIQUE_DATE__57" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__58" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__58" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__58_INDEX1" ON "OBJ_UNIQUE_DATE__58" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__58_INDEX2" ON "OBJ_UNIQUE_DATE__58" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__59" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__59" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__59_INDEX1" ON "OBJ_UNIQUE_DATE__59" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__59_INDEX2" ON "OBJ_UNIQUE_DATE__59" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__60" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__60" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__60_INDEX1" ON "OBJ_UNIQUE_DATE__60" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__60_INDEX2" ON "OBJ_UNIQUE_DATE__60" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__61" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__61" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__61_INDEX1" ON "OBJ_UNIQUE_DATE__61" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__61_INDEX2" ON "OBJ_UNIQUE_DATE__61" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__62" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__62" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__62_INDEX1" ON "OBJ_UNIQUE_DATE__62" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__62_INDEX2" ON "OBJ_UNIQUE_DATE__62" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__63" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__63" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__63_INDEX1" ON "OBJ_UNIQUE_DATE__63" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__63_INDEX2" ON "OBJ_UNIQUE_DATE__63" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__64" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__64" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__64_INDEX1" ON "OBJ_UNIQUE_DATE__64" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__64_INDEX2" ON "OBJ_UNIQUE_DATE__64" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__65" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__65" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__65_INDEX1" ON "OBJ_UNIQUE_DATE__65" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__65_INDEX2" ON "OBJ_UNIQUE_DATE__65" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__66" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__66" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__66_INDEX1" ON "OBJ_UNIQUE_DATE__66" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__66_INDEX2" ON "OBJ_UNIQUE_DATE__66" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__67" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__67" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__67_INDEX1" ON "OBJ_UNIQUE_DATE__67" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__67_INDEX2" ON "OBJ_UNIQUE_DATE__67" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__68" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__68" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__68_INDEX1" ON "OBJ_UNIQUE_DATE__68" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__68_INDEX2" ON "OBJ_UNIQUE_DATE__68" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__69" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__69" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__69_INDEX1" ON "OBJ_UNIQUE_DATE__69" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__69_INDEX2" ON "OBJ_UNIQUE_DATE__69" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__70" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__70" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__70_INDEX1" ON "OBJ_UNIQUE_DATE__70" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__70_INDEX2" ON "OBJ_UNIQUE_DATE__70" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__71" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__71" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__71_INDEX1" ON "OBJ_UNIQUE_DATE__71" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__71_INDEX2" ON "OBJ_UNIQUE_DATE__71" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__72" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__72" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__72_INDEX1" ON "OBJ_UNIQUE_DATE__72" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__72_INDEX2" ON "OBJ_UNIQUE_DATE__72" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__73" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__73" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__73_INDEX1" ON "OBJ_UNIQUE_DATE__73" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__73_INDEX2" ON "OBJ_UNIQUE_DATE__73" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__74" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__74" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__74_INDEX1" ON "OBJ_UNIQUE_DATE__74" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__74_INDEX2" ON "OBJ_UNIQUE_DATE__74" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__75" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__75" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__75_INDEX1" ON "OBJ_UNIQUE_DATE__75" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__75_INDEX2" ON "OBJ_UNIQUE_DATE__75" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__76" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__76" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__76_INDEX1" ON "OBJ_UNIQUE_DATE__76" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__76_INDEX2" ON "OBJ_UNIQUE_DATE__76" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__77" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__77" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__77_INDEX1" ON "OBJ_UNIQUE_DATE__77" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__77_INDEX2" ON "OBJ_UNIQUE_DATE__77" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__78" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__78" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__78_INDEX1" ON "OBJ_UNIQUE_DATE__78" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__78_INDEX2" ON "OBJ_UNIQUE_DATE__78" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__79" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__79" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__79_INDEX1" ON "OBJ_UNIQUE_DATE__79" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__79_INDEX2" ON "OBJ_UNIQUE_DATE__79" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__80" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__80" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__80_INDEX1" ON "OBJ_UNIQUE_DATE__80" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__80_INDEX2" ON "OBJ_UNIQUE_DATE__80" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__81" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__81" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__81_INDEX1" ON "OBJ_UNIQUE_DATE__81" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__81_INDEX2" ON "OBJ_UNIQUE_DATE__81" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__82" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__82" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__82_INDEX1" ON "OBJ_UNIQUE_DATE__82" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__82_INDEX2" ON "OBJ_UNIQUE_DATE__82" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__83" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__83" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__83_INDEX1" ON "OBJ_UNIQUE_DATE__83" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__83_INDEX2" ON "OBJ_UNIQUE_DATE__83" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__84" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__84" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__84_INDEX1" ON "OBJ_UNIQUE_DATE__84" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__84_INDEX2" ON "OBJ_UNIQUE_DATE__84" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__85" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__85" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__85_INDEX1" ON "OBJ_UNIQUE_DATE__85" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__85_INDEX2" ON "OBJ_UNIQUE_DATE__85" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__86" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__86" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__86_INDEX1" ON "OBJ_UNIQUE_DATE__86" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__86_INDEX2" ON "OBJ_UNIQUE_DATE__86" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__87" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__87" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__87_INDEX1" ON "OBJ_UNIQUE_DATE__87" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__87_INDEX2" ON "OBJ_UNIQUE_DATE__87" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__88" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__88" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__88_INDEX1" ON "OBJ_UNIQUE_DATE__88" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__88_INDEX2" ON "OBJ_UNIQUE_DATE__88" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__89" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__89" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__89_INDEX1" ON "OBJ_UNIQUE_DATE__89" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__89_INDEX2" ON "OBJ_UNIQUE_DATE__89" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__90" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__90" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__90_INDEX1" ON "OBJ_UNIQUE_DATE__90" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__90_INDEX2" ON "OBJ_UNIQUE_DATE__90" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__91" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__91" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__91_INDEX1" ON "OBJ_UNIQUE_DATE__91" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__91_INDEX2" ON "OBJ_UNIQUE_DATE__91" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__92" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__92" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__92_INDEX1" ON "OBJ_UNIQUE_DATE__92" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__92_INDEX2" ON "OBJ_UNIQUE_DATE__92" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__93" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__93" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__93_INDEX1" ON "OBJ_UNIQUE_DATE__93" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__93_INDEX2" ON "OBJ_UNIQUE_DATE__93" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__94" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__94" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__94_INDEX1" ON "OBJ_UNIQUE_DATE__94" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__94_INDEX2" ON "OBJ_UNIQUE_DATE__94" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__95" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__95" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__95_INDEX1" ON "OBJ_UNIQUE_DATE__95" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__95_INDEX2" ON "OBJ_UNIQUE_DATE__95" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__96" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__96" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__96_INDEX1" ON "OBJ_UNIQUE_DATE__96" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__96_INDEX2" ON "OBJ_UNIQUE_DATE__96" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__97" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__97" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__97_INDEX1" ON "OBJ_UNIQUE_DATE__97" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__97_INDEX2" ON "OBJ_UNIQUE_DATE__97" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__98" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__98" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__98_INDEX1" ON "OBJ_UNIQUE_DATE__98" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__98_INDEX2" ON "OBJ_UNIQUE_DATE__98" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__99" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__99" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__99_INDEX1" ON "OBJ_UNIQUE_DATE__99" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__99_INDEX2" ON "OBJ_UNIQUE_DATE__99" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__100" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__100" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__100_INDEX1" ON "OBJ_UNIQUE_DATE__100" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__100_INDEX2" ON "OBJ_UNIQUE_DATE__100" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__101" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__101" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__101_INDEX1" ON "OBJ_UNIQUE_DATE__101" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__101_INDEX2" ON "OBJ_UNIQUE_DATE__101" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__102" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__102" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__102_INDEX1" ON "OBJ_UNIQUE_DATE__102" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__102_INDEX2" ON "OBJ_UNIQUE_DATE__102" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__103" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__103" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__103_INDEX1" ON "OBJ_UNIQUE_DATE__103" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__103_INDEX2" ON "OBJ_UNIQUE_DATE__103" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__104" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__104" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__104_INDEX1" ON "OBJ_UNIQUE_DATE__104" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__104_INDEX2" ON "OBJ_UNIQUE_DATE__104" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__105" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__105" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__105_INDEX1" ON "OBJ_UNIQUE_DATE__105" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__105_INDEX2" ON "OBJ_UNIQUE_DATE__105" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__106" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__106" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__106_INDEX1" ON "OBJ_UNIQUE_DATE__106" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__106_INDEX2" ON "OBJ_UNIQUE_DATE__106" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__107" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__107" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__107_INDEX1" ON "OBJ_UNIQUE_DATE__107" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__107_INDEX2" ON "OBJ_UNIQUE_DATE__107" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__108" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__108" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__108_INDEX1" ON "OBJ_UNIQUE_DATE__108" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__108_INDEX2" ON "OBJ_UNIQUE_DATE__108" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__109" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__109" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__109_INDEX1" ON "OBJ_UNIQUE_DATE__109" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__109_INDEX2" ON "OBJ_UNIQUE_DATE__109" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__110" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__110" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__110_INDEX1" ON "OBJ_UNIQUE_DATE__110" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__110_INDEX2" ON "OBJ_UNIQUE_DATE__110" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__111" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__111" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__111_INDEX1" ON "OBJ_UNIQUE_DATE__111" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__111_INDEX2" ON "OBJ_UNIQUE_DATE__111" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__112" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__112" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__112_INDEX1" ON "OBJ_UNIQUE_DATE__112" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__112_INDEX2" ON "OBJ_UNIQUE_DATE__112" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__113" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__113" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__113_INDEX1" ON "OBJ_UNIQUE_DATE__113" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__113_INDEX2" ON "OBJ_UNIQUE_DATE__113" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__114" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__114" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__114_INDEX1" ON "OBJ_UNIQUE_DATE__114" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__114_INDEX2" ON "OBJ_UNIQUE_DATE__114" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__115" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__115" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__115_INDEX1" ON "OBJ_UNIQUE_DATE__115" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__115_INDEX2" ON "OBJ_UNIQUE_DATE__115" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__116" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__116" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__116_INDEX1" ON "OBJ_UNIQUE_DATE__116" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__116_INDEX2" ON "OBJ_UNIQUE_DATE__116" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__117" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__117" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__117_INDEX1" ON "OBJ_UNIQUE_DATE__117" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__117_INDEX2" ON "OBJ_UNIQUE_DATE__117" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__118" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__118" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__118_INDEX1" ON "OBJ_UNIQUE_DATE__118" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__118_INDEX2" ON "OBJ_UNIQUE_DATE__118" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__119" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__119" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__119_INDEX1" ON "OBJ_UNIQUE_DATE__119" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__119_INDEX2" ON "OBJ_UNIQUE_DATE__119" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__120" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__120" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__120_INDEX1" ON "OBJ_UNIQUE_DATE__120" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__120_INDEX2" ON "OBJ_UNIQUE_DATE__120" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__121" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__121" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__121_INDEX1" ON "OBJ_UNIQUE_DATE__121" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__121_INDEX2" ON "OBJ_UNIQUE_DATE__121" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__122" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__122" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__122_INDEX1" ON "OBJ_UNIQUE_DATE__122" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__122_INDEX2" ON "OBJ_UNIQUE_DATE__122" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__123" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__123" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__123_INDEX1" ON "OBJ_UNIQUE_DATE__123" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__123_INDEX2" ON "OBJ_UNIQUE_DATE__123" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__124" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__124" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__124_INDEX1" ON "OBJ_UNIQUE_DATE__124" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__124_INDEX2" ON "OBJ_UNIQUE_DATE__124" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__125" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__125" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__125_INDEX1" ON "OBJ_UNIQUE_DATE__125" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__125_INDEX2" ON "OBJ_UNIQUE_DATE__125" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__126" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__126" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__126_INDEX1" ON "OBJ_UNIQUE_DATE__126" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__126_INDEX2" ON "OBJ_UNIQUE_DATE__126" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DATE */
DROP TABLE "OBJ_UNIQUE_DATE__127" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DATE__127" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" DATE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DATE__127_INDEX1" ON "OBJ_UNIQUE_DATE__127" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DATE__127_INDEX2" ON "OBJ_UNIQUE_DATE__127" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;
