/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL_INDEX1" ON "OBJ_UNIQUE_DBL" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL_INDEX2" ON "OBJ_UNIQUE_DBL" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__1" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__1" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__1_INDEX1" ON "OBJ_UNIQUE_DBL__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__1_INDEX2" ON "OBJ_UNIQUE_DBL__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__2" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__2" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__2_INDEX1" ON "OBJ_UNIQUE_DBL__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__2_INDEX2" ON "OBJ_UNIQUE_DBL__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__3" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__3" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__3_INDEX1" ON "OBJ_UNIQUE_DBL__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__3_INDEX2" ON "OBJ_UNIQUE_DBL__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__4" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__4" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__4_INDEX1" ON "OBJ_UNIQUE_DBL__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__4_INDEX2" ON "OBJ_UNIQUE_DBL__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__5" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__5" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__5_INDEX1" ON "OBJ_UNIQUE_DBL__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__5_INDEX2" ON "OBJ_UNIQUE_DBL__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__6" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__6" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__6_INDEX1" ON "OBJ_UNIQUE_DBL__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__6_INDEX2" ON "OBJ_UNIQUE_DBL__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__7" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__7" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__7_INDEX1" ON "OBJ_UNIQUE_DBL__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__7_INDEX2" ON "OBJ_UNIQUE_DBL__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__8" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__8" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__8_INDEX1" ON "OBJ_UNIQUE_DBL__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__8_INDEX2" ON "OBJ_UNIQUE_DBL__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__9" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__9" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__9_INDEX1" ON "OBJ_UNIQUE_DBL__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__9_INDEX2" ON "OBJ_UNIQUE_DBL__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__10" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__10" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__10_INDEX1" ON "OBJ_UNIQUE_DBL__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__10_INDEX2" ON "OBJ_UNIQUE_DBL__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__11" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__11" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__11_INDEX1" ON "OBJ_UNIQUE_DBL__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__11_INDEX2" ON "OBJ_UNIQUE_DBL__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__12" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__12" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__12_INDEX1" ON "OBJ_UNIQUE_DBL__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__12_INDEX2" ON "OBJ_UNIQUE_DBL__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__13" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__13" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__13_INDEX1" ON "OBJ_UNIQUE_DBL__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__13_INDEX2" ON "OBJ_UNIQUE_DBL__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__14" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__14" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__14_INDEX1" ON "OBJ_UNIQUE_DBL__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__14_INDEX2" ON "OBJ_UNIQUE_DBL__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__15" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__15" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__15_INDEX1" ON "OBJ_UNIQUE_DBL__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__15_INDEX2" ON "OBJ_UNIQUE_DBL__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__16" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__16" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__16_INDEX1" ON "OBJ_UNIQUE_DBL__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__16_INDEX2" ON "OBJ_UNIQUE_DBL__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__17" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__17" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__17_INDEX1" ON "OBJ_UNIQUE_DBL__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__17_INDEX2" ON "OBJ_UNIQUE_DBL__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__18" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__18" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__18_INDEX1" ON "OBJ_UNIQUE_DBL__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__18_INDEX2" ON "OBJ_UNIQUE_DBL__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__19" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__19" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__19_INDEX1" ON "OBJ_UNIQUE_DBL__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__19_INDEX2" ON "OBJ_UNIQUE_DBL__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__20" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__20" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__20_INDEX1" ON "OBJ_UNIQUE_DBL__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__20_INDEX2" ON "OBJ_UNIQUE_DBL__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__21" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__21" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__21_INDEX1" ON "OBJ_UNIQUE_DBL__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__21_INDEX2" ON "OBJ_UNIQUE_DBL__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__22" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__22" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__22_INDEX1" ON "OBJ_UNIQUE_DBL__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__22_INDEX2" ON "OBJ_UNIQUE_DBL__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__23" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__23" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__23_INDEX1" ON "OBJ_UNIQUE_DBL__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__23_INDEX2" ON "OBJ_UNIQUE_DBL__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__24" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__24" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__24_INDEX1" ON "OBJ_UNIQUE_DBL__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__24_INDEX2" ON "OBJ_UNIQUE_DBL__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__25" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__25" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__25_INDEX1" ON "OBJ_UNIQUE_DBL__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__25_INDEX2" ON "OBJ_UNIQUE_DBL__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__26" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__26" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__26_INDEX1" ON "OBJ_UNIQUE_DBL__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__26_INDEX2" ON "OBJ_UNIQUE_DBL__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__27" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__27" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__27_INDEX1" ON "OBJ_UNIQUE_DBL__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__27_INDEX2" ON "OBJ_UNIQUE_DBL__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__28" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__28" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__28_INDEX1" ON "OBJ_UNIQUE_DBL__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__28_INDEX2" ON "OBJ_UNIQUE_DBL__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__29" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__29" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__29_INDEX1" ON "OBJ_UNIQUE_DBL__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__29_INDEX2" ON "OBJ_UNIQUE_DBL__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__30" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__30" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__30_INDEX1" ON "OBJ_UNIQUE_DBL__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__30_INDEX2" ON "OBJ_UNIQUE_DBL__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__31" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__31" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__31_INDEX1" ON "OBJ_UNIQUE_DBL__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__31_INDEX2" ON "OBJ_UNIQUE_DBL__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__32" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__32" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__32_INDEX1" ON "OBJ_UNIQUE_DBL__32" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__32_INDEX2" ON "OBJ_UNIQUE_DBL__32" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__33" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__33" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__33_INDEX1" ON "OBJ_UNIQUE_DBL__33" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__33_INDEX2" ON "OBJ_UNIQUE_DBL__33" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__34" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__34" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__34_INDEX1" ON "OBJ_UNIQUE_DBL__34" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__34_INDEX2" ON "OBJ_UNIQUE_DBL__34" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__35" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__35" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__35_INDEX1" ON "OBJ_UNIQUE_DBL__35" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__35_INDEX2" ON "OBJ_UNIQUE_DBL__35" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__36" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__36" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__36_INDEX1" ON "OBJ_UNIQUE_DBL__36" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__36_INDEX2" ON "OBJ_UNIQUE_DBL__36" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__37" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__37" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__37_INDEX1" ON "OBJ_UNIQUE_DBL__37" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__37_INDEX2" ON "OBJ_UNIQUE_DBL__37" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__38" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__38" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__38_INDEX1" ON "OBJ_UNIQUE_DBL__38" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__38_INDEX2" ON "OBJ_UNIQUE_DBL__38" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__39" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__39" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__39_INDEX1" ON "OBJ_UNIQUE_DBL__39" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__39_INDEX2" ON "OBJ_UNIQUE_DBL__39" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__40" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__40" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__40_INDEX1" ON "OBJ_UNIQUE_DBL__40" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__40_INDEX2" ON "OBJ_UNIQUE_DBL__40" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__41" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__41" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__41_INDEX1" ON "OBJ_UNIQUE_DBL__41" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__41_INDEX2" ON "OBJ_UNIQUE_DBL__41" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__42" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__42" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__42_INDEX1" ON "OBJ_UNIQUE_DBL__42" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__42_INDEX2" ON "OBJ_UNIQUE_DBL__42" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__43" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__43" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__43_INDEX1" ON "OBJ_UNIQUE_DBL__43" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__43_INDEX2" ON "OBJ_UNIQUE_DBL__43" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__44" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__44" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__44_INDEX1" ON "OBJ_UNIQUE_DBL__44" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__44_INDEX2" ON "OBJ_UNIQUE_DBL__44" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__45" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__45" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__45_INDEX1" ON "OBJ_UNIQUE_DBL__45" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__45_INDEX2" ON "OBJ_UNIQUE_DBL__45" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__46" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__46" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__46_INDEX1" ON "OBJ_UNIQUE_DBL__46" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__46_INDEX2" ON "OBJ_UNIQUE_DBL__46" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__47" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__47" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__47_INDEX1" ON "OBJ_UNIQUE_DBL__47" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__47_INDEX2" ON "OBJ_UNIQUE_DBL__47" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__48" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__48" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__48_INDEX1" ON "OBJ_UNIQUE_DBL__48" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__48_INDEX2" ON "OBJ_UNIQUE_DBL__48" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__49" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__49" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__49_INDEX1" ON "OBJ_UNIQUE_DBL__49" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__49_INDEX2" ON "OBJ_UNIQUE_DBL__49" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__50" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__50" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__50_INDEX1" ON "OBJ_UNIQUE_DBL__50" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__50_INDEX2" ON "OBJ_UNIQUE_DBL__50" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__51" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__51" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__51_INDEX1" ON "OBJ_UNIQUE_DBL__51" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__51_INDEX2" ON "OBJ_UNIQUE_DBL__51" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__52" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__52" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__52_INDEX1" ON "OBJ_UNIQUE_DBL__52" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__52_INDEX2" ON "OBJ_UNIQUE_DBL__52" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__53" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__53" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__53_INDEX1" ON "OBJ_UNIQUE_DBL__53" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__53_INDEX2" ON "OBJ_UNIQUE_DBL__53" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__54" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__54" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__54_INDEX1" ON "OBJ_UNIQUE_DBL__54" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__54_INDEX2" ON "OBJ_UNIQUE_DBL__54" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__55" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__55" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__55_INDEX1" ON "OBJ_UNIQUE_DBL__55" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__55_INDEX2" ON "OBJ_UNIQUE_DBL__55" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__56" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__56" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__56_INDEX1" ON "OBJ_UNIQUE_DBL__56" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__56_INDEX2" ON "OBJ_UNIQUE_DBL__56" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__57" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__57" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__57_INDEX1" ON "OBJ_UNIQUE_DBL__57" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__57_INDEX2" ON "OBJ_UNIQUE_DBL__57" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__58" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__58" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__58_INDEX1" ON "OBJ_UNIQUE_DBL__58" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__58_INDEX2" ON "OBJ_UNIQUE_DBL__58" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__59" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__59" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__59_INDEX1" ON "OBJ_UNIQUE_DBL__59" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__59_INDEX2" ON "OBJ_UNIQUE_DBL__59" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__60" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__60" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__60_INDEX1" ON "OBJ_UNIQUE_DBL__60" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__60_INDEX2" ON "OBJ_UNIQUE_DBL__60" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__61" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__61" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__61_INDEX1" ON "OBJ_UNIQUE_DBL__61" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__61_INDEX2" ON "OBJ_UNIQUE_DBL__61" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__62" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__62" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__62_INDEX1" ON "OBJ_UNIQUE_DBL__62" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__62_INDEX2" ON "OBJ_UNIQUE_DBL__62" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__63" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__63" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__63_INDEX1" ON "OBJ_UNIQUE_DBL__63" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__63_INDEX2" ON "OBJ_UNIQUE_DBL__63" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__64" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__64" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__64_INDEX1" ON "OBJ_UNIQUE_DBL__64" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__64_INDEX2" ON "OBJ_UNIQUE_DBL__64" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__65" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__65" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__65_INDEX1" ON "OBJ_UNIQUE_DBL__65" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__65_INDEX2" ON "OBJ_UNIQUE_DBL__65" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__66" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__66" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__66_INDEX1" ON "OBJ_UNIQUE_DBL__66" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__66_INDEX2" ON "OBJ_UNIQUE_DBL__66" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__67" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__67" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__67_INDEX1" ON "OBJ_UNIQUE_DBL__67" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__67_INDEX2" ON "OBJ_UNIQUE_DBL__67" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__68" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__68" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__68_INDEX1" ON "OBJ_UNIQUE_DBL__68" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__68_INDEX2" ON "OBJ_UNIQUE_DBL__68" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__69" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__69" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__69_INDEX1" ON "OBJ_UNIQUE_DBL__69" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__69_INDEX2" ON "OBJ_UNIQUE_DBL__69" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__70" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__70" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__70_INDEX1" ON "OBJ_UNIQUE_DBL__70" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__70_INDEX2" ON "OBJ_UNIQUE_DBL__70" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__71" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__71" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__71_INDEX1" ON "OBJ_UNIQUE_DBL__71" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__71_INDEX2" ON "OBJ_UNIQUE_DBL__71" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__72" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__72" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__72_INDEX1" ON "OBJ_UNIQUE_DBL__72" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__72_INDEX2" ON "OBJ_UNIQUE_DBL__72" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__73" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__73" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__73_INDEX1" ON "OBJ_UNIQUE_DBL__73" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__73_INDEX2" ON "OBJ_UNIQUE_DBL__73" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__74" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__74" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__74_INDEX1" ON "OBJ_UNIQUE_DBL__74" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__74_INDEX2" ON "OBJ_UNIQUE_DBL__74" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__75" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__75" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__75_INDEX1" ON "OBJ_UNIQUE_DBL__75" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__75_INDEX2" ON "OBJ_UNIQUE_DBL__75" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__76" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__76" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__76_INDEX1" ON "OBJ_UNIQUE_DBL__76" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__76_INDEX2" ON "OBJ_UNIQUE_DBL__76" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__77" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__77" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__77_INDEX1" ON "OBJ_UNIQUE_DBL__77" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__77_INDEX2" ON "OBJ_UNIQUE_DBL__77" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__78" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__78" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__78_INDEX1" ON "OBJ_UNIQUE_DBL__78" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__78_INDEX2" ON "OBJ_UNIQUE_DBL__78" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__79" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__79" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__79_INDEX1" ON "OBJ_UNIQUE_DBL__79" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__79_INDEX2" ON "OBJ_UNIQUE_DBL__79" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__80" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__80" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__80_INDEX1" ON "OBJ_UNIQUE_DBL__80" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__80_INDEX2" ON "OBJ_UNIQUE_DBL__80" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__81" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__81" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__81_INDEX1" ON "OBJ_UNIQUE_DBL__81" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__81_INDEX2" ON "OBJ_UNIQUE_DBL__81" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__82" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__82" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__82_INDEX1" ON "OBJ_UNIQUE_DBL__82" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__82_INDEX2" ON "OBJ_UNIQUE_DBL__82" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__83" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__83" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__83_INDEX1" ON "OBJ_UNIQUE_DBL__83" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__83_INDEX2" ON "OBJ_UNIQUE_DBL__83" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__84" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__84" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__84_INDEX1" ON "OBJ_UNIQUE_DBL__84" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__84_INDEX2" ON "OBJ_UNIQUE_DBL__84" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__85" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__85" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__85_INDEX1" ON "OBJ_UNIQUE_DBL__85" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__85_INDEX2" ON "OBJ_UNIQUE_DBL__85" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__86" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__86" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__86_INDEX1" ON "OBJ_UNIQUE_DBL__86" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__86_INDEX2" ON "OBJ_UNIQUE_DBL__86" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__87" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__87" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__87_INDEX1" ON "OBJ_UNIQUE_DBL__87" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__87_INDEX2" ON "OBJ_UNIQUE_DBL__87" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__88" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__88" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__88_INDEX1" ON "OBJ_UNIQUE_DBL__88" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__88_INDEX2" ON "OBJ_UNIQUE_DBL__88" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__89" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__89" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__89_INDEX1" ON "OBJ_UNIQUE_DBL__89" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__89_INDEX2" ON "OBJ_UNIQUE_DBL__89" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__90" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__90" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__90_INDEX1" ON "OBJ_UNIQUE_DBL__90" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__90_INDEX2" ON "OBJ_UNIQUE_DBL__90" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__91" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__91" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__91_INDEX1" ON "OBJ_UNIQUE_DBL__91" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__91_INDEX2" ON "OBJ_UNIQUE_DBL__91" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__92" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__92" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__92_INDEX1" ON "OBJ_UNIQUE_DBL__92" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__92_INDEX2" ON "OBJ_UNIQUE_DBL__92" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__93" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__93" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__93_INDEX1" ON "OBJ_UNIQUE_DBL__93" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__93_INDEX2" ON "OBJ_UNIQUE_DBL__93" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__94" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__94" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__94_INDEX1" ON "OBJ_UNIQUE_DBL__94" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__94_INDEX2" ON "OBJ_UNIQUE_DBL__94" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__95" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__95" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__95_INDEX1" ON "OBJ_UNIQUE_DBL__95" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__95_INDEX2" ON "OBJ_UNIQUE_DBL__95" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__96" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__96" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__96_INDEX1" ON "OBJ_UNIQUE_DBL__96" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__96_INDEX2" ON "OBJ_UNIQUE_DBL__96" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__97" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__97" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__97_INDEX1" ON "OBJ_UNIQUE_DBL__97" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__97_INDEX2" ON "OBJ_UNIQUE_DBL__97" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__98" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__98" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__98_INDEX1" ON "OBJ_UNIQUE_DBL__98" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__98_INDEX2" ON "OBJ_UNIQUE_DBL__98" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__99" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__99" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__99_INDEX1" ON "OBJ_UNIQUE_DBL__99" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__99_INDEX2" ON "OBJ_UNIQUE_DBL__99" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__100" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__100" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__100_INDEX1" ON "OBJ_UNIQUE_DBL__100" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__100_INDEX2" ON "OBJ_UNIQUE_DBL__100" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__101" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__101" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__101_INDEX1" ON "OBJ_UNIQUE_DBL__101" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__101_INDEX2" ON "OBJ_UNIQUE_DBL__101" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__102" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__102" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__102_INDEX1" ON "OBJ_UNIQUE_DBL__102" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__102_INDEX2" ON "OBJ_UNIQUE_DBL__102" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__103" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__103" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__103_INDEX1" ON "OBJ_UNIQUE_DBL__103" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__103_INDEX2" ON "OBJ_UNIQUE_DBL__103" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__104" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__104" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__104_INDEX1" ON "OBJ_UNIQUE_DBL__104" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__104_INDEX2" ON "OBJ_UNIQUE_DBL__104" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__105" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__105" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__105_INDEX1" ON "OBJ_UNIQUE_DBL__105" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__105_INDEX2" ON "OBJ_UNIQUE_DBL__105" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__106" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__106" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__106_INDEX1" ON "OBJ_UNIQUE_DBL__106" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__106_INDEX2" ON "OBJ_UNIQUE_DBL__106" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__107" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__107" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__107_INDEX1" ON "OBJ_UNIQUE_DBL__107" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__107_INDEX2" ON "OBJ_UNIQUE_DBL__107" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__108" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__108" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__108_INDEX1" ON "OBJ_UNIQUE_DBL__108" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__108_INDEX2" ON "OBJ_UNIQUE_DBL__108" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__109" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__109" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__109_INDEX1" ON "OBJ_UNIQUE_DBL__109" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__109_INDEX2" ON "OBJ_UNIQUE_DBL__109" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__110" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__110" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__110_INDEX1" ON "OBJ_UNIQUE_DBL__110" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__110_INDEX2" ON "OBJ_UNIQUE_DBL__110" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__111" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__111" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__111_INDEX1" ON "OBJ_UNIQUE_DBL__111" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__111_INDEX2" ON "OBJ_UNIQUE_DBL__111" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__112" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__112" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__112_INDEX1" ON "OBJ_UNIQUE_DBL__112" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__112_INDEX2" ON "OBJ_UNIQUE_DBL__112" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__113" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__113" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__113_INDEX1" ON "OBJ_UNIQUE_DBL__113" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__113_INDEX2" ON "OBJ_UNIQUE_DBL__113" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__114" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__114" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__114_INDEX1" ON "OBJ_UNIQUE_DBL__114" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__114_INDEX2" ON "OBJ_UNIQUE_DBL__114" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__115" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__115" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__115_INDEX1" ON "OBJ_UNIQUE_DBL__115" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__115_INDEX2" ON "OBJ_UNIQUE_DBL__115" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__116" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__116" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__116_INDEX1" ON "OBJ_UNIQUE_DBL__116" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__116_INDEX2" ON "OBJ_UNIQUE_DBL__116" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__117" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__117" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__117_INDEX1" ON "OBJ_UNIQUE_DBL__117" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__117_INDEX2" ON "OBJ_UNIQUE_DBL__117" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__118" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__118" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__118_INDEX1" ON "OBJ_UNIQUE_DBL__118" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__118_INDEX2" ON "OBJ_UNIQUE_DBL__118" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__119" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__119" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__119_INDEX1" ON "OBJ_UNIQUE_DBL__119" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__119_INDEX2" ON "OBJ_UNIQUE_DBL__119" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__120" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__120" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__120_INDEX1" ON "OBJ_UNIQUE_DBL__120" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__120_INDEX2" ON "OBJ_UNIQUE_DBL__120" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__121" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__121" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__121_INDEX1" ON "OBJ_UNIQUE_DBL__121" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__121_INDEX2" ON "OBJ_UNIQUE_DBL__121" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__122" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__122" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__122_INDEX1" ON "OBJ_UNIQUE_DBL__122" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__122_INDEX2" ON "OBJ_UNIQUE_DBL__122" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__123" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__123" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__123_INDEX1" ON "OBJ_UNIQUE_DBL__123" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__123_INDEX2" ON "OBJ_UNIQUE_DBL__123" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__124" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__124" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__124_INDEX1" ON "OBJ_UNIQUE_DBL__124" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__124_INDEX2" ON "OBJ_UNIQUE_DBL__124" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__125" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__125" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__125_INDEX1" ON "OBJ_UNIQUE_DBL__125" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__125_INDEX2" ON "OBJ_UNIQUE_DBL__125" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__126" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__126" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__126_INDEX1" ON "OBJ_UNIQUE_DBL__126" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__126_INDEX2" ON "OBJ_UNIQUE_DBL__126" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_DBL */
DROP TABLE "OBJ_UNIQUE_DBL__127" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_DBL__127" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" BINARY_DOUBLE
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_DBL__127_INDEX1" ON "OBJ_UNIQUE_DBL__127" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_DBL__127_INDEX2" ON "OBJ_UNIQUE_DBL__127" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;
