/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM_INDEX1" ON "OBJ_UNIQUE_NUM" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM_INDEX2" ON "OBJ_UNIQUE_NUM" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__1" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__1" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__1_INDEX1" ON "OBJ_UNIQUE_NUM__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__1_INDEX2" ON "OBJ_UNIQUE_NUM__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__2" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__2" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__2_INDEX1" ON "OBJ_UNIQUE_NUM__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__2_INDEX2" ON "OBJ_UNIQUE_NUM__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__3" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__3" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__3_INDEX1" ON "OBJ_UNIQUE_NUM__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__3_INDEX2" ON "OBJ_UNIQUE_NUM__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__4" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__4" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__4_INDEX1" ON "OBJ_UNIQUE_NUM__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__4_INDEX2" ON "OBJ_UNIQUE_NUM__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__5" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__5" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__5_INDEX1" ON "OBJ_UNIQUE_NUM__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__5_INDEX2" ON "OBJ_UNIQUE_NUM__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__6" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__6" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__6_INDEX1" ON "OBJ_UNIQUE_NUM__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__6_INDEX2" ON "OBJ_UNIQUE_NUM__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__7" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__7" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__7_INDEX1" ON "OBJ_UNIQUE_NUM__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__7_INDEX2" ON "OBJ_UNIQUE_NUM__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__8" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__8" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__8_INDEX1" ON "OBJ_UNIQUE_NUM__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__8_INDEX2" ON "OBJ_UNIQUE_NUM__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__9" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__9" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__9_INDEX1" ON "OBJ_UNIQUE_NUM__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__9_INDEX2" ON "OBJ_UNIQUE_NUM__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__10" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__10" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__10_INDEX1" ON "OBJ_UNIQUE_NUM__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__10_INDEX2" ON "OBJ_UNIQUE_NUM__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__11" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__11" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__11_INDEX1" ON "OBJ_UNIQUE_NUM__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__11_INDEX2" ON "OBJ_UNIQUE_NUM__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__12" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__12" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__12_INDEX1" ON "OBJ_UNIQUE_NUM__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__12_INDEX2" ON "OBJ_UNIQUE_NUM__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__13" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__13" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__13_INDEX1" ON "OBJ_UNIQUE_NUM__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__13_INDEX2" ON "OBJ_UNIQUE_NUM__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__14" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__14" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__14_INDEX1" ON "OBJ_UNIQUE_NUM__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__14_INDEX2" ON "OBJ_UNIQUE_NUM__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__15" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__15" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__15_INDEX1" ON "OBJ_UNIQUE_NUM__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__15_INDEX2" ON "OBJ_UNIQUE_NUM__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__16" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__16" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__16_INDEX1" ON "OBJ_UNIQUE_NUM__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__16_INDEX2" ON "OBJ_UNIQUE_NUM__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__17" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__17" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__17_INDEX1" ON "OBJ_UNIQUE_NUM__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__17_INDEX2" ON "OBJ_UNIQUE_NUM__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__18" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__18" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__18_INDEX1" ON "OBJ_UNIQUE_NUM__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__18_INDEX2" ON "OBJ_UNIQUE_NUM__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__19" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__19" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__19_INDEX1" ON "OBJ_UNIQUE_NUM__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__19_INDEX2" ON "OBJ_UNIQUE_NUM__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__20" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__20" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__20_INDEX1" ON "OBJ_UNIQUE_NUM__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__20_INDEX2" ON "OBJ_UNIQUE_NUM__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__21" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__21" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__21_INDEX1" ON "OBJ_UNIQUE_NUM__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__21_INDEX2" ON "OBJ_UNIQUE_NUM__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__22" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__22" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__22_INDEX1" ON "OBJ_UNIQUE_NUM__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__22_INDEX2" ON "OBJ_UNIQUE_NUM__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__23" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__23" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__23_INDEX1" ON "OBJ_UNIQUE_NUM__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__23_INDEX2" ON "OBJ_UNIQUE_NUM__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__24" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__24" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__24_INDEX1" ON "OBJ_UNIQUE_NUM__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__24_INDEX2" ON "OBJ_UNIQUE_NUM__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__25" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__25" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__25_INDEX1" ON "OBJ_UNIQUE_NUM__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__25_INDEX2" ON "OBJ_UNIQUE_NUM__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__26" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__26" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__26_INDEX1" ON "OBJ_UNIQUE_NUM__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__26_INDEX2" ON "OBJ_UNIQUE_NUM__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__27" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__27" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__27_INDEX1" ON "OBJ_UNIQUE_NUM__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__27_INDEX2" ON "OBJ_UNIQUE_NUM__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__28" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__28" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__28_INDEX1" ON "OBJ_UNIQUE_NUM__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__28_INDEX2" ON "OBJ_UNIQUE_NUM__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__29" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__29" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__29_INDEX1" ON "OBJ_UNIQUE_NUM__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__29_INDEX2" ON "OBJ_UNIQUE_NUM__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__30" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__30" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__30_INDEX1" ON "OBJ_UNIQUE_NUM__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__30_INDEX2" ON "OBJ_UNIQUE_NUM__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__31" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__31" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__31_INDEX1" ON "OBJ_UNIQUE_NUM__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__31_INDEX2" ON "OBJ_UNIQUE_NUM__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__32" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__32" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__32_INDEX1" ON "OBJ_UNIQUE_NUM__32" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__32_INDEX2" ON "OBJ_UNIQUE_NUM__32" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__33" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__33" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__33_INDEX1" ON "OBJ_UNIQUE_NUM__33" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__33_INDEX2" ON "OBJ_UNIQUE_NUM__33" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__34" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__34" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__34_INDEX1" ON "OBJ_UNIQUE_NUM__34" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__34_INDEX2" ON "OBJ_UNIQUE_NUM__34" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__35" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__35" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__35_INDEX1" ON "OBJ_UNIQUE_NUM__35" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__35_INDEX2" ON "OBJ_UNIQUE_NUM__35" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__36" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__36" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__36_INDEX1" ON "OBJ_UNIQUE_NUM__36" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__36_INDEX2" ON "OBJ_UNIQUE_NUM__36" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__37" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__37" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__37_INDEX1" ON "OBJ_UNIQUE_NUM__37" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__37_INDEX2" ON "OBJ_UNIQUE_NUM__37" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__38" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__38" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__38_INDEX1" ON "OBJ_UNIQUE_NUM__38" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__38_INDEX2" ON "OBJ_UNIQUE_NUM__38" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__39" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__39" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__39_INDEX1" ON "OBJ_UNIQUE_NUM__39" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__39_INDEX2" ON "OBJ_UNIQUE_NUM__39" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__40" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__40" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__40_INDEX1" ON "OBJ_UNIQUE_NUM__40" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__40_INDEX2" ON "OBJ_UNIQUE_NUM__40" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__41" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__41" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__41_INDEX1" ON "OBJ_UNIQUE_NUM__41" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__41_INDEX2" ON "OBJ_UNIQUE_NUM__41" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__42" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__42" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__42_INDEX1" ON "OBJ_UNIQUE_NUM__42" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__42_INDEX2" ON "OBJ_UNIQUE_NUM__42" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__43" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__43" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__43_INDEX1" ON "OBJ_UNIQUE_NUM__43" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__43_INDEX2" ON "OBJ_UNIQUE_NUM__43" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__44" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__44" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__44_INDEX1" ON "OBJ_UNIQUE_NUM__44" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__44_INDEX2" ON "OBJ_UNIQUE_NUM__44" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__45" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__45" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__45_INDEX1" ON "OBJ_UNIQUE_NUM__45" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__45_INDEX2" ON "OBJ_UNIQUE_NUM__45" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__46" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__46" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__46_INDEX1" ON "OBJ_UNIQUE_NUM__46" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__46_INDEX2" ON "OBJ_UNIQUE_NUM__46" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__47" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__47" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__47_INDEX1" ON "OBJ_UNIQUE_NUM__47" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__47_INDEX2" ON "OBJ_UNIQUE_NUM__47" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__48" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__48" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__48_INDEX1" ON "OBJ_UNIQUE_NUM__48" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__48_INDEX2" ON "OBJ_UNIQUE_NUM__48" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__49" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__49" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__49_INDEX1" ON "OBJ_UNIQUE_NUM__49" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__49_INDEX2" ON "OBJ_UNIQUE_NUM__49" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__50" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__50" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__50_INDEX1" ON "OBJ_UNIQUE_NUM__50" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__50_INDEX2" ON "OBJ_UNIQUE_NUM__50" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__51" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__51" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__51_INDEX1" ON "OBJ_UNIQUE_NUM__51" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__51_INDEX2" ON "OBJ_UNIQUE_NUM__51" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__52" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__52" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__52_INDEX1" ON "OBJ_UNIQUE_NUM__52" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__52_INDEX2" ON "OBJ_UNIQUE_NUM__52" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__53" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__53" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__53_INDEX1" ON "OBJ_UNIQUE_NUM__53" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__53_INDEX2" ON "OBJ_UNIQUE_NUM__53" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__54" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__54" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__54_INDEX1" ON "OBJ_UNIQUE_NUM__54" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__54_INDEX2" ON "OBJ_UNIQUE_NUM__54" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__55" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__55" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__55_INDEX1" ON "OBJ_UNIQUE_NUM__55" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__55_INDEX2" ON "OBJ_UNIQUE_NUM__55" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__56" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__56" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__56_INDEX1" ON "OBJ_UNIQUE_NUM__56" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__56_INDEX2" ON "OBJ_UNIQUE_NUM__56" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__57" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__57" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__57_INDEX1" ON "OBJ_UNIQUE_NUM__57" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__57_INDEX2" ON "OBJ_UNIQUE_NUM__57" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__58" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__58" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__58_INDEX1" ON "OBJ_UNIQUE_NUM__58" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__58_INDEX2" ON "OBJ_UNIQUE_NUM__58" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__59" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__59" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__59_INDEX1" ON "OBJ_UNIQUE_NUM__59" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__59_INDEX2" ON "OBJ_UNIQUE_NUM__59" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__60" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__60" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__60_INDEX1" ON "OBJ_UNIQUE_NUM__60" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__60_INDEX2" ON "OBJ_UNIQUE_NUM__60" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__61" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__61" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__61_INDEX1" ON "OBJ_UNIQUE_NUM__61" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__61_INDEX2" ON "OBJ_UNIQUE_NUM__61" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__62" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__62" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__62_INDEX1" ON "OBJ_UNIQUE_NUM__62" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__62_INDEX2" ON "OBJ_UNIQUE_NUM__62" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__63" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__63" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__63_INDEX1" ON "OBJ_UNIQUE_NUM__63" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__63_INDEX2" ON "OBJ_UNIQUE_NUM__63" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__64" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__64" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__64_INDEX1" ON "OBJ_UNIQUE_NUM__64" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__64_INDEX2" ON "OBJ_UNIQUE_NUM__64" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__65" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__65" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__65_INDEX1" ON "OBJ_UNIQUE_NUM__65" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__65_INDEX2" ON "OBJ_UNIQUE_NUM__65" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__66" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__66" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__66_INDEX1" ON "OBJ_UNIQUE_NUM__66" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__66_INDEX2" ON "OBJ_UNIQUE_NUM__66" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__67" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__67" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__67_INDEX1" ON "OBJ_UNIQUE_NUM__67" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__67_INDEX2" ON "OBJ_UNIQUE_NUM__67" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__68" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__68" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__68_INDEX1" ON "OBJ_UNIQUE_NUM__68" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__68_INDEX2" ON "OBJ_UNIQUE_NUM__68" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__69" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__69" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__69_INDEX1" ON "OBJ_UNIQUE_NUM__69" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__69_INDEX2" ON "OBJ_UNIQUE_NUM__69" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__70" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__70" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__70_INDEX1" ON "OBJ_UNIQUE_NUM__70" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__70_INDEX2" ON "OBJ_UNIQUE_NUM__70" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__71" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__71" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__71_INDEX1" ON "OBJ_UNIQUE_NUM__71" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__71_INDEX2" ON "OBJ_UNIQUE_NUM__71" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__72" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__72" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__72_INDEX1" ON "OBJ_UNIQUE_NUM__72" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__72_INDEX2" ON "OBJ_UNIQUE_NUM__72" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__73" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__73" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__73_INDEX1" ON "OBJ_UNIQUE_NUM__73" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__73_INDEX2" ON "OBJ_UNIQUE_NUM__73" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__74" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__74" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__74_INDEX1" ON "OBJ_UNIQUE_NUM__74" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__74_INDEX2" ON "OBJ_UNIQUE_NUM__74" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__75" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__75" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__75_INDEX1" ON "OBJ_UNIQUE_NUM__75" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__75_INDEX2" ON "OBJ_UNIQUE_NUM__75" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__76" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__76" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__76_INDEX1" ON "OBJ_UNIQUE_NUM__76" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__76_INDEX2" ON "OBJ_UNIQUE_NUM__76" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__77" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__77" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__77_INDEX1" ON "OBJ_UNIQUE_NUM__77" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__77_INDEX2" ON "OBJ_UNIQUE_NUM__77" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__78" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__78" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__78_INDEX1" ON "OBJ_UNIQUE_NUM__78" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__78_INDEX2" ON "OBJ_UNIQUE_NUM__78" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__79" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__79" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__79_INDEX1" ON "OBJ_UNIQUE_NUM__79" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__79_INDEX2" ON "OBJ_UNIQUE_NUM__79" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__80" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__80" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__80_INDEX1" ON "OBJ_UNIQUE_NUM__80" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__80_INDEX2" ON "OBJ_UNIQUE_NUM__80" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__81" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__81" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__81_INDEX1" ON "OBJ_UNIQUE_NUM__81" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__81_INDEX2" ON "OBJ_UNIQUE_NUM__81" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__82" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__82" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__82_INDEX1" ON "OBJ_UNIQUE_NUM__82" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__82_INDEX2" ON "OBJ_UNIQUE_NUM__82" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__83" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__83" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__83_INDEX1" ON "OBJ_UNIQUE_NUM__83" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__83_INDEX2" ON "OBJ_UNIQUE_NUM__83" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__84" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__84" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__84_INDEX1" ON "OBJ_UNIQUE_NUM__84" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__84_INDEX2" ON "OBJ_UNIQUE_NUM__84" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__85" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__85" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__85_INDEX1" ON "OBJ_UNIQUE_NUM__85" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__85_INDEX2" ON "OBJ_UNIQUE_NUM__85" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__86" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__86" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__86_INDEX1" ON "OBJ_UNIQUE_NUM__86" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__86_INDEX2" ON "OBJ_UNIQUE_NUM__86" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__87" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__87" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__87_INDEX1" ON "OBJ_UNIQUE_NUM__87" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__87_INDEX2" ON "OBJ_UNIQUE_NUM__87" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__88" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__88" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__88_INDEX1" ON "OBJ_UNIQUE_NUM__88" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__88_INDEX2" ON "OBJ_UNIQUE_NUM__88" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__89" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__89" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__89_INDEX1" ON "OBJ_UNIQUE_NUM__89" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__89_INDEX2" ON "OBJ_UNIQUE_NUM__89" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__90" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__90" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__90_INDEX1" ON "OBJ_UNIQUE_NUM__90" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__90_INDEX2" ON "OBJ_UNIQUE_NUM__90" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__91" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__91" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__91_INDEX1" ON "OBJ_UNIQUE_NUM__91" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__91_INDEX2" ON "OBJ_UNIQUE_NUM__91" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__92" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__92" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__92_INDEX1" ON "OBJ_UNIQUE_NUM__92" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__92_INDEX2" ON "OBJ_UNIQUE_NUM__92" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__93" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__93" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__93_INDEX1" ON "OBJ_UNIQUE_NUM__93" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__93_INDEX2" ON "OBJ_UNIQUE_NUM__93" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__94" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__94" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__94_INDEX1" ON "OBJ_UNIQUE_NUM__94" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__94_INDEX2" ON "OBJ_UNIQUE_NUM__94" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__95" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__95" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__95_INDEX1" ON "OBJ_UNIQUE_NUM__95" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__95_INDEX2" ON "OBJ_UNIQUE_NUM__95" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__96" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__96" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__96_INDEX1" ON "OBJ_UNIQUE_NUM__96" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__96_INDEX2" ON "OBJ_UNIQUE_NUM__96" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__97" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__97" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__97_INDEX1" ON "OBJ_UNIQUE_NUM__97" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__97_INDEX2" ON "OBJ_UNIQUE_NUM__97" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__98" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__98" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__98_INDEX1" ON "OBJ_UNIQUE_NUM__98" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__98_INDEX2" ON "OBJ_UNIQUE_NUM__98" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__99" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__99" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__99_INDEX1" ON "OBJ_UNIQUE_NUM__99" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__99_INDEX2" ON "OBJ_UNIQUE_NUM__99" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__100" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__100" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__100_INDEX1" ON "OBJ_UNIQUE_NUM__100" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__100_INDEX2" ON "OBJ_UNIQUE_NUM__100" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__101" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__101" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__101_INDEX1" ON "OBJ_UNIQUE_NUM__101" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__101_INDEX2" ON "OBJ_UNIQUE_NUM__101" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__102" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__102" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__102_INDEX1" ON "OBJ_UNIQUE_NUM__102" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__102_INDEX2" ON "OBJ_UNIQUE_NUM__102" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__103" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__103" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__103_INDEX1" ON "OBJ_UNIQUE_NUM__103" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__103_INDEX2" ON "OBJ_UNIQUE_NUM__103" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__104" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__104" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__104_INDEX1" ON "OBJ_UNIQUE_NUM__104" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__104_INDEX2" ON "OBJ_UNIQUE_NUM__104" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__105" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__105" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__105_INDEX1" ON "OBJ_UNIQUE_NUM__105" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__105_INDEX2" ON "OBJ_UNIQUE_NUM__105" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__106" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__106" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__106_INDEX1" ON "OBJ_UNIQUE_NUM__106" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__106_INDEX2" ON "OBJ_UNIQUE_NUM__106" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__107" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__107" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__107_INDEX1" ON "OBJ_UNIQUE_NUM__107" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__107_INDEX2" ON "OBJ_UNIQUE_NUM__107" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__108" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__108" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__108_INDEX1" ON "OBJ_UNIQUE_NUM__108" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__108_INDEX2" ON "OBJ_UNIQUE_NUM__108" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__109" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__109" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__109_INDEX1" ON "OBJ_UNIQUE_NUM__109" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__109_INDEX2" ON "OBJ_UNIQUE_NUM__109" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__110" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__110" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__110_INDEX1" ON "OBJ_UNIQUE_NUM__110" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__110_INDEX2" ON "OBJ_UNIQUE_NUM__110" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__111" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__111" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__111_INDEX1" ON "OBJ_UNIQUE_NUM__111" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__111_INDEX2" ON "OBJ_UNIQUE_NUM__111" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__112" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__112" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__112_INDEX1" ON "OBJ_UNIQUE_NUM__112" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__112_INDEX2" ON "OBJ_UNIQUE_NUM__112" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__113" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__113" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__113_INDEX1" ON "OBJ_UNIQUE_NUM__113" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__113_INDEX2" ON "OBJ_UNIQUE_NUM__113" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__114" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__114" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__114_INDEX1" ON "OBJ_UNIQUE_NUM__114" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__114_INDEX2" ON "OBJ_UNIQUE_NUM__114" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__115" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__115" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__115_INDEX1" ON "OBJ_UNIQUE_NUM__115" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__115_INDEX2" ON "OBJ_UNIQUE_NUM__115" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__116" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__116" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__116_INDEX1" ON "OBJ_UNIQUE_NUM__116" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__116_INDEX2" ON "OBJ_UNIQUE_NUM__116" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__117" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__117" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__117_INDEX1" ON "OBJ_UNIQUE_NUM__117" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__117_INDEX2" ON "OBJ_UNIQUE_NUM__117" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__118" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__118" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__118_INDEX1" ON "OBJ_UNIQUE_NUM__118" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__118_INDEX2" ON "OBJ_UNIQUE_NUM__118" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__119" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__119" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__119_INDEX1" ON "OBJ_UNIQUE_NUM__119" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__119_INDEX2" ON "OBJ_UNIQUE_NUM__119" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__120" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__120" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__120_INDEX1" ON "OBJ_UNIQUE_NUM__120" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__120_INDEX2" ON "OBJ_UNIQUE_NUM__120" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__121" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__121" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__121_INDEX1" ON "OBJ_UNIQUE_NUM__121" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__121_INDEX2" ON "OBJ_UNIQUE_NUM__121" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__122" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__122" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__122_INDEX1" ON "OBJ_UNIQUE_NUM__122" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__122_INDEX2" ON "OBJ_UNIQUE_NUM__122" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__123" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__123" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__123_INDEX1" ON "OBJ_UNIQUE_NUM__123" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__123_INDEX2" ON "OBJ_UNIQUE_NUM__123" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__124" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__124" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__124_INDEX1" ON "OBJ_UNIQUE_NUM__124" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__124_INDEX2" ON "OBJ_UNIQUE_NUM__124" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__125" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__125" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__125_INDEX1" ON "OBJ_UNIQUE_NUM__125" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__125_INDEX2" ON "OBJ_UNIQUE_NUM__125" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__126" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__126" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__126_INDEX1" ON "OBJ_UNIQUE_NUM__126" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__126_INDEX2" ON "OBJ_UNIQUE_NUM__126" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_UNIQUE_NUM */
DROP TABLE "OBJ_UNIQUE_NUM__127" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_UNIQUE_NUM__127" 
(
    "TENANT_ID" NUMBER(7,0) NOT NULL, 
    "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
    "COL_NAME" VARCHAR2(36) NOT NULL, 
    "OBJ_ID" VARCHAR2(64) NOT NULL,
    "VAL" NUMBER
)
;

CREATE UNIQUE INDEX "OBJ_UNIQUE_NUM__127_INDEX1" ON "OBJ_UNIQUE_NUM__127" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_UNIQUE_NUM__127_INDEX2" ON "OBJ_UNIQUE_NUM__127" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;
