/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR_INDEX1" ON "OBJ_INDEX_STR" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR_INDEX2" ON "OBJ_INDEX_STR" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__1" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__1" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__1_INDEX1" ON "OBJ_INDEX_STR__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__1_INDEX2" ON "OBJ_INDEX_STR__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__2" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__2" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__2_INDEX1" ON "OBJ_INDEX_STR__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__2_INDEX2" ON "OBJ_INDEX_STR__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__3" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__3" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__3_INDEX1" ON "OBJ_INDEX_STR__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__3_INDEX2" ON "OBJ_INDEX_STR__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__4" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__4" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__4_INDEX1" ON "OBJ_INDEX_STR__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__4_INDEX2" ON "OBJ_INDEX_STR__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__5" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__5" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__5_INDEX1" ON "OBJ_INDEX_STR__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__5_INDEX2" ON "OBJ_INDEX_STR__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__6" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__6" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__6_INDEX1" ON "OBJ_INDEX_STR__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__6_INDEX2" ON "OBJ_INDEX_STR__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__7" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__7" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__7_INDEX1" ON "OBJ_INDEX_STR__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__7_INDEX2" ON "OBJ_INDEX_STR__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__8" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__8" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__8_INDEX1" ON "OBJ_INDEX_STR__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__8_INDEX2" ON "OBJ_INDEX_STR__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__9" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__9" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__9_INDEX1" ON "OBJ_INDEX_STR__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__9_INDEX2" ON "OBJ_INDEX_STR__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__10" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__10" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__10_INDEX1" ON "OBJ_INDEX_STR__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__10_INDEX2" ON "OBJ_INDEX_STR__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__11" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__11" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__11_INDEX1" ON "OBJ_INDEX_STR__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__11_INDEX2" ON "OBJ_INDEX_STR__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__12" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__12" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__12_INDEX1" ON "OBJ_INDEX_STR__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__12_INDEX2" ON "OBJ_INDEX_STR__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__13" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__13" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__13_INDEX1" ON "OBJ_INDEX_STR__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__13_INDEX2" ON "OBJ_INDEX_STR__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__14" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__14" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__14_INDEX1" ON "OBJ_INDEX_STR__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__14_INDEX2" ON "OBJ_INDEX_STR__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__15" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__15" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__15_INDEX1" ON "OBJ_INDEX_STR__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__15_INDEX2" ON "OBJ_INDEX_STR__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__16" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__16" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__16_INDEX1" ON "OBJ_INDEX_STR__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__16_INDEX2" ON "OBJ_INDEX_STR__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__17" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__17" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__17_INDEX1" ON "OBJ_INDEX_STR__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__17_INDEX2" ON "OBJ_INDEX_STR__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__18" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__18" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__18_INDEX1" ON "OBJ_INDEX_STR__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__18_INDEX2" ON "OBJ_INDEX_STR__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__19" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__19" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__19_INDEX1" ON "OBJ_INDEX_STR__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__19_INDEX2" ON "OBJ_INDEX_STR__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__20" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__20" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__20_INDEX1" ON "OBJ_INDEX_STR__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__20_INDEX2" ON "OBJ_INDEX_STR__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__21" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__21" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__21_INDEX1" ON "OBJ_INDEX_STR__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__21_INDEX2" ON "OBJ_INDEX_STR__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__22" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__22" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__22_INDEX1" ON "OBJ_INDEX_STR__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__22_INDEX2" ON "OBJ_INDEX_STR__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__23" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__23" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__23_INDEX1" ON "OBJ_INDEX_STR__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__23_INDEX2" ON "OBJ_INDEX_STR__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__24" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__24" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__24_INDEX1" ON "OBJ_INDEX_STR__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__24_INDEX2" ON "OBJ_INDEX_STR__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__25" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__25" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__25_INDEX1" ON "OBJ_INDEX_STR__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__25_INDEX2" ON "OBJ_INDEX_STR__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__26" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__26" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__26_INDEX1" ON "OBJ_INDEX_STR__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__26_INDEX2" ON "OBJ_INDEX_STR__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__27" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__27" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__27_INDEX1" ON "OBJ_INDEX_STR__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__27_INDEX2" ON "OBJ_INDEX_STR__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__28" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__28" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__28_INDEX1" ON "OBJ_INDEX_STR__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__28_INDEX2" ON "OBJ_INDEX_STR__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__29" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__29" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__29_INDEX1" ON "OBJ_INDEX_STR__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__29_INDEX2" ON "OBJ_INDEX_STR__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__30" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__30" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__30_INDEX1" ON "OBJ_INDEX_STR__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__30_INDEX2" ON "OBJ_INDEX_STR__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__31" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__31" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__31_INDEX1" ON "OBJ_INDEX_STR__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__31_INDEX2" ON "OBJ_INDEX_STR__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__32" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__32" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__32_INDEX1" ON "OBJ_INDEX_STR__32" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__32_INDEX2" ON "OBJ_INDEX_STR__32" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__33" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__33" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__33_INDEX1" ON "OBJ_INDEX_STR__33" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__33_INDEX2" ON "OBJ_INDEX_STR__33" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__34" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__34" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__34_INDEX1" ON "OBJ_INDEX_STR__34" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__34_INDEX2" ON "OBJ_INDEX_STR__34" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__35" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__35" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__35_INDEX1" ON "OBJ_INDEX_STR__35" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__35_INDEX2" ON "OBJ_INDEX_STR__35" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__36" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__36" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__36_INDEX1" ON "OBJ_INDEX_STR__36" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__36_INDEX2" ON "OBJ_INDEX_STR__36" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__37" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__37" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__37_INDEX1" ON "OBJ_INDEX_STR__37" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__37_INDEX2" ON "OBJ_INDEX_STR__37" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__38" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__38" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__38_INDEX1" ON "OBJ_INDEX_STR__38" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__38_INDEX2" ON "OBJ_INDEX_STR__38" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__39" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__39" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__39_INDEX1" ON "OBJ_INDEX_STR__39" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__39_INDEX2" ON "OBJ_INDEX_STR__39" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__40" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__40" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__40_INDEX1" ON "OBJ_INDEX_STR__40" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__40_INDEX2" ON "OBJ_INDEX_STR__40" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__41" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__41" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__41_INDEX1" ON "OBJ_INDEX_STR__41" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__41_INDEX2" ON "OBJ_INDEX_STR__41" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__42" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__42" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__42_INDEX1" ON "OBJ_INDEX_STR__42" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__42_INDEX2" ON "OBJ_INDEX_STR__42" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__43" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__43" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__43_INDEX1" ON "OBJ_INDEX_STR__43" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__43_INDEX2" ON "OBJ_INDEX_STR__43" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__44" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__44" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__44_INDEX1" ON "OBJ_INDEX_STR__44" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__44_INDEX2" ON "OBJ_INDEX_STR__44" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__45" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__45" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__45_INDEX1" ON "OBJ_INDEX_STR__45" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__45_INDEX2" ON "OBJ_INDEX_STR__45" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__46" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__46" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__46_INDEX1" ON "OBJ_INDEX_STR__46" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__46_INDEX2" ON "OBJ_INDEX_STR__46" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__47" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__47" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__47_INDEX1" ON "OBJ_INDEX_STR__47" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__47_INDEX2" ON "OBJ_INDEX_STR__47" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__48" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__48" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__48_INDEX1" ON "OBJ_INDEX_STR__48" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__48_INDEX2" ON "OBJ_INDEX_STR__48" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__49" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__49" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__49_INDEX1" ON "OBJ_INDEX_STR__49" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__49_INDEX2" ON "OBJ_INDEX_STR__49" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__50" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__50" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__50_INDEX1" ON "OBJ_INDEX_STR__50" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__50_INDEX2" ON "OBJ_INDEX_STR__50" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__51" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__51" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__51_INDEX1" ON "OBJ_INDEX_STR__51" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__51_INDEX2" ON "OBJ_INDEX_STR__51" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__52" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__52" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__52_INDEX1" ON "OBJ_INDEX_STR__52" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__52_INDEX2" ON "OBJ_INDEX_STR__52" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__53" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__53" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__53_INDEX1" ON "OBJ_INDEX_STR__53" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__53_INDEX2" ON "OBJ_INDEX_STR__53" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__54" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__54" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__54_INDEX1" ON "OBJ_INDEX_STR__54" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__54_INDEX2" ON "OBJ_INDEX_STR__54" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__55" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__55" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__55_INDEX1" ON "OBJ_INDEX_STR__55" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__55_INDEX2" ON "OBJ_INDEX_STR__55" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__56" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__56" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__56_INDEX1" ON "OBJ_INDEX_STR__56" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__56_INDEX2" ON "OBJ_INDEX_STR__56" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__57" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__57" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__57_INDEX1" ON "OBJ_INDEX_STR__57" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__57_INDEX2" ON "OBJ_INDEX_STR__57" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__58" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__58" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__58_INDEX1" ON "OBJ_INDEX_STR__58" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__58_INDEX2" ON "OBJ_INDEX_STR__58" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__59" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__59" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__59_INDEX1" ON "OBJ_INDEX_STR__59" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__59_INDEX2" ON "OBJ_INDEX_STR__59" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__60" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__60" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__60_INDEX1" ON "OBJ_INDEX_STR__60" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__60_INDEX2" ON "OBJ_INDEX_STR__60" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__61" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__61" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__61_INDEX1" ON "OBJ_INDEX_STR__61" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__61_INDEX2" ON "OBJ_INDEX_STR__61" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__62" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__62" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__62_INDEX1" ON "OBJ_INDEX_STR__62" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__62_INDEX2" ON "OBJ_INDEX_STR__62" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__63" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__63" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__63_INDEX1" ON "OBJ_INDEX_STR__63" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__63_INDEX2" ON "OBJ_INDEX_STR__63" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__64" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__64" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__64_INDEX1" ON "OBJ_INDEX_STR__64" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__64_INDEX2" ON "OBJ_INDEX_STR__64" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__65" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__65" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__65_INDEX1" ON "OBJ_INDEX_STR__65" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__65_INDEX2" ON "OBJ_INDEX_STR__65" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__66" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__66" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__66_INDEX1" ON "OBJ_INDEX_STR__66" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__66_INDEX2" ON "OBJ_INDEX_STR__66" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__67" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__67" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__67_INDEX1" ON "OBJ_INDEX_STR__67" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__67_INDEX2" ON "OBJ_INDEX_STR__67" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__68" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__68" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__68_INDEX1" ON "OBJ_INDEX_STR__68" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__68_INDEX2" ON "OBJ_INDEX_STR__68" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__69" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__69" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__69_INDEX1" ON "OBJ_INDEX_STR__69" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__69_INDEX2" ON "OBJ_INDEX_STR__69" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__70" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__70" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__70_INDEX1" ON "OBJ_INDEX_STR__70" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__70_INDEX2" ON "OBJ_INDEX_STR__70" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__71" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__71" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__71_INDEX1" ON "OBJ_INDEX_STR__71" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__71_INDEX2" ON "OBJ_INDEX_STR__71" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__72" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__72" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__72_INDEX1" ON "OBJ_INDEX_STR__72" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__72_INDEX2" ON "OBJ_INDEX_STR__72" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__73" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__73" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__73_INDEX1" ON "OBJ_INDEX_STR__73" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__73_INDEX2" ON "OBJ_INDEX_STR__73" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__74" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__74" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__74_INDEX1" ON "OBJ_INDEX_STR__74" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__74_INDEX2" ON "OBJ_INDEX_STR__74" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__75" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__75" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__75_INDEX1" ON "OBJ_INDEX_STR__75" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__75_INDEX2" ON "OBJ_INDEX_STR__75" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__76" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__76" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__76_INDEX1" ON "OBJ_INDEX_STR__76" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__76_INDEX2" ON "OBJ_INDEX_STR__76" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__77" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__77" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__77_INDEX1" ON "OBJ_INDEX_STR__77" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__77_INDEX2" ON "OBJ_INDEX_STR__77" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__78" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__78" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__78_INDEX1" ON "OBJ_INDEX_STR__78" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__78_INDEX2" ON "OBJ_INDEX_STR__78" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__79" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__79" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__79_INDEX1" ON "OBJ_INDEX_STR__79" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__79_INDEX2" ON "OBJ_INDEX_STR__79" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__80" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__80" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__80_INDEX1" ON "OBJ_INDEX_STR__80" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__80_INDEX2" ON "OBJ_INDEX_STR__80" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__81" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__81" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__81_INDEX1" ON "OBJ_INDEX_STR__81" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__81_INDEX2" ON "OBJ_INDEX_STR__81" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__82" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__82" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__82_INDEX1" ON "OBJ_INDEX_STR__82" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__82_INDEX2" ON "OBJ_INDEX_STR__82" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__83" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__83" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__83_INDEX1" ON "OBJ_INDEX_STR__83" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__83_INDEX2" ON "OBJ_INDEX_STR__83" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__84" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__84" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__84_INDEX1" ON "OBJ_INDEX_STR__84" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__84_INDEX2" ON "OBJ_INDEX_STR__84" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__85" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__85" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__85_INDEX1" ON "OBJ_INDEX_STR__85" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__85_INDEX2" ON "OBJ_INDEX_STR__85" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__86" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__86" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__86_INDEX1" ON "OBJ_INDEX_STR__86" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__86_INDEX2" ON "OBJ_INDEX_STR__86" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__87" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__87" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__87_INDEX1" ON "OBJ_INDEX_STR__87" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__87_INDEX2" ON "OBJ_INDEX_STR__87" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__88" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__88" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__88_INDEX1" ON "OBJ_INDEX_STR__88" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__88_INDEX2" ON "OBJ_INDEX_STR__88" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__89" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__89" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__89_INDEX1" ON "OBJ_INDEX_STR__89" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__89_INDEX2" ON "OBJ_INDEX_STR__89" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__90" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__90" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__90_INDEX1" ON "OBJ_INDEX_STR__90" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__90_INDEX2" ON "OBJ_INDEX_STR__90" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__91" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__91" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__91_INDEX1" ON "OBJ_INDEX_STR__91" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__91_INDEX2" ON "OBJ_INDEX_STR__91" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__92" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__92" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__92_INDEX1" ON "OBJ_INDEX_STR__92" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__92_INDEX2" ON "OBJ_INDEX_STR__92" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__93" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__93" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__93_INDEX1" ON "OBJ_INDEX_STR__93" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__93_INDEX2" ON "OBJ_INDEX_STR__93" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__94" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__94" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__94_INDEX1" ON "OBJ_INDEX_STR__94" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__94_INDEX2" ON "OBJ_INDEX_STR__94" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__95" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__95" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__95_INDEX1" ON "OBJ_INDEX_STR__95" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__95_INDEX2" ON "OBJ_INDEX_STR__95" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__96" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__96" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__96_INDEX1" ON "OBJ_INDEX_STR__96" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__96_INDEX2" ON "OBJ_INDEX_STR__96" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__97" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__97" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__97_INDEX1" ON "OBJ_INDEX_STR__97" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__97_INDEX2" ON "OBJ_INDEX_STR__97" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__98" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__98" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__98_INDEX1" ON "OBJ_INDEX_STR__98" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__98_INDEX2" ON "OBJ_INDEX_STR__98" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__99" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__99" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__99_INDEX1" ON "OBJ_INDEX_STR__99" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__99_INDEX2" ON "OBJ_INDEX_STR__99" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__100" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__100" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__100_INDEX1" ON "OBJ_INDEX_STR__100" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__100_INDEX2" ON "OBJ_INDEX_STR__100" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__101" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__101" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__101_INDEX1" ON "OBJ_INDEX_STR__101" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__101_INDEX2" ON "OBJ_INDEX_STR__101" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__102" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__102" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__102_INDEX1" ON "OBJ_INDEX_STR__102" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__102_INDEX2" ON "OBJ_INDEX_STR__102" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__103" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__103" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__103_INDEX1" ON "OBJ_INDEX_STR__103" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__103_INDEX2" ON "OBJ_INDEX_STR__103" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__104" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__104" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__104_INDEX1" ON "OBJ_INDEX_STR__104" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__104_INDEX2" ON "OBJ_INDEX_STR__104" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__105" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__105" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__105_INDEX1" ON "OBJ_INDEX_STR__105" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__105_INDEX2" ON "OBJ_INDEX_STR__105" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__106" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__106" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__106_INDEX1" ON "OBJ_INDEX_STR__106" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__106_INDEX2" ON "OBJ_INDEX_STR__106" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__107" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__107" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__107_INDEX1" ON "OBJ_INDEX_STR__107" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__107_INDEX2" ON "OBJ_INDEX_STR__107" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__108" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__108" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__108_INDEX1" ON "OBJ_INDEX_STR__108" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__108_INDEX2" ON "OBJ_INDEX_STR__108" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__109" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__109" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__109_INDEX1" ON "OBJ_INDEX_STR__109" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__109_INDEX2" ON "OBJ_INDEX_STR__109" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__110" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__110" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__110_INDEX1" ON "OBJ_INDEX_STR__110" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__110_INDEX2" ON "OBJ_INDEX_STR__110" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__111" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__111" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__111_INDEX1" ON "OBJ_INDEX_STR__111" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__111_INDEX2" ON "OBJ_INDEX_STR__111" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__112" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__112" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__112_INDEX1" ON "OBJ_INDEX_STR__112" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__112_INDEX2" ON "OBJ_INDEX_STR__112" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__113" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__113" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__113_INDEX1" ON "OBJ_INDEX_STR__113" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__113_INDEX2" ON "OBJ_INDEX_STR__113" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__114" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__114" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__114_INDEX1" ON "OBJ_INDEX_STR__114" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__114_INDEX2" ON "OBJ_INDEX_STR__114" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__115" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__115" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__115_INDEX1" ON "OBJ_INDEX_STR__115" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__115_INDEX2" ON "OBJ_INDEX_STR__115" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__116" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__116" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__116_INDEX1" ON "OBJ_INDEX_STR__116" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__116_INDEX2" ON "OBJ_INDEX_STR__116" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__117" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__117" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__117_INDEX1" ON "OBJ_INDEX_STR__117" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__117_INDEX2" ON "OBJ_INDEX_STR__117" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__118" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__118" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__118_INDEX1" ON "OBJ_INDEX_STR__118" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__118_INDEX2" ON "OBJ_INDEX_STR__118" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__119" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__119" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__119_INDEX1" ON "OBJ_INDEX_STR__119" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__119_INDEX2" ON "OBJ_INDEX_STR__119" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__120" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__120" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__120_INDEX1" ON "OBJ_INDEX_STR__120" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__120_INDEX2" ON "OBJ_INDEX_STR__120" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__121" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__121" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__121_INDEX1" ON "OBJ_INDEX_STR__121" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__121_INDEX2" ON "OBJ_INDEX_STR__121" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__122" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__122" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__122_INDEX1" ON "OBJ_INDEX_STR__122" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__122_INDEX2" ON "OBJ_INDEX_STR__122" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__123" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__123" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__123_INDEX1" ON "OBJ_INDEX_STR__123" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__123_INDEX2" ON "OBJ_INDEX_STR__123" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__124" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__124" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__124_INDEX1" ON "OBJ_INDEX_STR__124" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__124_INDEX2" ON "OBJ_INDEX_STR__124" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__125" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__125" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__125_INDEX1" ON "OBJ_INDEX_STR__125" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__125_INDEX2" ON "OBJ_INDEX_STR__125" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__126" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__126" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__126_INDEX1" ON "OBJ_INDEX_STR__126" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__126_INDEX2" ON "OBJ_INDEX_STR__126" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__127" CASCADE CONSTRAINTS;

CREATE TABLE "OBJ_INDEX_STR__127" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__127_INDEX1" ON "OBJ_INDEX_STR__127" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__127_INDEX2" ON "OBJ_INDEX_STR__127" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;
