use mtdb
GO

DROP TABLE T_PASS_HI
GO

CREATE TABLE T_PASS_HI
(
    TENANT_ID NUMERIC(7) NOT NULL,
    ACCOUNT_ID VARCHAR(128) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    SALT VARCHAR(64),
    UP_DATE DATETIME2(3)
)
ON PS_MTDB (TENANT_ID)
GO

CREATE INDEX T_PASS_HI_INDEX ON T_PASS_HI (TENANT_ID, ACCOUNT_ID)
GO
