/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE_INDEX1" ON "OBJ_INDEX_DATE" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE_INDEX2" ON "OBJ_INDEX_DATE" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__1" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__1" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__1_INDEX1" ON "OBJ_INDEX_DATE__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__1_INDEX2" ON "OBJ_INDEX_DATE__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__2" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__2" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__2_INDEX1" ON "OBJ_INDEX_DATE__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__2_INDEX2" ON "OBJ_INDEX_DATE__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__3" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__3" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__3_INDEX1" ON "OBJ_INDEX_DATE__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__3_INDEX2" ON "OBJ_INDEX_DATE__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__4" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__4" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__4_INDEX1" ON "OBJ_INDEX_DATE__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__4_INDEX2" ON "OBJ_INDEX_DATE__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__5" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__5" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__5_INDEX1" ON "OBJ_INDEX_DATE__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__5_INDEX2" ON "OBJ_INDEX_DATE__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__6" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__6" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__6_INDEX1" ON "OBJ_INDEX_DATE__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__6_INDEX2" ON "OBJ_INDEX_DATE__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__7" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__7" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__7_INDEX1" ON "OBJ_INDEX_DATE__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__7_INDEX2" ON "OBJ_INDEX_DATE__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__8" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__8" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__8_INDEX1" ON "OBJ_INDEX_DATE__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__8_INDEX2" ON "OBJ_INDEX_DATE__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__9" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__9" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__9_INDEX1" ON "OBJ_INDEX_DATE__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__9_INDEX2" ON "OBJ_INDEX_DATE__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__10" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__10" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__10_INDEX1" ON "OBJ_INDEX_DATE__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__10_INDEX2" ON "OBJ_INDEX_DATE__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__11" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__11" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__11_INDEX1" ON "OBJ_INDEX_DATE__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__11_INDEX2" ON "OBJ_INDEX_DATE__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__12" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__12" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__12_INDEX1" ON "OBJ_INDEX_DATE__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__12_INDEX2" ON "OBJ_INDEX_DATE__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__13" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__13" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__13_INDEX1" ON "OBJ_INDEX_DATE__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__13_INDEX2" ON "OBJ_INDEX_DATE__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__14" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__14" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__14_INDEX1" ON "OBJ_INDEX_DATE__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__14_INDEX2" ON "OBJ_INDEX_DATE__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__15" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__15" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__15_INDEX1" ON "OBJ_INDEX_DATE__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__15_INDEX2" ON "OBJ_INDEX_DATE__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__16" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__16" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__16_INDEX1" ON "OBJ_INDEX_DATE__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__16_INDEX2" ON "OBJ_INDEX_DATE__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__17" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__17" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__17_INDEX1" ON "OBJ_INDEX_DATE__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__17_INDEX2" ON "OBJ_INDEX_DATE__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__18" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__18" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__18_INDEX1" ON "OBJ_INDEX_DATE__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__18_INDEX2" ON "OBJ_INDEX_DATE__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__19" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__19" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__19_INDEX1" ON "OBJ_INDEX_DATE__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__19_INDEX2" ON "OBJ_INDEX_DATE__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__20" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__20" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__20_INDEX1" ON "OBJ_INDEX_DATE__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__20_INDEX2" ON "OBJ_INDEX_DATE__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__21" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__21" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__21_INDEX1" ON "OBJ_INDEX_DATE__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__21_INDEX2" ON "OBJ_INDEX_DATE__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__22" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__22" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__22_INDEX1" ON "OBJ_INDEX_DATE__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__22_INDEX2" ON "OBJ_INDEX_DATE__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__23" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__23" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__23_INDEX1" ON "OBJ_INDEX_DATE__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__23_INDEX2" ON "OBJ_INDEX_DATE__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__24" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__24" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__24_INDEX1" ON "OBJ_INDEX_DATE__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__24_INDEX2" ON "OBJ_INDEX_DATE__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__25" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__25" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__25_INDEX1" ON "OBJ_INDEX_DATE__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__25_INDEX2" ON "OBJ_INDEX_DATE__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__26" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__26" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__26_INDEX1" ON "OBJ_INDEX_DATE__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__26_INDEX2" ON "OBJ_INDEX_DATE__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__27" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__27" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__27_INDEX1" ON "OBJ_INDEX_DATE__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__27_INDEX2" ON "OBJ_INDEX_DATE__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__28" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__28" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__28_INDEX1" ON "OBJ_INDEX_DATE__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__28_INDEX2" ON "OBJ_INDEX_DATE__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__29" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__29" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__29_INDEX1" ON "OBJ_INDEX_DATE__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__29_INDEX2" ON "OBJ_INDEX_DATE__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__30" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__30" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__30_INDEX1" ON "OBJ_INDEX_DATE__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__30_INDEX2" ON "OBJ_INDEX_DATE__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_DATE */
DROP TABLE "OBJ_INDEX_DATE__31" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_DATE__31" 
   (    "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" DATE
   )
;

CREATE INDEX "OBJ_INDEX_DATE__31_INDEX1" ON "OBJ_INDEX_DATE__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ; 
CREATE INDEX "OBJ_INDEX_DATE__31_INDEX2" ON "OBJ_INDEX_DATE__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

