/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS_INDEX1" ON "OBJ_INDEX_TS" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS_INDEX2" ON "OBJ_INDEX_TS" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__1"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__1" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__1_INDEX1" ON "OBJ_INDEX_TS__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__1_INDEX2" ON "OBJ_INDEX_TS__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__2"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__2" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__2_INDEX1" ON "OBJ_INDEX_TS__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__2_INDEX2" ON "OBJ_INDEX_TS__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__3"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__3" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__3_INDEX1" ON "OBJ_INDEX_TS__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__3_INDEX2" ON "OBJ_INDEX_TS__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__4"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__4" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__4_INDEX1" ON "OBJ_INDEX_TS__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__4_INDEX2" ON "OBJ_INDEX_TS__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__5"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__5" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__5_INDEX1" ON "OBJ_INDEX_TS__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__5_INDEX2" ON "OBJ_INDEX_TS__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__6"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__6" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__6_INDEX1" ON "OBJ_INDEX_TS__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__6_INDEX2" ON "OBJ_INDEX_TS__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__7"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__7" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__7_INDEX1" ON "OBJ_INDEX_TS__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__7_INDEX2" ON "OBJ_INDEX_TS__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__8"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__8" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__8_INDEX1" ON "OBJ_INDEX_TS__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__8_INDEX2" ON "OBJ_INDEX_TS__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__9"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__9" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__9_INDEX1" ON "OBJ_INDEX_TS__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__9_INDEX2" ON "OBJ_INDEX_TS__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__10"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__10" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__10_INDEX1" ON "OBJ_INDEX_TS__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__10_INDEX2" ON "OBJ_INDEX_TS__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__11"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__11" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__11_INDEX1" ON "OBJ_INDEX_TS__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__11_INDEX2" ON "OBJ_INDEX_TS__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__12"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__12" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__12_INDEX1" ON "OBJ_INDEX_TS__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__12_INDEX2" ON "OBJ_INDEX_TS__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__13"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__13" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__13_INDEX1" ON "OBJ_INDEX_TS__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__13_INDEX2" ON "OBJ_INDEX_TS__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__14"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__14" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__14_INDEX1" ON "OBJ_INDEX_TS__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__14_INDEX2" ON "OBJ_INDEX_TS__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__15"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__15" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__15_INDEX1" ON "OBJ_INDEX_TS__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__15_INDEX2" ON "OBJ_INDEX_TS__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__16"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__16" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__16_INDEX1" ON "OBJ_INDEX_TS__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__16_INDEX2" ON "OBJ_INDEX_TS__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__17"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__17" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__17_INDEX1" ON "OBJ_INDEX_TS__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__17_INDEX2" ON "OBJ_INDEX_TS__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__18"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__18" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__18_INDEX1" ON "OBJ_INDEX_TS__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__18_INDEX2" ON "OBJ_INDEX_TS__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__19"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__19" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__19_INDEX1" ON "OBJ_INDEX_TS__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__19_INDEX2" ON "OBJ_INDEX_TS__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__20"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__20" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__20_INDEX1" ON "OBJ_INDEX_TS__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__20_INDEX2" ON "OBJ_INDEX_TS__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__21"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__21" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__21_INDEX1" ON "OBJ_INDEX_TS__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__21_INDEX2" ON "OBJ_INDEX_TS__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__22"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__22" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__22_INDEX1" ON "OBJ_INDEX_TS__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__22_INDEX2" ON "OBJ_INDEX_TS__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__23"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__23" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__23_INDEX1" ON "OBJ_INDEX_TS__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__23_INDEX2" ON "OBJ_INDEX_TS__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__24"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__24" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__24_INDEX1" ON "OBJ_INDEX_TS__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__24_INDEX2" ON "OBJ_INDEX_TS__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__25"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__25" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__25_INDEX1" ON "OBJ_INDEX_TS__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__25_INDEX2" ON "OBJ_INDEX_TS__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__26"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__26" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__26_INDEX1" ON "OBJ_INDEX_TS__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__26_INDEX2" ON "OBJ_INDEX_TS__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__27"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__27" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__27_INDEX1" ON "OBJ_INDEX_TS__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__27_INDEX2" ON "OBJ_INDEX_TS__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__28"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__28" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__28_INDEX1" ON "OBJ_INDEX_TS__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__28_INDEX2" ON "OBJ_INDEX_TS__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__29"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__29" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__29_INDEX1" ON "OBJ_INDEX_TS__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__29_INDEX2" ON "OBJ_INDEX_TS__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__30"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__30" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__30_INDEX1" ON "OBJ_INDEX_TS__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__30_INDEX2" ON "OBJ_INDEX_TS__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_TS */
DROP TABLE "OBJ_INDEX_TS__31"  CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_TS__31" 
(       "TENANT_ID" NUMBER(7,0) NOT NULL, 
        "OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
        "COL_NAME" VARCHAR2(36) NOT NULL, 
        "OBJ_ID" VARCHAR2(64) NOT NULL,
        "OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
        "VAL" TIMESTAMP(3)
)
;

CREATE INDEX "OBJ_INDEX_TS__31_INDEX1" ON "OBJ_INDEX_TS__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_TS__31_INDEX2" ON "OBJ_INDEX_TS__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

