/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR_INDEX1" ON "OBJ_INDEX_STR" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR_INDEX2" ON "OBJ_INDEX_STR" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__1" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__1" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__1_INDEX1" ON "OBJ_INDEX_STR__1" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__1_INDEX2" ON "OBJ_INDEX_STR__1" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__2" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__2" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__2_INDEX1" ON "OBJ_INDEX_STR__2" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__2_INDEX2" ON "OBJ_INDEX_STR__2" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__3" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__3" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__3_INDEX1" ON "OBJ_INDEX_STR__3" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__3_INDEX2" ON "OBJ_INDEX_STR__3" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__4" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__4" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__4_INDEX1" ON "OBJ_INDEX_STR__4" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__4_INDEX2" ON "OBJ_INDEX_STR__4" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__5" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__5" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__5_INDEX1" ON "OBJ_INDEX_STR__5" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__5_INDEX2" ON "OBJ_INDEX_STR__5" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__6" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__6" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__6_INDEX1" ON "OBJ_INDEX_STR__6" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__6_INDEX2" ON "OBJ_INDEX_STR__6" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__7" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__7" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__7_INDEX1" ON "OBJ_INDEX_STR__7" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__7_INDEX2" ON "OBJ_INDEX_STR__7" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__8" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__8" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__8_INDEX1" ON "OBJ_INDEX_STR__8" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__8_INDEX2" ON "OBJ_INDEX_STR__8" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__9" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__9" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__9_INDEX1" ON "OBJ_INDEX_STR__9" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__9_INDEX2" ON "OBJ_INDEX_STR__9" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__10" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__10" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__10_INDEX1" ON "OBJ_INDEX_STR__10" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__10_INDEX2" ON "OBJ_INDEX_STR__10" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__11" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__11" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__11_INDEX1" ON "OBJ_INDEX_STR__11" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__11_INDEX2" ON "OBJ_INDEX_STR__11" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__12" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__12" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__12_INDEX1" ON "OBJ_INDEX_STR__12" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__12_INDEX2" ON "OBJ_INDEX_STR__12" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__13" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__13" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__13_INDEX1" ON "OBJ_INDEX_STR__13" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__13_INDEX2" ON "OBJ_INDEX_STR__13" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__14" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__14" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__14_INDEX1" ON "OBJ_INDEX_STR__14" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__14_INDEX2" ON "OBJ_INDEX_STR__14" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__15" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__15" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__15_INDEX1" ON "OBJ_INDEX_STR__15" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__15_INDEX2" ON "OBJ_INDEX_STR__15" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__16" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__16" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__16_INDEX1" ON "OBJ_INDEX_STR__16" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__16_INDEX2" ON "OBJ_INDEX_STR__16" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__17" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__17" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__17_INDEX1" ON "OBJ_INDEX_STR__17" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__17_INDEX2" ON "OBJ_INDEX_STR__17" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__18" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__18" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__18_INDEX1" ON "OBJ_INDEX_STR__18" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__18_INDEX2" ON "OBJ_INDEX_STR__18" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__19" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__19" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__19_INDEX1" ON "OBJ_INDEX_STR__19" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__19_INDEX2" ON "OBJ_INDEX_STR__19" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__20" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__20" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__20_INDEX1" ON "OBJ_INDEX_STR__20" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__20_INDEX2" ON "OBJ_INDEX_STR__20" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__21" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__21" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__21_INDEX1" ON "OBJ_INDEX_STR__21" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__21_INDEX2" ON "OBJ_INDEX_STR__21" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__22" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__22" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__22_INDEX1" ON "OBJ_INDEX_STR__22" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__22_INDEX2" ON "OBJ_INDEX_STR__22" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__23" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__23" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__23_INDEX1" ON "OBJ_INDEX_STR__23" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__23_INDEX2" ON "OBJ_INDEX_STR__23" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__24" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__24" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__24_INDEX1" ON "OBJ_INDEX_STR__24" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__24_INDEX2" ON "OBJ_INDEX_STR__24" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__25" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__25" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__25_INDEX1" ON "OBJ_INDEX_STR__25" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__25_INDEX2" ON "OBJ_INDEX_STR__25" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__26" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__26" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__26_INDEX1" ON "OBJ_INDEX_STR__26" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__26_INDEX2" ON "OBJ_INDEX_STR__26" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__27" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__27" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__27_INDEX1" ON "OBJ_INDEX_STR__27" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__27_INDEX2" ON "OBJ_INDEX_STR__27" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__28" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__28" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__28_INDEX1" ON "OBJ_INDEX_STR__28" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__28_INDEX2" ON "OBJ_INDEX_STR__28" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__29" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__29" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__29_INDEX1" ON "OBJ_INDEX_STR__29" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__29_INDEX2" ON "OBJ_INDEX_STR__29" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__30" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__30" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__30_INDEX1" ON "OBJ_INDEX_STR__30" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__30_INDEX2" ON "OBJ_INDEX_STR__30" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

/* drop/create OBJ_INDEX_STR */
DROP TABLE "OBJ_INDEX_STR__31" CASCADE CONSTRAINT;

CREATE TABLE "OBJ_INDEX_STR__31" 
(
	"TENANT_ID" NUMBER(7,0) NOT NULL, 
	"OBJ_DEF_ID" VARCHAR2(128) NOT NULL, 
	"COL_NAME" VARCHAR2(36) NOT NULL, 
	"OBJ_ID" VARCHAR2(64) NOT NULL,
	"OBJ_VER" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"VAL" VARCHAR2(4000)
)
;

CREATE INDEX "OBJ_INDEX_STR__31_INDEX1" ON "OBJ_INDEX_STR__31" ("TENANT_ID", "OBJ_DEF_ID", "COL_NAME", "VAL") ;
CREATE INDEX "OBJ_INDEX_STR__31_INDEX2" ON "OBJ_INDEX_STR__31" ("TENANT_ID", "OBJ_DEF_ID", "OBJ_ID") ;

