name: Java Format Check

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  java-format-check:
    name: Java Format Check
    permissions:
      contents: read
    runs-on: ubuntu-slim
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck --no-daemon
