name: Java Format Check

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  java-format-check:
    name: Java Format Check
    permissions:
      contents: read
    runs-on: ubuntu-slim
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Spotless Check
        run: |
          if [ -n "${{github.base_ref}}" ]; then
            ./gradlew spotlessCheck --no-daemon -PdiffBase=origin/${{github.base_ref}}
          else
            ./gradlew spotlessCheck --no-daemon
          fi
